/**
 * S9 拆分:emit provider data —— 每 provider 的 data/<id>.json(按 api 分组)与
 * <id>.models.ts 类型派生 shard。
 *
 * 模型清单只写入生成的 data JSON;shard 只导入该 JSON 并委托
 * `flattenModelCatalog` 推导类型,不再逐模型枚举 id/api(对照 pi 的 model-catalog)。
 * 输出排序确定性;packageRoot/pretty 由主入口注入。
 */

import { mkdirSync, readdirSync, rmSync, writeFileSync } from "fs";
import { join } from "path";
import type { Model } from "../../src/types.ts";

export const GENERATED_HEADER = `// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

`;

/** 扁平 catalog:provider -> model id -> Model;公开 JSON dump 与排序基准。 */
export function buildSortedJsonProviders(
	providers: Record<string, Record<string, Model<any>>>,
): Record<string, Record<string, Model<any>>> {
	const sortedProviderIds = Object.keys(providers).sort();
	const jsonProviders: Record<string, Record<string, Model<any>>> = {};
	for (const providerId of sortedProviderIds) {
		jsonProviders[providerId] = {};
		for (const modelId of Object.keys(providers[providerId]).sort()) {
			jsonProviders[providerId][modelId] = providers[providerId][modelId];
		}
	}
	return jsonProviders;
}

/**
 * 内部 data 结构:provider -> api -> model id -> Model。
 *
 * api 分组键是 `ModelCatalog` 推导模型 api 类型的唯一来源,因此内部 data
 * 必须保留分组;provider 内 api 键与 model id 都按字典序排序。
 */
export function buildApiGroupedProviders(
	providers: Record<string, Record<string, Model<any>>>,
): Record<string, Record<string, Record<string, Model<any>>>> {
	const sorted = buildSortedJsonProviders(providers);
	const grouped: Record<string, Record<string, Record<string, Model<any>>>> = {};
	for (const providerId of Object.keys(sorted)) {
		const byApi: Record<string, Record<string, Model<any>>> = {};
		for (const modelId of Object.keys(sorted[providerId])) {
			const model = sorted[providerId][modelId];
			const api = String(model.api);
			const bucket = (byApi[api] ??= {});
			bucket[modelId] = model;
		}
		const ordered: Record<string, Record<string, Model<any>>> = {};
		for (const api of Object.keys(byApi).sort()) {
			ordered[api] = byApi[api];
		}
		grouped[providerId] = ordered;
	}
	return grouped;
}

function writeJson(path: string, value: unknown, pretty: boolean): void {
	writeFileSync(path, `${JSON.stringify(value, null, pretty ? 2 : undefined)}\n`);
}

/** 写 src/providers/data/<id>.json 与 src/providers/<id>.models.ts(删除陈旧 catalog 后)。 */
export function emitProviderData(
	providers: Record<string, Record<string, Model<any>>>,
	options: { packageRoot: string; pretty: boolean },
): void {
	const { packageRoot, pretty } = options;
	const catalogConstName = (providerId: string) =>
		`${providerId.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}_MODELS`;
	const providersDir = join(packageRoot, "src/providers");
	const dataDir = join(providersDir, "data");
	const groupedProviders = buildApiGroupedProviders(providers);

	// Remove stale per-provider catalogs and their generated values.
	for (const entry of readdirSync(providersDir)) {
		if (entry.endsWith(".models.ts")) {
			rmSync(join(providersDir, entry));
		}
	}
	rmSync(dataDir, { recursive: true, force: true });
	mkdirSync(dataDir, { recursive: true });

	// Per-provider grouped values and their type-derivation shards (sorted for deterministic output).
	for (const providerId of Object.keys(groupedProviders)) {
		let output = GENERATED_HEADER;
		output += `import values from "./data/${providerId}.json" with { type: "json" };\n`;
		output += `import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";\n\n`;
		output += `export const ${catalogConstName(providerId)}: ModelCatalog<typeof values, ${JSON.stringify(providerId)}> =\n`;
		output += `\tflattenModelCatalog(${JSON.stringify(providerId)}, values);\n`;
		writeFileSync(join(providersDir, `${providerId}.models.ts`), output);
		writeJson(join(dataDir, `${providerId}.json`), groupedProviders[providerId], pretty);
	}
	console.log(`Generated ${Object.keys(groupedProviders).length} catalog shards under src/providers/`);
	console.log("Generated grouped JSON model values under src/providers/data/");
}
