/**
 * S9 拆分:emit provider data —— 每 provider 的 .models.ts 结构 catalog 与 data/*.json 值。
 *
 * 输出与旧 generate-models.ts 内联 emit 块逐字节一致(排序确定性);
 * packageRoot/pretty 由主入口注入。
 */

import { mkdirSync, readdirSync, rmSync, writeFileSync } from "fs";
import { join } from "path";
import type { Model } from "../../src/types.ts";

export const GENERATED_HEADER = `// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

`;

export function buildSortedJsonProviders(providers: Record<string, Record<string, Model<any>>>): Record<string, Record<string, Model<any>>> {
	const sortedProviderIds = Object.keys(providers).sort();
	const jsonProviders: Record<string, Record<string, Model<any>>> = {};
	for (const providerId of sortedProviderIds) {
		jsonProviders[providerId] = {};
		for (const modelId of Object.keys(providers[providerId]).sort()) {
			jsonProviders[providerId][modelId] = providers[providerId][modelId];
		}
	}
	return jsonProviders;
}

function writeJson(path: string, value: unknown, pretty: boolean): void {
	writeFileSync(path, `${JSON.stringify(value, null, pretty ? 2 : undefined)}\n`);
}

/** 写 src/providers/<id>.models.ts + src/providers/data/<id>.json(删除陈旧 catalog 后)。 */
export function emitProviderData(
	providers: Record<string, Record<string, Model<any>>>,
	options: { packageRoot: string; pretty: boolean },
): void {
	const { packageRoot, pretty } = options;
	const catalogConstName = (providerId: string) =>
		`${providerId.toUpperCase().replace(/[^A-Z0-9]+/g, "_")}_MODELS`;
	const providersDir = join(packageRoot, "src/providers");
	const dataDir = join(providersDir, "data");
	const jsonProviders = buildSortedJsonProviders(providers);

	function emitModelShape(model: Model<any>, indent: string): string {
		return `${indent}${JSON.stringify(model.id)}: Model<${JSON.stringify(model.api)}> & {\n${indent}\tid: ${JSON.stringify(model.id)};\n${indent}\tprovider: ${JSON.stringify(model.provider)};\n${indent}};\n`;
	}

	// Remove stale per-provider catalogs and their generated values.
	for (const entry of readdirSync(providersDir)) {
		if (entry.endsWith(".models.ts")) {
			rmSync(join(providersDir, entry));
		}
	}
	rmSync(dataDir, { recursive: true, force: true });
	mkdirSync(dataDir, { recursive: true });

	// Per-provider catalog structure and values (sorted for deterministic output).
	const sortedProviderIds = Object.keys(providers).sort();
	for (const providerId of sortedProviderIds) {
		const models = providers[providerId];
		const sortedModelIds = Object.keys(models).sort();
		let output = GENERATED_HEADER;
		output += `import values from "./data/${providerId}.json" with { type: "json" };\n`;
		output += `import type { Model } from "../types.ts";\n\n`;
		output += `export const ${catalogConstName(providerId)} = values as {\n`;
		for (const modelId of sortedModelIds) {
			output += emitModelShape(models[modelId], "\t");
		}
		output += `};\n`;
		writeFileSync(join(providersDir, `${providerId}.models.ts`), output);
		writeJson(join(dataDir, `${providerId}.json`), jsonProviders[providerId], pretty);
	}
	console.log(`Generated ${sortedProviderIds.length} catalog structures under src/providers/`);
	console.log("Generated JSON model values under src/providers/data/");
}
