/** Runtime 公共 contract 的机器可读盘点。 */

export type ContractPersistenceClass =
	| "canonical_durable"
	| "external_authority_ref"
	| "reconstructible_passive"
	| "ephemeral"
	| "forbidden";

export interface ContractInventoryEntry {
	readonly id: string;
	readonly owner: string;
	readonly modules: readonly string[];
	readonly types: readonly string[];
	readonly schemas: readonly string[];
	readonly events: readonly string[];
	readonly ports: readonly string[];
	readonly fixtures: readonly string[];
	readonly persistence: readonly ContractPersistenceClass[];
	readonly gaps: readonly string[];
}

export interface ContractHandoff {
	readonly behavior: string;
	readonly owner: string;
	readonly contracts: readonly string[];
	readonly availability: "external_plan" | "existing_behavior" | "unavailable";
}

export interface PassivePersistencePolicy {
	readonly contract: string;
	readonly classification: ContractPersistenceClass;
	readonly retention: string;
	readonly redaction: string;
	readonly forbiddenFields: readonly string[];
}

export const PERSISTENCE_CLASSES = [
	"canonical_durable",
	"external_authority_ref",
	"reconstructible_passive",
	"ephemeral",
	"forbidden",
] as const satisfies readonly ContractPersistenceClass[];

const DEFAULT_FORBIDDEN_FIELDS = ["absolutePath", "token", "secret", "rawContent", "processHandle"] as const;

function passivePolicy(
	contract: string,
	classification: ContractPersistenceClass,
	retention: string,
	redaction: string,
	forbiddenFields: readonly string[] = DEFAULT_FORBIDDEN_FIELDS,
): PassivePersistencePolicy {
	return { contract, classification, retention, redaction, forbiddenFields };
}

/** 每个 passive DTO 的保存分类；行为实现不得据此扩大保存范围或执行授权。 */
export const PASSIVE_PERSISTENCE_POLICIES = [
	passivePolicy("SessionProjection", "reconstructible_passive", "rebuildable_from_source_head", "metadata_only"),
	passivePolicy("GoalProjection", "reconstructible_passive", "rebuildable_from_source_head", "content_ref_only"),
	passivePolicy("TaskProjection", "reconstructible_passive", "rebuildable_from_source_head", "content_ref_only"),
	passivePolicy("QueueProjection", "reconstructible_passive", "rebuildable_from_source_head", "content_ref_only"),
	passivePolicy("AgentGraphProjection", "reconstructible_passive", "rebuildable_from_source_head", "content_ref_only"),
	passivePolicy("RuntimeSnapshotDescriptor", "reconstructible_passive", "rebuildable_from_source_range", "content_ref_only"),
	passivePolicy("WorkspaceExecutionEnvelope", "ephemeral", "request_lifetime", "digest_only"),
	passivePolicy("WorkspaceBindingRef", "external_authority_ref", "binding_revision_lifetime", "digest_only"),
	passivePolicy("WorkspaceLeaseRef", "external_authority_ref", "lease_revision_lifetime", "digest_only", ["fencingToken", "token", "secret", "absolutePath"]),
	passivePolicy("WorkspaceValidationReceiptRef", "external_authority_ref", "receipt_retention_policy", "digest_only"),
	passivePolicy("WorkspaceCheckpointDescriptor", "reconstructible_passive", "rebuildable_from_event_head", "content_ref_only"),
	passivePolicy("CapabilityClaim", "canonical_durable", "subject_event_lifetime", "digest_only"),
	passivePolicy("CapabilityRequest", "ephemeral", "request_lifetime", "digest_only", ["nonce", "credential", "token", "secret"]),
	passivePolicy("CapabilityDecisionReceipt", "external_authority_ref", "decision_revision_lifetime", "digest_only"),
	passivePolicy("ApprovalTicket", "external_authority_ref", "ticket_expiry_or_terminal", "metadata_only"),
	passivePolicy("ApprovalReceiptRef", "external_authority_ref", "receipt_retention_policy", "digest_only"),
	passivePolicy("RateLimitReceiptRef", "external_authority_ref", "window_and_receipt_lifetime", "digest_only"),
	passivePolicy("CredentialGrantRef", "external_authority_ref", "grant_expiry_or_revocation", "digest_only", ["credential", "token", "secret"]),
	passivePolicy("SandboxProfileRef", "external_authority_ref", "policy_revision_lifetime", "digest_only"),
	passivePolicy("SandboxExecutionReceiptRef", "external_authority_ref", "receipt_retention_policy", "digest_only"),
	passivePolicy("ArtifactRef", "external_authority_ref", "artifact_retention_graph", "metadata_only", ["content", "absolutePath", "token", "secret"]),
	passivePolicy("ResourceIdentity", "canonical_durable", "resource_revision_lifetime", "digest_only"),
	passivePolicy("ResourceProvenance", "external_authority_ref", "resource_revision_lifetime", "digest_only"),
	passivePolicy("ResourceApprovalReceipt", "external_authority_ref", "approval_expiry_or_revocation", "digest_only"),
	passivePolicy("RuntimeToolDescriptor", "reconstructible_passive", "snapshot_generation_lifetime", "content_ref_only", ["handler", "client", "process", "absolutePath", "token"]),
	passivePolicy("RuntimeToolInvocation", "ephemeral", "request_lifetime", "content_ref_only", ["input", "credential", "token", "secret"]),
	passivePolicy("RuntimeToolResult", "ephemeral", "request_lifetime", "bounded_inline_or_ref"),
	passivePolicy("RuntimeResourceSnapshot", "reconstructible_passive", "snapshot_generation_lifetime", "content_ref_only"),
	passivePolicy("ResourceLifecycleEvent", "canonical_durable", "event_stream_retention", "digest_only"),
	passivePolicy("ModelCapabilityProfile", "external_authority_ref", "manifest_revision_lifetime", "content_ref_only"),
	passivePolicy("ModelRouteRequest", "ephemeral", "request_lifetime", "digest_only"),
	passivePolicy("ModelRouteDecision", "canonical_durable", "event_stream_retention", "content_ref_only"),
	passivePolicy("PlanArtifactRef", "external_authority_ref", "plan_revision_lifetime", "content_ref_only"),
	passivePolicy("PlanApprovalRef", "external_authority_ref", "approval_revision_lifetime", "digest_only"),
	passivePolicy("PlanModeState", "reconstructible_passive", "rebuildable_from_source_head", "content_ref_only"),
	passivePolicy("ContextFragment", "ephemeral", "assembly_lifetime", "content_ref_only", ["content", "prompt", "privateReasoning", "token"]),
	passivePolicy("ContextAssemblyRequest", "ephemeral", "request_lifetime", "content_ref_only"),
	passivePolicy("ContextAssemblyReceipt", "reconstructible_passive", "rebuildable_from_source_head", "digest_only"),
	passivePolicy("CompactionCheckpoint", "reconstructible_passive", "rebuildable_from_source_range", "content_ref_only", ["summary", "prompt", "privateReasoning", "token"]),
	passivePolicy("MemoryRecord", "canonical_durable", "memory_scope_retention", "content_ref_only", ["body", "content", "credential", "token"]),
	passivePolicy("MemoryProposal", "canonical_durable", "proposal_terminal_retention", "digest_only"),
	passivePolicy("MemorySearchReceipt", "reconstructible_passive", "index_generation_lifetime", "digest_only"),
	passivePolicy("ArtifactIntent", "canonical_durable", "intent_terminal_retention", "digest_only"),
	passivePolicy("ArtifactCommitReceipt", "canonical_durable", "artifact_retention_graph", "content_ref_only"),
	passivePolicy("ProjectionCheckpoint", "reconstructible_passive", "rebuildable_from_source_range", "content_ref_only"),
	passivePolicy("CompositeCheckpoint", "reconstructible_passive", "rebuildable_from_event_head", "content_ref_only"),
	passivePolicy("EpisodeManifestBody", "canonical_durable", "episode_retention_graph", "content_ref_only"),
	passivePolicy("EpisodeSeal", "canonical_durable", "episode_retention_graph", "digest_only"),
	passivePolicy("VerificationRequest", "ephemeral", "request_lifetime", "content_ref_only"),
	passivePolicy("VerificationResult", "canonical_durable", "evidence_retention_graph", "content_ref_only"),
	passivePolicy("FindingRecord", "canonical_durable", "finding_revision_lifetime", "content_ref_only"),
	passivePolicy("ChangeProposal", "canonical_durable", "proposal_terminal_retention", "content_ref_only", ["diff", "credential", "token", "secret"]),
	passivePolicy("RuntimeActivity", "reconstructible_passive", "activity_cache_lifetime", "digest_only"),
	passivePolicy("ProductionCompositionReceipt", "external_authority_ref", "generation_expiry_lifetime", "digest_only", ["adapter", "client", "handler", "credential"]),
	passivePolicy("ManagedPolicyRef", "external_authority_ref", "policy_revision_lifetime", "digest_only"),
	passivePolicy("CostRecord", "canonical_durable", "cost_reconciliation_lifetime", "digest_only"),
	passivePolicy("TelemetryManifest", "external_authority_ref", "manifest_revision_lifetime", "digest_only", ["environment", "cookie", "token", "secret"]),
	passivePolicy("RemoteInvocationRef", "external_authority_ref", "receipt_retention_policy", "content_ref_only", ["credential", "token", "secret", "executorHandle"]),
	passivePolicy("LifecycleRef", "external_authority_ref", "reference_graph_retention", "content_ref_only"),
] as const satisfies readonly PassivePersistencePolicy[];

export const CONTRACT_DIRECTORY_ALLOWLIST = [
	"src/runtime/contracts",
	"src/runtime/protocol",
	"src/runtime/identity",
	"src/runtime/resources",
	"src/runtime/model-routing",
	"src/runtime/modes",
	"src/runtime/context",
] as const;

export const CONTRACT_INVENTORY = [
	{
		id: "foundation",
		owner: "development-doc/runtime/04-governed-agent-harness-runtime-plan.md#contract-foundation",
		modules: [
			"src/runtime/protocol/ids.ts",
			"src/runtime/protocol/canonical-json.ts",
			"src/runtime/protocol/foundation.ts",
			"src/runtime/protocol/foundation-schemas.ts",
			"src/runtime/protocol/errors.ts",
		],
		types: [
			"RuntimeId",
			"RuntimeIdKind",
			"CanonicalJsonValue",
			"RuntimeDigest",
			"RuntimeContentRef",
			"RuntimeRevisionRef",
			"RuntimeStreamHead",
			"RuntimeErrorShape",
			"RuntimeContractError",
		],
		schemas: [
			"parseRuntimeId",
			"isRuntimeId",
			"canonicalJson",
			"canonicalDigest",
			"RuntimeIdSchema",
			"RuntimeDigestSchema",
			"RuntimeContentRefSchema",
			"RuntimeRevisionRefSchema",
			"RuntimeStreamHeadSchema",
			"RuntimeErrorShapeSchema",
		],
		events: [],
		ports: [],
		fixtures: ["tests/runtime-contracts/canonical-json.test.ts", "tests/runtime-contracts/schema.test.ts"],
		persistence: ["canonical_durable", "external_authority_ref"],
		gaps: [],
	},
	{
		id: "identity",
		owner: "development-doc/runtime/04-governed-agent-harness-runtime-plan.md#contract-foundation",
		modules: ["src/runtime/identity/types.ts", "src/runtime/identity/schemas.ts"],
		types: ["IdentityContext"],
		schemas: ["IdentityContextSchema", "isIdentityContext"],
		events: [],
		ports: [],
		fixtures: ["tests/runtime-contracts/schema.test.ts"],
		persistence: ["canonical_durable", "external_authority_ref", "forbidden"],
		gaps: [],
	},
	{
		id: "events",
		owner: "development-doc/runtime/04-governed-agent-harness-runtime-plan.md#contract-events",
		modules: ["src/runtime/protocol/events.ts", "src/runtime/protocol/schemas.ts"],
		types: [
			"RuntimeEventType",
			"RuntimeEventPayloadByType",
			"RuntimeEventEnvelope",
			"RuntimeEvent",
			"RuntimeStreamRef",
			"RuntimeEventRangeRef",
			"DurableEventReceipt",
			"AppendEventOutcome",
		],
		schemas: [
			"RUNTIME_EVENT_PAYLOAD_SCHEMAS",
			"RuntimeEventEnvelopeSchema",
			"DurableEventReceiptSchema",
			"AppendEventOutcomeSchema",
			"RuntimeEventRangeRefSchema",
			"validateRuntimeEvent",
			"assertRuntimeEvent",
		],
		events: ["RUNTIME_EVENT_TYPES"],
		ports: [],
		fixtures: [
			"tests/runtime-contracts/schema.test.ts",
			"tests/runtime-contracts/event-contracts.test.ts",
			"tests/runtime-contracts/event-durability.test.ts",
		],
		persistence: ["canonical_durable", "ephemeral", "forbidden"],
		gaps: [],
	},
	{
		id: "passive-state",
		owner: "development-doc/runtime/04-governed-agent-harness-runtime-plan.md#contract-session",
		modules: [
			"src/runtime/contracts/passive-state.ts",
			"src/runtime/contracts/passive-state-schemas.ts",
		],
		types: [
			"SessionProjection",
			"GoalProjection",
			"TaskProjection",
			"QueueProjection",
			"AgentGraphProjection",
			"RuntimeSnapshotDescriptor",
		],
		schemas: ["RUNTIME_PROJECTION_SCHEMAS", "RuntimeSnapshotDescriptorSchema"],
		events: [],
		ports: [],
		fixtures: ["tests/runtime-contracts/passive-state-contracts.test.ts"],
		persistence: ["reconstructible_passive", "external_authority_ref", "forbidden"],
		gaps: [],
	},
	{
		id: "workspace-security",
		owner: "development-doc/worktree-sandbox-permisson/00-worktree-sandbox-permission-plan.md",
		modules: ["src/runtime/protocol/workspace.ts", "src/runtime/protocol/capability.ts"],
		types: [
			"WorkspaceExecutionEnvelope",
			"WorkspaceBindingRef",
			"WorkspaceLeaseRef",
			"WorkspaceValidationReceiptRef",
			"WorkspaceCheckpointDescriptor",
			"CapabilityClaim",
			"CapabilityRequest",
			"CapabilityDecisionReceipt",
			"ApprovalTicket",
			"ApprovalReceiptRef",
			"RateLimitReceiptRef",
			"CredentialGrantRef",
			"SandboxProfileRef",
			"SandboxExecutionReceiptRef",
			"ArtifactRef",
		],
		schemas: [
			"WorkspaceExecutionEnvelopeSchema",
			"WorkspaceBindingRefSchema",
			"WorkspaceLeaseRefSchema",
			"WorkspaceValidationReceiptRefSchema",
			"WorkspaceCheckpointDescriptorSchema",
			"CapabilityClaimSchema",
			"CapabilityRequestSchema",
			"CapabilityDecisionReceiptSchema",
			"ApprovalTicketSchema",
			"ApprovalReceiptRefSchema",
			"RateLimitReceiptRefSchema",
			"CredentialGrantRefSchema",
			"SandboxProfileRefSchema",
			"SandboxExecutionReceiptRefSchema",
			"ArtifactRefSchema",
		],
		events: ["workspace.*", "permission.*", "sandbox.*", "lease.*"],
		ports: ["WorkspaceServicePort", "CapabilityGatewayPort", "ApprovalCoordinatorPort", "SandboxExecutionPort"],
		fixtures: [
			"tests/security/current-runtime-boundary.test.ts",
			"tests/runtime-contracts/workspace-security-contracts.test.ts",
			"tests/runtime-contracts/capability-security-contracts.test.ts",
		],
		persistence: ["canonical_durable", "external_authority_ref", "reconstructible_passive", "forbidden"],
		gaps: [],
	},
	{
		id: "resources",
		owner: "development-doc/plugin-mcp-skill-hooks/01-implementation-plan.md",
		modules: [
			"src/runtime/resources/types.ts",
			"src/runtime/resources/schemas.ts",
			"src/runtime/resources/events.ts",
			"src/runtime/resources/ports.ts",
		],
		types: [
			"ResourceIdentity",
			"ResourceProvenance",
			"ResourceApprovalReceipt",
			"RuntimeToolDescriptor",
			"RuntimeToolInvocation",
			"RuntimeToolResult",
			"ResourceContent",
			"RuntimeResourceSnapshot",
		],
		schemas: [
			"ResourceIdentitySchema",
			"ResourceApprovalReceiptSchema",
			"RuntimeToolDescriptorSchema",
			"RuntimeToolInvocationSchema",
			"RuntimeToolResultSchema",
			"RuntimeResourceSnapshotSchema",
			"ResourceLifecycleEventSchema",
		],
		events: ["ResourceLifecycleEvent"],
		ports: [
			"RuntimeResourceCatalogPort",
			"RuntimeResourceInvocationPort",
			"RuntimeResourceEventSink",
			"RuntimeResourceSnapshotProvider",
		],
		fixtures: [
			"tests/runtime-contracts/resource-contracts/contracts.test.ts",
			"tests/runtime-contracts/resource-contracts/passive-contracts.test.ts",
		],
		persistence: ["canonical_durable", "external_authority_ref", "reconstructible_passive", "ephemeral", "forbidden"],
		gaps: [],
	},
	{
		id: "model-routing",
		owner: "development-doc/plan-compact-memory/01-implementation-plan.md",
		modules: ["src/runtime/model-routing/types.ts", "src/runtime/model-routing/schema.ts"],
		types: ["ModelCapabilityProfile", "ModelRouteRequest", "ModelRouteDecision"],
		schemas: ["ModelCapabilityProfileSchema", "ModelRouteRequestSchema", "ModelRouteDecisionSchema"],
		events: ["model.routed"],
		ports: ["ModelStreamPort"],
		fixtures: ["tests/runtime-contracts/plan-context-memory/contract-consumer.test.ts"],
		persistence: ["canonical_durable", "external_authority_ref", "reconstructible_passive"],
		gaps: [],
	},
	{
		id: "plan-mode",
		owner: "development-doc/plan-compact-memory/01-implementation-plan.md",
		modules: ["src/runtime/modes/plan/types.ts", "src/runtime/modes/plan/schema.ts"],
		types: ["PlanArtifactRef", "PlanApprovalRef", "PlanModeState"],
		schemas: ["PlanArtifactRefSchema", "PlanApprovalRefSchema", "PlanModeStateSchema"],
		events: ["plan.enter_requested", "plan.entered", "plan.approval_requested", "plan.approved", "plan.exit_requested", "plan.exited", "plan.failed"],
		ports: [],
		fixtures: ["tests/runtime-contracts/plan-context-memory/contract-consumer.test.ts"],
		persistence: ["canonical_durable", "external_authority_ref", "reconstructible_passive"],
		gaps: [],
	},
	{
		id: "context",
		owner: "development-doc/plan-compact-memory/01-implementation-plan.md",
		modules: ["src/runtime/context/types.ts", "src/runtime/context/schema.ts"],
		types: ["ContextFragment", "ContextAssemblyRequest", "ContextAssemblyReceipt"],
		schemas: ["ContextFragmentSchema", "ContextAssemblyRequestSchema", "ContextAssemblyReceiptSchema"],
		events: ["context.assembled"],
		ports: [],
		fixtures: ["tests/runtime-contracts/plan-context-memory/contract-consumer.test.ts"],
		persistence: ["canonical_durable", "reconstructible_passive", "ephemeral", "forbidden"],
		gaps: [],
	},
	{
		id: "compaction",
		owner: "development-doc/plan-compact-memory/01-implementation-plan.md",
		modules: ["src/runtime/context/compaction/types.ts", "src/runtime/context/compaction/schema.ts"],
		types: ["CompactionCheckpoint"],
		schemas: ["CompactionCheckpointSchema"],
		events: ["compaction.started", "compaction.completed", "compaction.failed"],
		ports: [],
		fixtures: ["tests/runtime-contracts/plan-context-memory/contract-consumer.test.ts"],
		persistence: ["canonical_durable", "reconstructible_passive", "external_authority_ref"],
		gaps: [],
	},
	{
		id: "memory",
		owner: "development-doc/plan-compact-memory/01-implementation-plan.md",
		modules: ["src/runtime/context/memory/types.ts", "src/runtime/context/memory/schema.ts"],
		types: ["MemoryRecord", "MemoryProposal", "MemorySearchReceipt"],
		schemas: ["MemoryRecordSchema", "MemoryProposalSchema", "MemorySearchReceiptSchema"],
		events: ["memory.proposed", "memory.approved", "memory.revoked", "memory.search_recorded"],
		ports: [],
		fixtures: ["tests/runtime-contracts/plan-context-memory/contract-consumer.test.ts"],
		persistence: ["canonical_durable", "reconstructible_passive", "forbidden"],
		gaps: [],
	},
	{
		id: "artifact-evidence",
		owner: "development-doc/runtime/04-governed-agent-harness-runtime-plan.md#contract-artifact-evidence",
		modules: [
			"src/runtime/contracts/evidence.ts",
			"src/runtime/contracts/evidence-schemas.ts",
		],
		types: [
			"ArtifactIntent",
			"ArtifactCommitReceipt",
			"ProjectionCheckpoint",
			"CompositeCheckpoint",
			"EpisodeManifestBody",
			"EpisodeSeal",
			"VerificationRequest",
			"VerificationResult",
			"FindingRecord",
			"ChangeProposal",
		],
		schemas: [
			"ArtifactIntentSchema",
			"ArtifactCommitReceiptSchema",
			"ProjectionCheckpointSchema",
			"CompositeCheckpointSchema",
			"EpisodeManifestBodySchema",
			"EpisodeSealSchema",
			"VerificationRequestSchema",
			"VerificationResultSchema",
			"FindingRecordSchema",
			"ChangeProposalSchema",
		],
		events: ["checkpoint.*", "artifact.*", "episode.*", "verification.*", "finding.*", "change_proposal.*", "draft_pr.*", "human_gate.*"],
		ports: ["ArtifactStorePort", "VerificationRunnerPort", "ForgeProviderPort", "HumanGatePort"],
		fixtures: ["tests/runtime-contracts/evidence-control-passive-contracts.test.ts"],
		persistence: ["canonical_durable", "external_authority_ref", "reconstructible_passive", "ephemeral", "forbidden"],
		gaps: [],
	},
	{
		id: "user-home-layout",
		owner: "development-doc/runtime/04-governed-agent-harness-runtime-plan.md#contract-persistence",
		modules: ["src/runtime/contracts/storage-layout.ts"],
		types: ["RunledgerHomeResolution", "RunledgerLayout", "RuntimeLocator"],
		schemas: ["RuntimeLocatorSchema", "isRuntimeLocator"],
		events: [],
		ports: [],
		fixtures: ["tests/runtime-contracts/storage-layout-contracts.test.ts"],
		persistence: ["canonical_durable", "external_authority_ref", "reconstructible_passive", "ephemeral", "forbidden"],
		gaps: [],
	},
	{
		id: "control-telemetry",
		owner: "development-doc/runtime/04-governed-agent-harness-runtime-plan.md#contract-control-telemetry",
		modules: [
			"src/runtime/contracts/control-telemetry.ts",
			"src/runtime/contracts/control-telemetry-schemas.ts",
		],
		types: [
			"AdapterIdentityRef",
			"RuntimeActivity",
			"ProductionCompositionReceipt",
			"ManagedPolicyRef",
			"CostRecord",
			"TelemetryManifest",
			"RemoteInvocationRef",
			"LifecycleRef",
		],
		schemas: [
			"AdapterIdentityRefSchema",
			"RuntimeActivitySchema",
			"ProductionCompositionReceiptSchema",
			"ManagedPolicyRefSchema",
			"CostRecordSchema",
			"TelemetryManifestSchema",
			"RemoteInvocationRefSchema",
			"LifecycleRefSchema",
		],
		events: [
			"command.*",
			"runtime.*",
			"policy.*",
			"cost.*",
			"telemetry.*",
		],
		ports: ["RuntimeEventStorePort", "RuntimeEventSubscriptionPort", "TelemetryExporterPort", "RemoteExecutorPort"],
		fixtures: ["tests/runtime-contracts/evidence-control-passive-contracts.test.ts"],
		persistence: ["canonical_durable", "external_authority_ref", "reconstructible_passive", "ephemeral", "forbidden"],
		gaps: [],
	},
] as const satisfies readonly ContractInventoryEntry[];

export const CONTRACT_HANDOFFS = [
	{
		behavior: "Plugin, MCP, Skill, and Hook discovery, trust, process, and control",
		owner: "development-doc/plugin-mcp-skill-hooks/01-implementation-plan.md",
		contracts: ["resources"],
		availability: "external_plan",
	},
	{
		behavior: "Workspace, permission, approval, credential, gateway, and sandbox",
		owner: "development-doc/worktree-sandbox-permisson/00-worktree-sandbox-permission-plan.md",
		contracts: ["workspace-security"],
		availability: "external_plan",
	},
	{
		behavior: "Model routing, plan, context, compaction, and memory",
		owner: "development-doc/plan-compact-memory/01-implementation-plan.md",
		contracts: ["model-routing", "plan-mode", "context", "compaction", "memory"],
		availability: "external_plan",
	},
	{
		behavior: "Provider, API, authentication, and model catalog",
		owner: "development-doc/providers/01-pi-ai-migration-plan.md",
		contracts: ["model-routing", "context"],
		availability: "existing_behavior",
	},
	{
		behavior: "Agent loop, Agent, ledger, and standard tools",
		owner: "development-doc/runtime/01-minimum-runtime-scaffold-plan.md",
		contracts: ["events", "workspace-security", "resources"],
		availability: "existing_behavior",
	},
	{
		behavior: "User home creation, legacy import, and CLI option deprecation",
		owner: "development-doc/storage-cli/01-project-layout-cli-plan.md",
		contracts: ["user-home-layout"],
		availability: "external_plan",
	},
	{
		behavior: "Event store writer, replay, reducer, and recovery",
		owner: "no authorized behavior plan",
		contracts: ["events", "control-telemetry"],
		availability: "unavailable",
	},
	{
		behavior: "Artifact CAS, redaction, retention, and garbage collection",
		owner: "no authorized behavior plan",
		contracts: ["workspace-security", "control-telemetry"],
		availability: "unavailable",
	},
	{
		behavior: "Orchestration, verification, and multi-agent execution",
		owner: "no authorized behavior plan",
		contracts: ["events", "control-telemetry"],
		availability: "unavailable",
	},
	{
		behavior: "Daemon, control plane, forge, and human gates",
		owner: "no authorized behavior plan",
		contracts: ["control-telemetry"],
		availability: "unavailable",
	},
	{
		behavior: "Telemetry export, remote execution, and lifecycle services",
		owner: "no authorized behavior plan",
		contracts: ["control-telemetry"],
		availability: "unavailable",
	},
	{
		behavior: "TUI, CLI, IDE, and CI clients",
		owner: "product-specific plans",
		contracts: ["events", "resources", "control-telemetry"],
		availability: "external_plan",
	},
] as const satisfies readonly ContractHandoff[];
