import { contractAssistantMessage } from "../../tui/fixtures/contract-integration.ts";
import type { ToolAuthorizationPolicy } from "../../../src/runtime/types.ts";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { createEmbeddedSessionRuntime } from "../../../src/cli/embedded-session-runtime.ts";
import { claimDriver, fetchDomainSnapshot, pauseIfLastAttachment } from "../../../src/cli/main.ts";
import { SessionInteractiveController } from "../../../src/cli/session-interactive-controller.ts";
import { builtinModels } from "../../../src/providers/all.ts";
import { buildRunledgerLayout } from "../../../src/runtime/contracts/storage-layout.ts";
import { resolveAgentMode } from "../../../src/runtime/harness-profiles/agent-mode.ts";
import { isValidPlanModeState } from "../../../src/runtime/modes/plan/reducer.ts";
import { createRuntimeId } from "../../../src/runtime/protocol/ids.ts";
import type { ExecutionEnv } from "../../../src/runtime/execution-env.ts";
import type { SessionDomainPort } from "../../../src/runtime/session-runtime/session-runtime.ts";
import type { AgentTool } from "../../../src/runtime/types.ts";
import { AuthStorage } from "../../../src/storage/auth-storage.ts";
import { openSessionDatabase } from "../../../src/storage/session-store/database.ts";
import { OwnerStore } from "../../../src/storage/session-store/owner-store.ts";
import { installSessionStoreSchema } from "../../../src/storage/session-store/schema.ts";
import { SessionStore } from "../../../src/storage/session-store/session-store.ts";

describe("production Plan agent mode", () => {
	it("keeps workspace effects denied while writing, approving and restoring a pinned plan", async () => {
		const mode = resolveAgentMode("plan");
		expect(mode.ok).toBe(true); if (!mode.ok) return;
		const root = mkdtempSync(join(tmpdir(), "runledger-plan-mode-"));
		const home = join(root, "home"); mkdirSync(home);
		const target = join(root, "source.txt"); writeFileSync(target, "unchanged\n");
		const layout = buildRunledgerLayout(home, "posix");
		const db = openSessionDatabase(layout.database); installSessionStoreSchema(db);
		const store = new SessionStore(db); const ownerStore = new OwnerStore(db);
		const sessionId = createRuntimeId("session", "plan-mode-production");
		store.createSession({ sessionId, workspaceId: createRuntimeId("workspace", "plan-mode"), repositoryId: createRuntimeId("repository", "plan-mode"), settingsDigest: "d".repeat(64), harnessProfile: mode.ref });
		const models = builtinModels({ credentials: AuthStorage.create(layout) }); await models.refresh({ allowNetwork: false });
		const options = { sessionId, store, ownerStore, domain: { cwd: root, layout, models, settings: { autoTitle: false }, securitySources: [{ source: "cli" as const, read: async () => ({ status: "available" as const, text: JSON.stringify({ profile: "danger-full-access", approvalPolicy: "never" }) }) }] } };
		let embedded: Awaited<ReturnType<typeof createEmbeddedSessionRuntime>> | undefined;
		let client: SessionInteractiveController | undefined;
		try {
			embedded = await createEmbeddedSessionRuntime(options);
			client = new SessionInteractiveController(embedded.handle, await fetchDomainSnapshot(embedded));
			await claimDriver(embedded, client);
			const domain = (embedded.runtime as unknown as { domain: SessionDomainPort }).domain;
			const controller = domain.controller as typeof domain.controller & { tools: readonly AgentTool[]; executionEnv: ExecutionEnv; policy: ToolAuthorizationPolicy };
			expect(controller.tools.map((tool) => tool.name)).toEqual(["read", "glob", "ls", "plan_read", "plan_write"]);
			const planWriter = controller.tools.find((tool) => tool.name === "plan_write")!;
			const authorize = (tool: AgentTool | undefined) => controller.policy.authorize({ assistantMessage: contractAssistantMessage(), toolCall: { type: "toolCall", id: "policy-test", name: tool?.name ?? "unknown", arguments: {} }, args: {}, tool, context: { systemPrompt: "", messages: [], tools: [...controller.tools] } });
			expect(await authorize(planWriter)).toMatchObject({ decision: "allow" });
			expect(await authorize({ ...planWriter })).toMatchObject({ decision: "deny" });
			expect(await authorize({ ...planWriter, name: "read", capabilityClaims: [] })).toMatchObject({ decision: "deny" });
			expect(await authorize(undefined)).toMatchObject({ decision: "deny" });
			expect(embedded.handle.supports("session.process.start")).toBe(false);
			expect(embedded.handle.supports("extension.inspect")).toBe(false);
			await expect(controller.executionEnv.fs.writeFile(target, "changed")).rejects.toThrow("plan_mode_write_denied");
			await expect(controller.executionEnv.shell.exec("touch forbidden")).rejects.toThrow("plan_mode_process_denied");
			const inspected = await client.querySessionDomain("plan.inspect", {}, { correlationId: "inspect", effectId: "inspect" });
			expect(inspected.ok).toBe(true); if (!inspected.ok || !isValidPlanModeState(inspected.value.state)) throw new Error("invalid plan state");
			expect(inspected.value.state.status).toBe("active");
			const revision = inspected.value.state.revision;
			const written = await client.commandSessionDomain("plan.write", { expectedRevision: revision, expectedPlanRevision: 0, content: "# Implement feature\n\n1. Update code\n2. Run tests" }, { correlationId: "write", effectId: "write", expectedRevision: revision });
			expect(written.ok).toBe(true); if (!written.ok || !isValidPlanModeState(written.value.state)) throw new Error("plan write failed");
			const state = written.value.state;
			const replayedWrite = await client.commandSessionDomain("plan.write", { expectedRevision: revision, expectedPlanRevision: 0, content: "# Implement feature\n\n1. Update code\n2. Run tests" }, { correlationId: "write", effectId: "write", expectedRevision: revision });
			expect(replayedWrite).toEqual(written);
			const stale = await client.commandSessionDomain("plan.write", { expectedRevision: revision, expectedPlanRevision: 0, content: "stale" }, { correlationId: "stale", effectId: "stale", expectedRevision: revision });
			expect(stale).toMatchObject({ ok: false, code: "domain_revision_conflict" });
			const requested = await client.commandSessionDomain("plan.request_approval", { expectedRevision: state.revision, expectedPlanRevision: state.plan!.revision, expectedPlanDigest: state.plan!.digest }, { correlationId: "request", effectId: "request", expectedRevision: state.revision });
			expect(requested.ok).toBe(true); if (!requested.ok || !isValidPlanModeState(requested.value.state)) throw new Error("plan request failed");
			const pending = requested.value.state;
			const invalidApproval = await client.commandSessionDomain("plan.resolve_approval", { expectedRevision: pending.revision, expectedPlanRevision: 0, expectedPlanDigest: pending.plan!.digest, approvalId: pending.approval!.approvalId, decision: "approved" }, { correlationId: "invalid-approve", effectId: "invalid-approve", expectedRevision: pending.revision });
			expect(invalidApproval).toMatchObject({ ok: false, code: "plan_approval_binding_mismatch" });
			const approved = await client.commandSessionDomain("plan.resolve_approval", { expectedRevision: pending.revision, expectedPlanRevision: pending.plan!.revision, expectedPlanDigest: pending.plan!.digest, approvalId: pending.approval!.approvalId, decision: "approved" }, { correlationId: "approve", effectId: "approve", expectedRevision: pending.revision });
			expect(approved.ok).toBe(true);
			await expect(controller.executionEnv.fs.writeFile(target, "approved write")).rejects.toThrow("plan_mode_write_denied");
			expect(readFileSync(target, "utf8")).toBe("unchanged\n");
			client.dispose(); client = undefined;
			await embedded.handle.close(); await pauseIfLastAttachment(embedded);
			embedded = await createEmbeddedSessionRuntime(options);
			client = new SessionInteractiveController(embedded.handle, await fetchDomainSnapshot(embedded));
			const restored = await client.querySessionDomain("plan.inspect", {}, { correlationId: "restored", effectId: "restored" });
			expect(restored).toMatchObject({ ok: true, value: { content: "# Implement feature\n\n1. Update code\n2. Run tests", state: { status: "exit_pending", plan: { digest: state.plan!.digest }, approval: { status: "approved" } } } });
			await claimDriver(embedded, client);
			if (!restored.ok || !isValidPlanModeState(restored.value.state)) throw new Error("invalid restored state");
			const finished = await client.commandSessionDomain("plan.settle_exit", { expectedRevision: restored.value.state.revision }, { correlationId: "finish", effectId: "finish", expectedRevision: restored.value.state.revision });
			expect(finished).toMatchObject({ ok: true, value: { state: { status: "inactive" } } });
			const restoredDomain = (embedded.runtime as unknown as { domain: SessionDomainPort }).domain;
			await expect((restoredDomain.controller as typeof controller).executionEnv.shell.exec("touch forbidden")).rejects.toThrow("plan_mode_process_denied");
		} finally {
			client?.dispose(); await embedded?.handle.close().catch(() => undefined); await embedded?.runtime?.shutdownAfterLastAttachment("paused"); db.close(); rmSync(root, { recursive: true, force: true });
		}
	});
});
