// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/aiand.json" with { type: "json" };
import type { Model } from "../types.ts";

export const AIAND_MODELS = values as {
	"deepseek-ai/deepseek-v4-flash": Model<"openai-completions"> & {
		id: "deepseek-ai/deepseek-v4-flash";
		provider: "aiand";
	};
	"deepseek-ai/deepseek-v4-pro": Model<"openai-completions"> & {
		id: "deepseek-ai/deepseek-v4-pro";
		provider: "aiand";
	};
	"google/gemma-4-31b-it": Model<"openai-completions"> & {
		id: "google/gemma-4-31b-it";
		provider: "aiand";
	};
	"moonshotai/kimi-k2.7-code": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.7-code";
		provider: "aiand";
	};
	"moonshotai/kimi-k3": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k3";
		provider: "aiand";
	};
	"openai/gpt-oss-120b": Model<"openai-completions"> & {
		id: "openai/gpt-oss-120b";
		provider: "aiand";
	};
	"qwen/qwen3.6-27b": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-27b";
		provider: "aiand";
	};
	"zai-org/glm-5.2": Model<"openai-completions"> & {
		id: "zai-org/glm-5.2";
		provider: "aiand";
	};
};
