// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/aimlapi.json" with { type: "json" };
import type { Model } from "../types.ts";

export const AIMLAPI_MODELS = values as {
	"Qwen/Qwen2.5-7B-Instruct-Turbo": Model<"openai-completions"> & {
		id: "Qwen/Qwen2.5-7B-Instruct-Turbo";
		provider: "aimlapi";
	};
	"act_two": Model<"openai-completions"> & {
		id: "act_two";
		provider: "aimlapi";
	};
	"alibaba/qwen-max": Model<"openai-completions"> & {
		id: "alibaba/qwen-max";
		provider: "aimlapi";
	};
	"alibaba/qwen-plus": Model<"openai-completions"> & {
		id: "alibaba/qwen-plus";
		provider: "aimlapi";
	};
	"alibaba/qwen-turbo": Model<"openai-completions"> & {
		id: "alibaba/qwen-turbo";
		provider: "aimlapi";
	};
	"alibaba/qwen3-235b-a22b-thinking-2507": Model<"openai-completions"> & {
		id: "alibaba/qwen3-235b-a22b-thinking-2507";
		provider: "aimlapi";
	};
	"alibaba/qwen3-32b": Model<"openai-completions"> & {
		id: "alibaba/qwen3-32b";
		provider: "aimlapi";
	};
	"alibaba/qwen3-coder-480b-a35b-instruct": Model<"openai-completions"> & {
		id: "alibaba/qwen3-coder-480b-a35b-instruct";
		provider: "aimlapi";
	};
	"alibaba/qwen3-max-instruct": Model<"openai-completions"> & {
		id: "alibaba/qwen3-max-instruct";
		provider: "aimlapi";
	};
	"alibaba/qwen3-next-80b-a3b-instruct": Model<"openai-completions"> & {
		id: "alibaba/qwen3-next-80b-a3b-instruct";
		provider: "aimlapi";
	};
	"alibaba/qwen3-next-80b-a3b-thinking": Model<"openai-completions"> & {
		id: "alibaba/qwen3-next-80b-a3b-thinking";
		provider: "aimlapi";
	};
	"alibaba/wan2.2-14b-animate-move": Model<"openai-completions"> & {
		id: "alibaba/wan2.2-14b-animate-move";
		provider: "aimlapi";
	};
	"alibaba/wan2.2-14b-animate-replace": Model<"openai-completions"> & {
		id: "alibaba/wan2.2-14b-animate-replace";
		provider: "aimlapi";
	};
	"alibaba/wan2.2-vace-fun-a14b-depth": Model<"openai-completions"> & {
		id: "alibaba/wan2.2-vace-fun-a14b-depth";
		provider: "aimlapi";
	};
	"alibaba/wan2.2-vace-fun-a14b-inpainting": Model<"openai-completions"> & {
		id: "alibaba/wan2.2-vace-fun-a14b-inpainting";
		provider: "aimlapi";
	};
	"alibaba/wan2.2-vace-fun-a14b-outpainting": Model<"openai-completions"> & {
		id: "alibaba/wan2.2-vace-fun-a14b-outpainting";
		provider: "aimlapi";
	};
	"alibaba/wan2.2-vace-fun-a14b-pose": Model<"openai-completions"> & {
		id: "alibaba/wan2.2-vace-fun-a14b-pose";
		provider: "aimlapi";
	};
	"alibaba/wan2.2-vace-fun-a14b-reframe": Model<"openai-completions"> & {
		id: "alibaba/wan2.2-vace-fun-a14b-reframe";
		provider: "aimlapi";
	};
	"aura-2-amalthea-en": Model<"openai-completions"> & {
		id: "aura-2-amalthea-en";
		provider: "aimlapi";
	};
	"aura-2-andromeda-en": Model<"openai-completions"> & {
		id: "aura-2-andromeda-en";
		provider: "aimlapi";
	};
	"aura-2-apollo-en": Model<"openai-completions"> & {
		id: "aura-2-apollo-en";
		provider: "aimlapi";
	};
	"aura-2-arcas-en": Model<"openai-completions"> & {
		id: "aura-2-arcas-en";
		provider: "aimlapi";
	};
	"aura-2-aries-en": Model<"openai-completions"> & {
		id: "aura-2-aries-en";
		provider: "aimlapi";
	};
	"aura-2-asteria-en": Model<"openai-completions"> & {
		id: "aura-2-asteria-en";
		provider: "aimlapi";
	};
	"aura-2-athena-en": Model<"openai-completions"> & {
		id: "aura-2-athena-en";
		provider: "aimlapi";
	};
	"aura-2-atlas-en": Model<"openai-completions"> & {
		id: "aura-2-atlas-en";
		provider: "aimlapi";
	};
	"aura-2-aurora-en": Model<"openai-completions"> & {
		id: "aura-2-aurora-en";
		provider: "aimlapi";
	};
	"aura-2-callista-en": Model<"openai-completions"> & {
		id: "aura-2-callista-en";
		provider: "aimlapi";
	};
	"aura-2-celeste-es": Model<"openai-completions"> & {
		id: "aura-2-celeste-es";
		provider: "aimlapi";
	};
	"aura-2-cora-en": Model<"openai-completions"> & {
		id: "aura-2-cora-en";
		provider: "aimlapi";
	};
	"aura-2-cordelia-en": Model<"openai-completions"> & {
		id: "aura-2-cordelia-en";
		provider: "aimlapi";
	};
	"aura-2-delia-en": Model<"openai-completions"> & {
		id: "aura-2-delia-en";
		provider: "aimlapi";
	};
	"aura-2-draco-en": Model<"openai-completions"> & {
		id: "aura-2-draco-en";
		provider: "aimlapi";
	};
	"aura-2-electra-en": Model<"openai-completions"> & {
		id: "aura-2-electra-en";
		provider: "aimlapi";
	};
	"aura-2-estrella-es": Model<"openai-completions"> & {
		id: "aura-2-estrella-es";
		provider: "aimlapi";
	};
	"aura-2-harmonia-en": Model<"openai-completions"> & {
		id: "aura-2-harmonia-en";
		provider: "aimlapi";
	};
	"aura-2-helena-en": Model<"openai-completions"> & {
		id: "aura-2-helena-en";
		provider: "aimlapi";
	};
	"aura-2-hera-en": Model<"openai-completions"> & {
		id: "aura-2-hera-en";
		provider: "aimlapi";
	};
	"aura-2-hermes-en": Model<"openai-completions"> & {
		id: "aura-2-hermes-en";
		provider: "aimlapi";
	};
	"aura-2-hyperion-en": Model<"openai-completions"> & {
		id: "aura-2-hyperion-en";
		provider: "aimlapi";
	};
	"aura-2-iris-en": Model<"openai-completions"> & {
		id: "aura-2-iris-en";
		provider: "aimlapi";
	};
	"aura-2-janus-en": Model<"openai-completions"> & {
		id: "aura-2-janus-en";
		provider: "aimlapi";
	};
	"aura-2-juno-en": Model<"openai-completions"> & {
		id: "aura-2-juno-en";
		provider: "aimlapi";
	};
	"aura-2-jupiter-en": Model<"openai-completions"> & {
		id: "aura-2-jupiter-en";
		provider: "aimlapi";
	};
	"aura-2-luna-en": Model<"openai-completions"> & {
		id: "aura-2-luna-en";
		provider: "aimlapi";
	};
	"aura-2-mars-en": Model<"openai-completions"> & {
		id: "aura-2-mars-en";
		provider: "aimlapi";
	};
	"aura-2-minerva-en": Model<"openai-completions"> & {
		id: "aura-2-minerva-en";
		provider: "aimlapi";
	};
	"aura-2-neptune-en": Model<"openai-completions"> & {
		id: "aura-2-neptune-en";
		provider: "aimlapi";
	};
	"aura-2-nestor-es": Model<"openai-completions"> & {
		id: "aura-2-nestor-es";
		provider: "aimlapi";
	};
	"aura-2-odysseus-en": Model<"openai-completions"> & {
		id: "aura-2-odysseus-en";
		provider: "aimlapi";
	};
	"aura-2-ophelia-en": Model<"openai-completions"> & {
		id: "aura-2-ophelia-en";
		provider: "aimlapi";
	};
	"aura-2-orion-en": Model<"openai-completions"> & {
		id: "aura-2-orion-en";
		provider: "aimlapi";
	};
	"aura-2-orpheus-en": Model<"openai-completions"> & {
		id: "aura-2-orpheus-en";
		provider: "aimlapi";
	};
	"aura-2-pandora-en": Model<"openai-completions"> & {
		id: "aura-2-pandora-en";
		provider: "aimlapi";
	};
	"aura-2-phoebe-en": Model<"openai-completions"> & {
		id: "aura-2-phoebe-en";
		provider: "aimlapi";
	};
	"aura-2-pluto-en": Model<"openai-completions"> & {
		id: "aura-2-pluto-en";
		provider: "aimlapi";
	};
	"aura-2-saturn-en": Model<"openai-completions"> & {
		id: "aura-2-saturn-en";
		provider: "aimlapi";
	};
	"aura-2-selene-en": Model<"openai-completions"> & {
		id: "aura-2-selene-en";
		provider: "aimlapi";
	};
	"aura-2-thalia-en": Model<"openai-completions"> & {
		id: "aura-2-thalia-en";
		provider: "aimlapi";
	};
	"aura-2-theia-en": Model<"openai-completions"> & {
		id: "aura-2-theia-en";
		provider: "aimlapi";
	};
	"aura-2-vesta-en": Model<"openai-completions"> & {
		id: "aura-2-vesta-en";
		provider: "aimlapi";
	};
	"aura-2-zeus-en": Model<"openai-completions"> & {
		id: "aura-2-zeus-en";
		provider: "aimlapi";
	};
	"aura-angus-en": Model<"openai-completions"> & {
		id: "aura-angus-en";
		provider: "aimlapi";
	};
	"aura-arcas-en": Model<"openai-completions"> & {
		id: "aura-arcas-en";
		provider: "aimlapi";
	};
	"aura-asteria-en": Model<"openai-completions"> & {
		id: "aura-asteria-en";
		provider: "aimlapi";
	};
	"aura-athena-en": Model<"openai-completions"> & {
		id: "aura-athena-en";
		provider: "aimlapi";
	};
	"aura-helios-en": Model<"openai-completions"> & {
		id: "aura-helios-en";
		provider: "aimlapi";
	};
	"aura-hera-en": Model<"openai-completions"> & {
		id: "aura-hera-en";
		provider: "aimlapi";
	};
	"aura-luna-en": Model<"openai-completions"> & {
		id: "aura-luna-en";
		provider: "aimlapi";
	};
	"aura-orion-en": Model<"openai-completions"> & {
		id: "aura-orion-en";
		provider: "aimlapi";
	};
	"aura-orpheus-en": Model<"openai-completions"> & {
		id: "aura-orpheus-en";
		provider: "aimlapi";
	};
	"aura-perseus-en": Model<"openai-completions"> & {
		id: "aura-perseus-en";
		provider: "aimlapi";
	};
	"aura-stella-en": Model<"openai-completions"> & {
		id: "aura-stella-en";
		provider: "aimlapi";
	};
	"aura-zeus-en": Model<"openai-completions"> & {
		id: "aura-zeus-en";
		provider: "aimlapi";
	};
	"baidu/ernie-4-5-0-3b": Model<"openai-completions"> & {
		id: "baidu/ernie-4-5-0-3b";
		provider: "aimlapi";
	};
	"baidu/ernie-4-5-21b-a3b": Model<"openai-completions"> & {
		id: "baidu/ernie-4-5-21b-a3b";
		provider: "aimlapi";
	};
	"baidu/ernie-4-5-300b-a47b": Model<"openai-completions"> & {
		id: "baidu/ernie-4-5-300b-a47b";
		provider: "aimlapi";
	};
	"baidu/ernie-4-5-300b-a47b-paddle": Model<"openai-completions"> & {
		id: "baidu/ernie-4-5-300b-a47b-paddle";
		provider: "aimlapi";
	};
	"baidu/ernie-4-5-8k-preview": Model<"openai-completions"> & {
		id: "baidu/ernie-4-5-8k-preview";
		provider: "aimlapi";
	};
	"baidu/ernie-4-5-turbo-128k": Model<"openai-completions"> & {
		id: "baidu/ernie-4-5-turbo-128k";
		provider: "aimlapi";
	};
	"baidu/ernie-4-5-turbo-vl-32k": Model<"openai-completions"> & {
		id: "baidu/ernie-4-5-turbo-vl-32k";
		provider: "aimlapi";
	};
	"baidu/ernie-4-5-vl-28b-a3b": Model<"openai-completions"> & {
		id: "baidu/ernie-4-5-vl-28b-a3b";
		provider: "aimlapi";
	};
	"baidu/ernie-4-5-vl-424b-a47b": Model<"openai-completions"> & {
		id: "baidu/ernie-4-5-vl-424b-a47b";
		provider: "aimlapi";
	};
	"baidu/ernie-5-0-thinking-latest": Model<"openai-completions"> & {
		id: "baidu/ernie-5-0-thinking-latest";
		provider: "aimlapi";
	};
	"baidu/ernie-5-0-thinking-preview": Model<"openai-completions"> & {
		id: "baidu/ernie-5-0-thinking-preview";
		provider: "aimlapi";
	};
	"baidu/ernie-x1-1-preview": Model<"openai-completions"> & {
		id: "baidu/ernie-x1-1-preview";
		provider: "aimlapi";
	};
	"baidu/ernie-x1-turbo-32k": Model<"openai-completions"> & {
		id: "baidu/ernie-x1-turbo-32k";
		provider: "aimlapi";
	};
	"bytedance/dreamina-creative-upscale": Model<"openai-completions"> & {
		id: "bytedance/dreamina-creative-upscale";
		provider: "aimlapi";
	};
	"bytedance/dreamina-seedance-2-0": Model<"openai-completions"> & {
		id: "bytedance/dreamina-seedance-2-0";
		provider: "aimlapi";
	};
	"bytedance/dreamina-seedance-2-0-fast": Model<"openai-completions"> & {
		id: "bytedance/dreamina-seedance-2-0-fast";
		provider: "aimlapi";
	};
	"bytedance/omnihuman": Model<"openai-completions"> & {
		id: "bytedance/omnihuman";
		provider: "aimlapi";
	};
	"bytedance/omnihuman/v1.5": Model<"openai-completions"> & {
		id: "bytedance/omnihuman/v1.5";
		provider: "aimlapi";
	};
	"bytedance/seed-1-8": Model<"openai-completions"> & {
		id: "bytedance/seed-1-8";
		provider: "aimlapi";
	};
	"bytedance/seed-2-0-code-preview": Model<"openai-completions"> & {
		id: "bytedance/seed-2-0-code-preview";
		provider: "aimlapi";
	};
	"bytedance/seed-2-0-lite": Model<"openai-completions"> & {
		id: "bytedance/seed-2-0-lite";
		provider: "aimlapi";
	};
	"bytedance/seed-2-0-mini": Model<"openai-completions"> & {
		id: "bytedance/seed-2-0-mini";
		provider: "aimlapi";
	};
	"bytedance/seed-2-0-pro": Model<"openai-completions"> & {
		id: "bytedance/seed-2-0-pro";
		provider: "aimlapi";
	};
	"bytedance/seedance-1-0-pro": Model<"openai-completions"> & {
		id: "bytedance/seedance-1-0-pro";
		provider: "aimlapi";
	};
	"bytedance/seedance-1-0-pro-fast": Model<"openai-completions"> & {
		id: "bytedance/seedance-1-0-pro-fast";
		provider: "aimlapi";
	};
	"bytedance/seedance-1-5-pro": Model<"openai-completions"> & {
		id: "bytedance/seedance-1-5-pro";
		provider: "aimlapi";
	};
	"bytedance/seedance-2-0": Model<"openai-completions"> & {
		id: "bytedance/seedance-2-0";
		provider: "aimlapi";
	};
	"bytedance/seedance-2-0-fast": Model<"openai-completions"> & {
		id: "bytedance/seedance-2-0-fast";
		provider: "aimlapi";
	};
	"bytedance/seedream-4-5": Model<"openai-completions"> & {
		id: "bytedance/seedream-4-5";
		provider: "aimlapi";
	};
	"bytedance/seedream-5-0-lite": Model<"openai-completions"> & {
		id: "bytedance/seedream-5-0-lite";
		provider: "aimlapi";
	};
	"bytedance/seedream/v4/edit": Model<"openai-completions"> & {
		id: "bytedance/seedream/v4/edit";
		provider: "aimlapi";
	};
	"claude-haiku-4-5-20251001": Model<"openai-completions"> & {
		id: "claude-haiku-4-5-20251001";
		provider: "aimlapi";
	};
	"claude-opus-4-1-20250805": Model<"openai-completions"> & {
		id: "claude-opus-4-1-20250805";
		provider: "aimlapi";
	};
	"claude-opus-4-20250514": Model<"openai-completions"> & {
		id: "claude-opus-4-20250514";
		provider: "aimlapi";
	};
	"claude-opus-4-5-20251101": Model<"openai-completions"> & {
		id: "claude-opus-4-5-20251101";
		provider: "aimlapi";
	};
	"claude-opus-4-6": Model<"openai-completions"> & {
		id: "claude-opus-4-6";
		provider: "aimlapi";
	};
	"claude-opus-4-7": Model<"openai-completions"> & {
		id: "claude-opus-4-7";
		provider: "aimlapi";
	};
	"claude-opus-4-8": Model<"openai-completions"> & {
		id: "claude-opus-4-8";
		provider: "aimlapi";
	};
	"claude-sonnet-4-20250514": Model<"openai-completions"> & {
		id: "claude-sonnet-4-20250514";
		provider: "aimlapi";
	};
	"claude-sonnet-4-5-20250929": Model<"openai-completions"> & {
		id: "claude-sonnet-4-5-20250929";
		provider: "aimlapi";
	};
	"claude-sonnet-4-6": Model<"openai-completions"> & {
		id: "claude-sonnet-4-6";
		provider: "aimlapi";
	};
	"command-a": Model<"openai-completions"> & {
		id: "command-a";
		provider: "aimlapi";
	};
	"custom:happyhorse-1.0": Model<"openai-completions"> & {
		id: "custom:happyhorse-1.0";
		provider: "aimlapi";
	};
	"deepseek-chat": Model<"openai-completions"> & {
		id: "deepseek-chat";
		provider: "aimlapi";
	};
	"deepseek-non-reasoner-v3.1-terminus": Model<"openai-completions"> & {
		id: "deepseek-non-reasoner-v3.1-terminus";
		provider: "aimlapi";
	};
	"deepseek-non-thinking-v3.2-exp": Model<"openai-completions"> & {
		id: "deepseek-non-thinking-v3.2-exp";
		provider: "aimlapi";
	};
	"deepseek-reasoner": Model<"openai-completions"> & {
		id: "deepseek-reasoner";
		provider: "aimlapi";
	};
	"deepseek-v4-flash": Model<"openai-completions"> & {
		id: "deepseek-v4-flash";
		provider: "aimlapi";
	};
	"deepseek-v4-pro": Model<"openai-completions"> & {
		id: "deepseek-v4-pro";
		provider: "aimlapi";
	};
	"deepseek/deepseek-chat-v3-0324": Model<"openai-completions"> & {
		id: "deepseek/deepseek-chat-v3-0324";
		provider: "aimlapi";
	};
	"deepseek/deepseek-chat-v3.1": Model<"openai-completions"> & {
		id: "deepseek/deepseek-chat-v3.1";
		provider: "aimlapi";
	};
	"deepseek/deepseek-r1": Model<"openai-completions"> & {
		id: "deepseek/deepseek-r1";
		provider: "aimlapi";
	};
	"elevenlabs/eleven_multilingual_v2": Model<"openai-completions"> & {
		id: "elevenlabs/eleven_multilingual_v2";
		provider: "aimlapi";
	};
	"elevenlabs/eleven_music": Model<"openai-completions"> & {
		id: "elevenlabs/eleven_music";
		provider: "aimlapi";
	};
	"elevenlabs/eleven_turbo_v2_5": Model<"openai-completions"> & {
		id: "elevenlabs/eleven_turbo_v2_5";
		provider: "aimlapi";
	};
	"elevenlabs/v3_alpha": Model<"openai-completions"> & {
		id: "elevenlabs/v3_alpha";
		provider: "aimlapi";
	};
	"gc-document-ai": Model<"openai-completions"> & {
		id: "gc-document-ai";
		provider: "aimlapi";
	};
	"gemini-2.5-flash": Model<"openai-completions"> & {
		id: "gemini-2.5-flash";
		provider: "aimlapi";
	};
	"gemini-2.5-flash-lite": Model<"openai-completions"> & {
		id: "gemini-2.5-flash-lite";
		provider: "aimlapi";
	};
	"gemini-2.5-flash-lite-preview-09-2025": Model<"openai-completions"> & {
		id: "gemini-2.5-flash-lite-preview-09-2025";
		provider: "aimlapi";
	};
	"gemini-2.5-pro": Model<"openai-completions"> & {
		id: "gemini-2.5-pro";
		provider: "aimlapi";
	};
	"gemini-3-flash-preview": Model<"openai-completions"> & {
		id: "gemini-3-flash-preview";
		provider: "aimlapi";
	};
	"gemini-3.1-flash-lite": Model<"openai-completions"> & {
		id: "gemini-3.1-flash-lite";
		provider: "aimlapi";
	};
	"gemini-3.1-flash-lite-preview": Model<"openai-completions"> & {
		id: "gemini-3.1-flash-lite-preview";
		provider: "aimlapi";
	};
	"gemini-3.1-pro-preview": Model<"openai-completions"> & {
		id: "gemini-3.1-pro-preview";
		provider: "aimlapi";
	};
	"gemini-3.5-flash": Model<"openai-completions"> & {
		id: "gemini-3.5-flash";
		provider: "aimlapi";
	};
	"gemma-3-12b-it": Model<"openai-completions"> & {
		id: "gemma-3-12b-it";
		provider: "aimlapi";
	};
	"gemma-3-27b-it": Model<"openai-completions"> & {
		id: "gemma-3-27b-it";
		provider: "aimlapi";
	};
	"gemma-3-4b-it": Model<"openai-completions"> & {
		id: "gemma-3-4b-it";
		provider: "aimlapi";
	};
	"gemma-3n-e4b-it": Model<"openai-completions"> & {
		id: "gemma-3n-e4b-it";
		provider: "aimlapi";
	};
	"gemma-4-31b-it": Model<"openai-completions"> & {
		id: "gemma-4-31b-it";
		provider: "aimlapi";
	};
	"gen3a_turbo": Model<"openai-completions"> & {
		id: "gen3a_turbo";
		provider: "aimlapi";
	};
	"gen4_aleph": Model<"openai-completions"> & {
		id: "gen4_aleph";
		provider: "aimlapi";
	};
	"gen4_turbo": Model<"openai-completions"> & {
		id: "gen4_turbo";
		provider: "aimlapi";
	};
	"glm-4.5": Model<"openai-completions"> & {
		id: "glm-4.5";
		provider: "aimlapi";
	};
	"glm-4.5-air": Model<"openai-completions"> & {
		id: "glm-4.5-air";
		provider: "aimlapi";
	};
	"glm-4.6": Model<"openai-completions"> & {
		id: "glm-4.6";
		provider: "aimlapi";
	};
	"glm-4.7": Model<"openai-completions"> & {
		id: "glm-4.7";
		provider: "aimlapi";
	};
	"glm-5": Model<"openai-completions"> & {
		id: "glm-5";
		provider: "aimlapi";
	};
	"glm-5.1": Model<"openai-completions"> & {
		id: "glm-5.1";
		provider: "aimlapi";
	};
	"glm-ocr": Model<"openai-completions"> & {
		id: "glm-ocr";
		provider: "aimlapi";
	};
	"gpt-3.5-turbo": Model<"openai-completions"> & {
		id: "gpt-3.5-turbo";
		provider: "aimlapi";
	};
	"gpt-3.5-turbo-0125": Model<"openai-completions"> & {
		id: "gpt-3.5-turbo-0125";
		provider: "aimlapi";
	};
	"gpt-3.5-turbo-0613": Model<"openai-completions"> & {
		id: "gpt-3.5-turbo-0613";
		provider: "aimlapi";
	};
	"gpt-3.5-turbo-1106": Model<"openai-completions"> & {
		id: "gpt-3.5-turbo-1106";
		provider: "aimlapi";
	};
	"gpt-3.5-turbo-16k": Model<"openai-completions"> & {
		id: "gpt-3.5-turbo-16k";
		provider: "aimlapi";
	};
	"gpt-3.5-turbo-instruct": Model<"openai-completions"> & {
		id: "gpt-3.5-turbo-instruct";
		provider: "aimlapi";
	};
	"gpt-4": Model<"openai-completions"> & {
		id: "gpt-4";
		provider: "aimlapi";
	};
	"gpt-4-0314": Model<"openai-completions"> & {
		id: "gpt-4-0314";
		provider: "aimlapi";
	};
	"gpt-4-1106-vision-preview": Model<"openai-completions"> & {
		id: "gpt-4-1106-vision-preview";
		provider: "aimlapi";
	};
	"gpt-4-turbo": Model<"openai-completions"> & {
		id: "gpt-4-turbo";
		provider: "aimlapi";
	};
	"gpt-4-turbo-2024-04-09": Model<"openai-completions"> & {
		id: "gpt-4-turbo-2024-04-09";
		provider: "aimlapi";
	};
	"gpt-4-turbo-preview": Model<"openai-completions"> & {
		id: "gpt-4-turbo-preview";
		provider: "aimlapi";
	};
	"gpt-4.1": Model<"openai-completions"> & {
		id: "gpt-4.1";
		provider: "aimlapi";
	};
	"gpt-4.1-2025-04-14": Model<"openai-completions"> & {
		id: "gpt-4.1-2025-04-14";
		provider: "aimlapi";
	};
	"gpt-4.1-mini": Model<"openai-completions"> & {
		id: "gpt-4.1-mini";
		provider: "aimlapi";
	};
	"gpt-4.1-mini-2025-04-14": Model<"openai-completions"> & {
		id: "gpt-4.1-mini-2025-04-14";
		provider: "aimlapi";
	};
	"gpt-4.1-nano": Model<"openai-completions"> & {
		id: "gpt-4.1-nano";
		provider: "aimlapi";
	};
	"gpt-4.1-nano-2025-04-14": Model<"openai-completions"> & {
		id: "gpt-4.1-nano-2025-04-14";
		provider: "aimlapi";
	};
	"gpt-4o": Model<"openai-completions"> & {
		id: "gpt-4o";
		provider: "aimlapi";
	};
	"gpt-4o-2024-05-13": Model<"openai-completions"> & {
		id: "gpt-4o-2024-05-13";
		provider: "aimlapi";
	};
	"gpt-4o-2024-08-06": Model<"openai-completions"> & {
		id: "gpt-4o-2024-08-06";
		provider: "aimlapi";
	};
	"gpt-4o-2024-11-20": Model<"openai-completions"> & {
		id: "gpt-4o-2024-11-20";
		provider: "aimlapi";
	};
	"gpt-4o-mini": Model<"openai-completions"> & {
		id: "gpt-4o-mini";
		provider: "aimlapi";
	};
	"gpt-4o-mini-2024-07-18": Model<"openai-completions"> & {
		id: "gpt-4o-mini-2024-07-18";
		provider: "aimlapi";
	};
	"gpt-4o-mini-search-preview": Model<"openai-completions"> & {
		id: "gpt-4o-mini-search-preview";
		provider: "aimlapi";
	};
	"gpt-4o-mini-transcribe": Model<"openai-completions"> & {
		id: "gpt-4o-mini-transcribe";
		provider: "aimlapi";
	};
	"gpt-4o-search-preview": Model<"openai-completions"> & {
		id: "gpt-4o-search-preview";
		provider: "aimlapi";
	};
	"gpt-4o-transcribe": Model<"openai-completions"> & {
		id: "gpt-4o-transcribe";
		provider: "aimlapi";
	};
	"gpt-5": Model<"openai-completions"> & {
		id: "gpt-5";
		provider: "aimlapi";
	};
	"gpt-5-2025-08-07": Model<"openai-completions"> & {
		id: "gpt-5-2025-08-07";
		provider: "aimlapi";
	};
	"gpt-5-chat": Model<"openai-completions"> & {
		id: "gpt-5-chat";
		provider: "aimlapi";
	};
	"gpt-5-chat-latest": Model<"openai-completions"> & {
		id: "gpt-5-chat-latest";
		provider: "aimlapi";
	};
	"gpt-5-mini": Model<"openai-completions"> & {
		id: "gpt-5-mini";
		provider: "aimlapi";
	};
	"gpt-5-mini-2025-08-07": Model<"openai-completions"> & {
		id: "gpt-5-mini-2025-08-07";
		provider: "aimlapi";
	};
	"gpt-5-nano": Model<"openai-completions"> & {
		id: "gpt-5-nano";
		provider: "aimlapi";
	};
	"gpt-5-nano-2025-08-07": Model<"openai-completions"> & {
		id: "gpt-5-nano-2025-08-07";
		provider: "aimlapi";
	};
	"gpt-5-pro": Model<"openai-completions"> & {
		id: "gpt-5-pro";
		provider: "aimlapi";
	};
	"gpt-5.1-2025-11-13": Model<"openai-completions"> & {
		id: "gpt-5.1-2025-11-13";
		provider: "aimlapi";
	};
	"gpt-5.1-chat-latest": Model<"openai-completions"> & {
		id: "gpt-5.1-chat-latest";
		provider: "aimlapi";
	};
	"gpt-5.1-codex": Model<"openai-completions"> & {
		id: "gpt-5.1-codex";
		provider: "aimlapi";
	};
	"gpt-5.1-codex-mini": Model<"openai-completions"> & {
		id: "gpt-5.1-codex-mini";
		provider: "aimlapi";
	};
	"gpt-5.2-2025-12-11": Model<"openai-completions"> & {
		id: "gpt-5.2-2025-12-11";
		provider: "aimlapi";
	};
	"gpt-5.2-chat-latest": Model<"openai-completions"> & {
		id: "gpt-5.2-chat-latest";
		provider: "aimlapi";
	};
	"gpt-5.2-codex": Model<"openai-completions"> & {
		id: "gpt-5.2-codex";
		provider: "aimlapi";
	};
	"gpt-5.2-pro-2025-12-11": Model<"openai-completions"> & {
		id: "gpt-5.2-pro-2025-12-11";
		provider: "aimlapi";
	};
	"gpt-5.3-codex": Model<"openai-completions"> & {
		id: "gpt-5.3-codex";
		provider: "aimlapi";
	};
	"gpt-5.4-2026-03-05": Model<"openai-completions"> & {
		id: "gpt-5.4-2026-03-05";
		provider: "aimlapi";
	};
	"gpt-5.4-pro-2026-03-05": Model<"openai-completions"> & {
		id: "gpt-5.4-pro-2026-03-05";
		provider: "aimlapi";
	};
	"gpt-5.5-2026-04-23": Model<"openai-completions"> & {
		id: "gpt-5.5-2026-04-23";
		provider: "aimlapi";
	};
	"gpt-5.5-pro-2026-04-23": Model<"openai-completions"> & {
		id: "gpt-5.5-pro-2026-04-23";
		provider: "aimlapi";
	};
	"gpt-oss-120b": Model<"openai-completions"> & {
		id: "gpt-oss-120b";
		provider: "aimlapi";
	};
	"gpt-oss-20b": Model<"openai-completions"> & {
		id: "gpt-oss-20b";
		provider: "aimlapi";
	};
	"grok-4-1-fast-non-reasoning": Model<"openai-completions"> & {
		id: "grok-4-1-fast-non-reasoning";
		provider: "aimlapi";
	};
	"grok-4-1-fast-reasoning": Model<"openai-completions"> & {
		id: "grok-4-1-fast-reasoning";
		provider: "aimlapi";
	};
	"grok-4-20-0309-non-reasoning": Model<"openai-completions"> & {
		id: "grok-4-20-0309-non-reasoning";
		provider: "aimlapi";
	};
	"grok-4-20-0309-reasoning": Model<"openai-completions"> & {
		id: "grok-4-20-0309-reasoning";
		provider: "aimlapi";
	};
	"grok-4-fast-non-reasoning": Model<"openai-completions"> & {
		id: "grok-4-fast-non-reasoning";
		provider: "aimlapi";
	};
	"grok-4-fast-reasoning": Model<"openai-completions"> & {
		id: "grok-4-fast-reasoning";
		provider: "aimlapi";
	};
	"happyhorse-1.0-r2v": Model<"openai-completions"> & {
		id: "happyhorse-1.0-r2v";
		provider: "aimlapi";
	};
	"hermes-4-405b": Model<"openai-completions"> & {
		id: "hermes-4-405b";
		provider: "aimlapi";
	};
	"hunyuan-part": Model<"openai-completions"> & {
		id: "hunyuan-part";
		provider: "aimlapi";
	};
	"klingai/avatar-pro": Model<"openai-completions"> & {
		id: "klingai/avatar-pro";
		provider: "aimlapi";
	};
	"klingai/avatar-standard": Model<"openai-completions"> & {
		id: "klingai/avatar-standard";
		provider: "aimlapi";
	};
	"ltxv-2": Model<"openai-completions"> & {
		id: "ltxv-2";
		provider: "aimlapi";
	};
	"ltxv-2/fast": Model<"openai-completions"> & {
		id: "ltxv-2/fast";
		provider: "aimlapi";
	};
	"lyria2": Model<"openai-completions"> & {
		id: "lyria2";
		provider: "aimlapi";
	};
	"magnum-v4-72b": Model<"openai-completions"> & {
		id: "magnum-v4-72b";
		provider: "aimlapi";
	};
	"meta-llama/Llama-3.3-70B-Instruct-Turbo": Model<"openai-completions"> & {
		id: "meta-llama/Llama-3.3-70B-Instruct-Turbo";
		provider: "aimlapi";
	};
	"meta-llama/llama-3.3-70b-versatile": Model<"openai-completions"> & {
		id: "meta-llama/llama-3.3-70b-versatile";
		provider: "aimlapi";
	};
	"microsoft/mai-transcribe-1.5": Model<"openai-completions"> & {
		id: "microsoft/mai-transcribe-1.5";
		provider: "aimlapi";
	};
	"microsoft/mai-voice-2": Model<"openai-completions"> & {
		id: "microsoft/mai-voice-2";
		provider: "aimlapi";
	};
	"minimax-music": Model<"openai-completions"> & {
		id: "minimax-music";
		provider: "aimlapi";
	};
	"minimax/MiniMax-Text-01": Model<"openai-completions"> & {
		id: "minimax/MiniMax-Text-01";
		provider: "aimlapi";
	};
	"minimax/hailuo-02": Model<"openai-completions"> & {
		id: "minimax/hailuo-02";
		provider: "aimlapi";
	};
	"minimax/hailuo-2.3": Model<"openai-completions"> & {
		id: "minimax/hailuo-2.3";
		provider: "aimlapi";
	};
	"minimax/hailuo-2.3-fast": Model<"openai-completions"> & {
		id: "minimax/hailuo-2.3-fast";
		provider: "aimlapi";
	};
	"minimax/m1": Model<"openai-completions"> & {
		id: "minimax/m1";
		provider: "aimlapi";
	};
	"minimax/m2": Model<"openai-completions"> & {
		id: "minimax/m2";
		provider: "aimlapi";
	};
	"minimax/m2-1": Model<"openai-completions"> & {
		id: "minimax/m2-1";
		provider: "aimlapi";
	};
	"minimax/m2-1-highspeed": Model<"openai-completions"> & {
		id: "minimax/m2-1-highspeed";
		provider: "aimlapi";
	};
	"minimax/m2-5-20260218": Model<"openai-completions"> & {
		id: "minimax/m2-5-20260218";
		provider: "aimlapi";
	};
	"minimax/m2-5-highspeed-20260218": Model<"openai-completions"> & {
		id: "minimax/m2-5-highspeed-20260218";
		provider: "aimlapi";
	};
	"minimax/m2-7-20260402": Model<"openai-completions"> & {
		id: "minimax/m2-7-20260402";
		provider: "aimlapi";
	};
	"minimax/m2-7-highspeed": Model<"openai-completions"> & {
		id: "minimax/m2-7-highspeed";
		provider: "aimlapi";
	};
	"minimax/m2-her": Model<"openai-completions"> & {
		id: "minimax/m2-her";
		provider: "aimlapi";
	};
	"minimax/minimax-m3": Model<"openai-completions"> & {
		id: "minimax/minimax-m3";
		provider: "aimlapi";
	};
	"minimax/music-1.5": Model<"openai-completions"> & {
		id: "minimax/music-1.5";
		provider: "aimlapi";
	};
	"minimax/music-2.0": Model<"openai-completions"> & {
		id: "minimax/music-2.0";
		provider: "aimlapi";
	};
	"minimax/music-2.6": Model<"openai-completions"> & {
		id: "minimax/music-2.6";
		provider: "aimlapi";
	};
	"minimax/music-cover": Model<"openai-completions"> & {
		id: "minimax/music-cover";
		provider: "aimlapi";
	};
	"mistral-nemo": Model<"openai-completions"> & {
		id: "mistral-nemo";
		provider: "aimlapi";
	};
	"mistral-ocr-latest": Model<"openai-completions"> & {
		id: "mistral-ocr-latest";
		provider: "aimlapi";
	};
	"moonshot/kimi-k2-0905-preview": Model<"openai-completions"> & {
		id: "moonshot/kimi-k2-0905-preview";
		provider: "aimlapi";
	};
	"moonshot/kimi-k2-5": Model<"openai-completions"> & {
		id: "moonshot/kimi-k2-5";
		provider: "aimlapi";
	};
	"moonshot/kimi-k2-6": Model<"openai-completions"> & {
		id: "moonshot/kimi-k2-6";
		provider: "aimlapi";
	};
	"moonshot/kimi-k2-preview": Model<"openai-completions"> & {
		id: "moonshot/kimi-k2-preview";
		provider: "aimlapi";
	};
	"mythomax-l2-13b": Model<"openai-completions"> & {
		id: "mythomax-l2-13b";
		provider: "aimlapi";
	};
	"nano-banana": Model<"openai-completions"> & {
		id: "nano-banana";
		provider: "aimlapi";
	};
	"nano-banana-pro": Model<"openai-completions"> & {
		id: "nano-banana-pro";
		provider: "aimlapi";
	};
	"nano-banana-pro-edit": Model<"openai-completions"> & {
		id: "nano-banana-pro-edit";
		provider: "aimlapi";
	};
	"nemotron-3-nano-30b-a3b": Model<"openai-completions"> & {
		id: "nemotron-3-nano-30b-a3b";
		provider: "aimlapi";
	};
	"nemotron-3-nano-omni-30b-a3b-reasoning:free": Model<"openai-completions"> & {
		id: "nemotron-3-nano-omni-30b-a3b-reasoning:free";
		provider: "aimlapi";
	};
	"nemotron-3-super-120b-a12b": Model<"openai-completions"> & {
		id: "nemotron-3-super-120b-a12b";
		provider: "aimlapi";
	};
	"nemotron-3-ultra-550b-a55b": Model<"openai-completions"> & {
		id: "nemotron-3-ultra-550b-a55b";
		provider: "aimlapi";
	};
	"nemotron-nano-9b-v2": Model<"openai-completions"> & {
		id: "nemotron-nano-9b-v2";
		provider: "aimlapi";
	};
	"nova-2-automotive": Model<"openai-completions"> & {
		id: "nova-2-automotive";
		provider: "aimlapi";
	};
	"nova-2-conversationalai": Model<"openai-completions"> & {
		id: "nova-2-conversationalai";
		provider: "aimlapi";
	};
	"nova-2-drivethru": Model<"openai-completions"> & {
		id: "nova-2-drivethru";
		provider: "aimlapi";
	};
	"nova-2-finance": Model<"openai-completions"> & {
		id: "nova-2-finance";
		provider: "aimlapi";
	};
	"nova-2-general": Model<"openai-completions"> & {
		id: "nova-2-general";
		provider: "aimlapi";
	};
	"nova-2-medical": Model<"openai-completions"> & {
		id: "nova-2-medical";
		provider: "aimlapi";
	};
	"nova-2-meeting": Model<"openai-completions"> & {
		id: "nova-2-meeting";
		provider: "aimlapi";
	};
	"nova-2-phonecall": Model<"openai-completions"> & {
		id: "nova-2-phonecall";
		provider: "aimlapi";
	};
	"nova-2-voicemail": Model<"openai-completions"> & {
		id: "nova-2-voicemail";
		provider: "aimlapi";
	};
	"nova-3": Model<"openai-completions"> & {
		id: "nova-3";
		provider: "aimlapi";
	};
	"nova-3-general": Model<"openai-completions"> & {
		id: "nova-3-general";
		provider: "aimlapi";
	};
	"nova-3-medical": Model<"openai-completions"> & {
		id: "nova-3-medical";
		provider: "aimlapi";
	};
	"o1": Model<"openai-completions"> & {
		id: "o1";
		provider: "aimlapi";
	};
	"o1-2024-12-17": Model<"openai-completions"> & {
		id: "o1-2024-12-17";
		provider: "aimlapi";
	};
	"o3-2025-04-16": Model<"openai-completions"> & {
		id: "o3-2025-04-16";
		provider: "aimlapi";
	};
	"o3-mini": Model<"openai-completions"> & {
		id: "o3-mini";
		provider: "aimlapi";
	};
	"o3-mini-2025-01-31": Model<"openai-completions"> & {
		id: "o3-mini-2025-01-31";
		provider: "aimlapi";
	};
	"o3-mini-high": Model<"openai-completions"> & {
		id: "o3-mini-high";
		provider: "aimlapi";
	};
	"o3-pro": Model<"openai-completions"> & {
		id: "o3-pro";
		provider: "aimlapi";
	};
	"o4-mini": Model<"openai-completions"> & {
		id: "o4-mini";
		provider: "aimlapi";
	};
	"o4-mini-2025-04-16": Model<"openai-completions"> & {
		id: "o4-mini-2025-04-16";
		provider: "aimlapi";
	};
	"o4-mini-high": Model<"openai-completions"> & {
		id: "o4-mini-high";
		provider: "aimlapi";
	};
	"octave-2": Model<"openai-completions"> & {
		id: "octave-2";
		provider: "aimlapi";
	};
	"pixverse/lip-sync": Model<"openai-completions"> & {
		id: "pixverse/lip-sync";
		provider: "aimlapi";
	};
	"pixverse/v5/transition": Model<"openai-completions"> & {
		id: "pixverse/v5/transition";
		provider: "aimlapi";
	};
	"qwen-max": Model<"openai-completions"> & {
		id: "qwen-max";
		provider: "aimlapi";
	};
	"qwen-max-2025-01-25": Model<"openai-completions"> & {
		id: "qwen-max-2025-01-25";
		provider: "aimlapi";
	};
	"qwen-plus": Model<"openai-completions"> & {
		id: "qwen-plus";
		provider: "aimlapi";
	};
	"qwen-turbo": Model<"openai-completions"> & {
		id: "qwen-turbo";
		provider: "aimlapi";
	};
	"qwen3-235b-a22b-thinking-2507": Model<"openai-completions"> & {
		id: "qwen3-235b-a22b-thinking-2507";
		provider: "aimlapi";
	};
	"qwen3-32b": Model<"openai-completions"> & {
		id: "qwen3-32b";
		provider: "aimlapi";
	};
	"qwen3-coder-480b-a35b-instruct": Model<"openai-completions"> & {
		id: "qwen3-coder-480b-a35b-instruct";
		provider: "aimlapi";
	};
	"qwen3-max": Model<"openai-completions"> & {
		id: "qwen3-max";
		provider: "aimlapi";
	};
	"qwen3-max-preview": Model<"openai-completions"> & {
		id: "qwen3-max-preview";
		provider: "aimlapi";
	};
	"qwen3-next-80b-a3b-instruct": Model<"openai-completions"> & {
		id: "qwen3-next-80b-a3b-instruct";
		provider: "aimlapi";
	};
	"qwen3-next-80b-a3b-thinking": Model<"openai-completions"> & {
		id: "qwen3-next-80b-a3b-thinking";
		provider: "aimlapi";
	};
	"qwen3-omni-30b-a3b-captioner": Model<"openai-completions"> & {
		id: "qwen3-omni-30b-a3b-captioner";
		provider: "aimlapi";
	};
	"qwen3-vl-32b-instruct": Model<"openai-completions"> & {
		id: "qwen3-vl-32b-instruct";
		provider: "aimlapi";
	};
	"qwen3-vl-32b-thinking": Model<"openai-completions"> & {
		id: "qwen3-vl-32b-thinking";
		provider: "aimlapi";
	};
	"qwen3-vl-flash": Model<"openai-completions"> & {
		id: "qwen3-vl-flash";
		provider: "aimlapi";
	};
	"qwen3-vl-plus": Model<"openai-completions"> & {
		id: "qwen3-vl-plus";
		provider: "aimlapi";
	};
	"qwen3.5-flash": Model<"openai-completions"> & {
		id: "qwen3.5-flash";
		provider: "aimlapi";
	};
	"qwen3.5-omni-flash": Model<"openai-completions"> & {
		id: "qwen3.5-omni-flash";
		provider: "aimlapi";
	};
	"qwen3.5-omni-plus": Model<"openai-completions"> & {
		id: "qwen3.5-omni-plus";
		provider: "aimlapi";
	};
	"qwen3.5-plus": Model<"openai-completions"> & {
		id: "qwen3.5-plus";
		provider: "aimlapi";
	};
	"qwen3.6-27b": Model<"openai-completions"> & {
		id: "qwen3.6-27b";
		provider: "aimlapi";
	};
	"qwen3.6-35b-a3b": Model<"openai-completions"> & {
		id: "qwen3.6-35b-a3b";
		provider: "aimlapi";
	};
	"qwen3.6-flash": Model<"openai-completions"> & {
		id: "qwen3.6-flash";
		provider: "aimlapi";
	};
	"qwen3.6-max-preview": Model<"openai-completions"> & {
		id: "qwen3.6-max-preview";
		provider: "aimlapi";
	};
	"qwen3.6-plus": Model<"openai-completions"> & {
		id: "qwen3.6-plus";
		provider: "aimlapi";
	};
	"qwen3.7-max": Model<"openai-completions"> & {
		id: "qwen3.7-max";
		provider: "aimlapi";
	};
	"qwen3.7-plus": Model<"openai-completions"> & {
		id: "qwen3.7-plus";
		provider: "aimlapi";
	};
	"ray-2": Model<"openai-completions"> & {
		id: "ray-2";
		provider: "aimlapi";
	};
	"ray-flash-2": Model<"openai-completions"> & {
		id: "ray-flash-2";
		provider: "aimlapi";
	};
	"recraft-v3": Model<"openai-completions"> & {
		id: "recraft-v3";
		provider: "aimlapi";
	};
	"redaction": Model<"openai-completions"> & {
		id: "redaction";
		provider: "aimlapi";
	};
	"sharpen": Model<"openai-completions"> & {
		id: "sharpen";
		provider: "aimlapi";
	};
	"sharpen-gen": Model<"openai-completions"> & {
		id: "sharpen-gen";
		provider: "aimlapi";
	};
	"slam-1": Model<"openai-completions"> & {
		id: "slam-1";
		provider: "aimlapi";
	};
	"sonar": Model<"openai-completions"> & {
		id: "sonar";
		provider: "aimlapi";
	};
	"sonar-pro": Model<"openai-completions"> & {
		id: "sonar-pro";
		provider: "aimlapi";
	};
	"stable-diffusion-v3-medium": Model<"openai-completions"> & {
		id: "stable-diffusion-v3-medium";
		provider: "aimlapi";
	};
	"stable-diffusion-v35-large": Model<"openai-completions"> & {
		id: "stable-diffusion-v35-large";
		provider: "aimlapi";
	};
	"stepfun/step-3.7-flash": Model<"openai-completions"> & {
		id: "stepfun/step-3.7-flash";
		provider: "aimlapi";
	};
	"triposr": Model<"openai-completions"> & {
		id: "triposr";
		provider: "aimlapi";
	};
	"universal": Model<"openai-completions"> & {
		id: "universal";
		provider: "aimlapi";
	};
	"uso": Model<"openai-completions"> & {
		id: "uso";
		provider: "aimlapi";
	};
	"veed/fabric-1.0": Model<"openai-completions"> & {
		id: "veed/fabric-1.0";
		provider: "aimlapi";
	};
	"veed/fabric-1.0/fast": Model<"openai-completions"> & {
		id: "veed/fabric-1.0/fast";
		provider: "aimlapi";
	};
	"vibevoice": Model<"openai-completions"> & {
		id: "vibevoice";
		provider: "aimlapi";
	};
	"vibevoice/7b": Model<"openai-completions"> & {
		id: "vibevoice/7b";
		provider: "aimlapi";
	};
	"voyage-2": Model<"openai-completions"> & {
		id: "voyage-2";
		provider: "aimlapi";
	};
	"voyage-code-2": Model<"openai-completions"> & {
		id: "voyage-code-2";
		provider: "aimlapi";
	};
	"voyage-finance-2": Model<"openai-completions"> & {
		id: "voyage-finance-2";
		provider: "aimlapi";
	};
	"voyage-large-2": Model<"openai-completions"> & {
		id: "voyage-large-2";
		provider: "aimlapi";
	};
	"voyage-large-2-instruct": Model<"openai-completions"> & {
		id: "voyage-large-2-instruct";
		provider: "aimlapi";
	};
	"voyage-law-2": Model<"openai-completions"> & {
		id: "voyage-law-2";
		provider: "aimlapi";
	};
	"voyage-multilingual-2": Model<"openai-completions"> & {
		id: "voyage-multilingual-2";
		provider: "aimlapi";
	};
	"wan2.6-r2v": Model<"openai-completions"> & {
		id: "wan2.6-r2v";
		provider: "aimlapi";
	};
	"wan2.7-r2v": Model<"openai-completions"> & {
		id: "wan2.7-r2v";
		provider: "aimlapi";
	};
	"x-ai/grok-3-beta": Model<"openai-completions"> & {
		id: "x-ai/grok-3-beta";
		provider: "aimlapi";
	};
	"x-ai/grok-3-mini-beta": Model<"openai-completions"> & {
		id: "x-ai/grok-3-mini-beta";
		provider: "aimlapi";
	};
	"x-ai/grok-4-07-09": Model<"openai-completions"> & {
		id: "x-ai/grok-4-07-09";
		provider: "aimlapi";
	};
	"x-ai/grok-4-3": Model<"openai-completions"> & {
		id: "x-ai/grok-4-3";
		provider: "aimlapi";
	};
	"x-ai/grok-code-fast-1": Model<"openai-completions"> & {
		id: "x-ai/grok-code-fast-1";
		provider: "aimlapi";
	};
	"xai/grok-build-0-1": Model<"openai-completions"> & {
		id: "xai/grok-build-0-1";
		provider: "aimlapi";
	};
	"xiaomi/mimo-v2-flash": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2-flash";
		provider: "aimlapi";
	};
	"xiaomi/mimo-v2.5": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2.5";
		provider: "aimlapi";
	};
	"xiaomi/mimo-v2.5-pro": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2.5-pro";
		provider: "aimlapi";
	};
};
