// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/alibaba-coding-plan.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const ALIBABA_CODING_PLAN_MODELS: ModelCatalog<typeof values, "alibaba-coding-plan"> =
	flattenModelCatalog("alibaba-coding-plan", values);
