// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/alibaba-token-plan.json" with { type: "json" };
import type { Model } from "../types.ts";

export const ALIBABA_TOKEN_PLAN_MODELS = values as {
	"deepseek-v4-pro": Model<"openai-completions"> & {
		id: "deepseek-v4-pro";
		provider: "alibaba-token-plan";
	};
	"glm-5.2": Model<"openai-completions"> & {
		id: "glm-5.2";
		provider: "alibaba-token-plan";
	};
	"qwen3.6-flash": Model<"openai-completions"> & {
		id: "qwen3.6-flash";
		provider: "alibaba-token-plan";
	};
	"qwen3.7-max": Model<"openai-completions"> & {
		id: "qwen3.7-max";
		provider: "alibaba-token-plan";
	};
	"qwen3.7-plus": Model<"openai-completions"> & {
		id: "qwen3.7-plus";
		provider: "alibaba-token-plan";
	};
	"qwen3.8-max": Model<"openai-completions"> & {
		id: "qwen3.8-max";
		provider: "alibaba-token-plan";
	};
	"qwen3.8-max-preview": Model<"openai-completions"> & {
		id: "qwen3.8-max-preview";
		provider: "alibaba-token-plan";
	};
};
