// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/bedrock-mantle.json" with { type: "json" };
import type { Model } from "../types.ts";

export const BEDROCK_MANTLE_MODELS = values as {
	"openai.gpt-5.4": Model<"openai-responses"> & {
		id: "openai.gpt-5.4";
		provider: "bedrock-mantle";
	};
	"openai.gpt-5.5": Model<"openai-responses"> & {
		id: "openai.gpt-5.5";
		provider: "bedrock-mantle";
	};
	"openai.gpt-5.6-luna": Model<"openai-responses"> & {
		id: "openai.gpt-5.6-luna";
		provider: "bedrock-mantle";
	};
	"openai.gpt-5.6-sol": Model<"openai-responses"> & {
		id: "openai.gpt-5.6-sol";
		provider: "bedrock-mantle";
	};
	"openai.gpt-5.6-terra": Model<"openai-responses"> & {
		id: "openai.gpt-5.6-terra";
		provider: "bedrock-mantle";
	};
};
