// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/bedrock-mantle.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const BEDROCK_MANTLE_MODELS: ModelCatalog<typeof values, "bedrock-mantle"> =
	flattenModelCatalog("bedrock-mantle", values);
