// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/cline-pass.json" with { type: "json" };
import type { Model } from "../types.ts";

export const CLINE_PASS_MODELS = values as {
	"cline-free/longcat-2.0": Model<"openai-completions"> & {
		id: "cline-free/longcat-2.0";
		provider: "cline-pass";
	};
	"deepseek-v4-flash": Model<"openai-completions"> & {
		id: "deepseek-v4-flash";
		provider: "cline-pass";
	};
	"deepseek-v4-pro": Model<"openai-completions"> & {
		id: "deepseek-v4-pro";
		provider: "cline-pass";
	};
	"deepseek/deepseek-v4-flash": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-flash";
		provider: "cline-pass";
	};
	"glm-5.2": Model<"openai-completions"> & {
		id: "glm-5.2";
		provider: "cline-pass";
	};
	"glm-5.3": Model<"openai-completions"> & {
		id: "glm-5.3";
		provider: "cline-pass";
	};
	"glm-5.3-flash": Model<"openai-completions"> & {
		id: "glm-5.3-flash";
		provider: "cline-pass";
	};
	"kimi-k2.6": Model<"openai-completions"> & {
		id: "kimi-k2.6";
		provider: "cline-pass";
	};
	"kimi-k2.7-code": Model<"openai-completions"> & {
		id: "kimi-k2.7-code";
		provider: "cline-pass";
	};
	"kimi-k3": Model<"openai-completions"> & {
		id: "kimi-k3";
		provider: "cline-pass";
	};
	"mimo-v2.5": Model<"openai-completions"> & {
		id: "mimo-v2.5";
		provider: "cline-pass";
	};
	"mimo-v2.5-pro": Model<"openai-completions"> & {
		id: "mimo-v2.5-pro";
		provider: "cline-pass";
	};
	"minimax-m3": Model<"openai-completions"> & {
		id: "minimax-m3";
		provider: "cline-pass";
	};
	"poolside/laguna-s-2.1:free": Model<"openai-completions"> & {
		id: "poolside/laguna-s-2.1:free";
		provider: "cline-pass";
	};
	"qwen3.7-max": Model<"openai-completions"> & {
		id: "qwen3.7-max";
		provider: "cline-pass";
	};
	"qwen3.7-plus": Model<"openai-completions"> & {
		id: "qwen3.7-plus";
		provider: "cline-pass";
	};
	"qwen3.8-max": Model<"openai-completions"> & {
		id: "qwen3.8-max";
		provider: "cline-pass";
	};
	"z-ai/glm-5.3-flash": Model<"openai-completions"> & {
		id: "z-ai/glm-5.3-flash";
		provider: "cline-pass";
	};
};
