// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/coreweave.json" with { type: "json" };
import type { Model } from "../types.ts";

export const COREWEAVE_MODELS = values as {
	"JetBrains/Mellum2-12B-A2.5B-Instruct": Model<"openai-completions"> & {
		id: "JetBrains/Mellum2-12B-A2.5B-Instruct";
		provider: "coreweave";
	};
	"MiniMaxAI/MiniMax-M2.5": Model<"openai-completions"> & {
		id: "MiniMaxAI/MiniMax-M2.5";
		provider: "coreweave";
	};
	"MiniMaxAI/MiniMax-M3": Model<"openai-completions"> & {
		id: "MiniMaxAI/MiniMax-M3";
		provider: "coreweave";
	};
	"OpenPipe/Qwen3-14B-Instruct": Model<"openai-completions"> & {
		id: "OpenPipe/Qwen3-14B-Instruct";
		provider: "coreweave";
	};
	"Qwen/Qwen3-235B-A22B-Instruct-2507": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-235B-A22B-Instruct-2507";
		provider: "coreweave";
	};
	"Qwen/Qwen3-235B-A22B-Thinking-2507": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-235B-A22B-Thinking-2507";
		provider: "coreweave";
	};
	"Qwen/Qwen3-30B-A3B-Instruct-2507": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-30B-A3B-Instruct-2507";
		provider: "coreweave";
	};
	"Qwen/Qwen3-Coder-480B-A35B-Instruct": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-Coder-480B-A35B-Instruct";
		provider: "coreweave";
	};
	"Qwen/Qwen3.5-27B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.5-27B";
		provider: "coreweave";
	};
	"Qwen/Qwen3.5-35B-A3B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.5-35B-A3B";
		provider: "coreweave";
	};
	"Qwen/Qwen3.6-27B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.6-27B";
		provider: "coreweave";
	};
	"Qwen/Qwen3.6-35B-A3B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.6-35B-A3B";
		provider: "coreweave";
	};
	"deepseek-ai/DeepSeek-V3.1": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V3.1";
		provider: "coreweave";
	};
	"deepseek-ai/DeepSeek-V4-Flash": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V4-Flash";
		provider: "coreweave";
	};
	"deepseek-ai/DeepSeek-V4-Flash-0731": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V4-Flash-0731";
		provider: "coreweave";
	};
	"deepseek-ai/DeepSeek-V4-Pro": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V4-Pro";
		provider: "coreweave";
	};
	"google/gemma-4-31B-it": Model<"openai-completions"> & {
		id: "google/gemma-4-31B-it";
		provider: "coreweave";
	};
	"ibm-granite/granite-4.1-8b": Model<"openai-completions"> & {
		id: "ibm-granite/granite-4.1-8b";
		provider: "coreweave";
	};
	"meta-llama/Llama-3.1-70B-Instruct": Model<"openai-completions"> & {
		id: "meta-llama/Llama-3.1-70B-Instruct";
		provider: "coreweave";
	};
	"meta-llama/Llama-3.1-8B-Instruct": Model<"openai-completions"> & {
		id: "meta-llama/Llama-3.1-8B-Instruct";
		provider: "coreweave";
	};
	"meta-llama/Llama-3.3-70B-Instruct": Model<"openai-completions"> & {
		id: "meta-llama/Llama-3.3-70B-Instruct";
		provider: "coreweave";
	};
	"meta-llama/Llama-4-Scout-17B-16E-Instruct": Model<"openai-completions"> & {
		id: "meta-llama/Llama-4-Scout-17B-16E-Instruct";
		provider: "coreweave";
	};
	"microsoft/Phi-4-mini-instruct": Model<"openai-completions"> & {
		id: "microsoft/Phi-4-mini-instruct";
		provider: "coreweave";
	};
	"moonshotai/Kimi-K2.5": Model<"openai-completions"> & {
		id: "moonshotai/Kimi-K2.5";
		provider: "coreweave";
	};
	"moonshotai/Kimi-K2.6": Model<"openai-completions"> & {
		id: "moonshotai/Kimi-K2.6";
		provider: "coreweave";
	};
	"moonshotai/Kimi-K2.7-Code": Model<"openai-completions"> & {
		id: "moonshotai/Kimi-K2.7-Code";
		provider: "coreweave";
	};
	"moonshotai/Kimi-K3": Model<"openai-completions"> & {
		id: "moonshotai/Kimi-K3";
		provider: "coreweave";
	};
	"nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8": Model<"openai-completions"> & {
		id: "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8";
		provider: "coreweave";
	};
	"nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B": Model<"openai-completions"> & {
		id: "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B";
		provider: "coreweave";
	};
	"openai/gpt-oss-120b": Model<"openai-completions"> & {
		id: "openai/gpt-oss-120b";
		provider: "coreweave";
	};
	"openai/gpt-oss-20b": Model<"openai-completions"> & {
		id: "openai/gpt-oss-20b";
		provider: "coreweave";
	};
	"zai-org/GLM-5-FP8": Model<"openai-completions"> & {
		id: "zai-org/GLM-5-FP8";
		provider: "coreweave";
	};
	"zai-org/GLM-5.1": Model<"openai-completions"> & {
		id: "zai-org/GLM-5.1";
		provider: "coreweave";
	};
	"zai-org/GLM-5.2": Model<"openai-completions"> & {
		id: "zai-org/GLM-5.2";
		provider: "coreweave";
	};
};
