// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/deepinfra.json" with { type: "json" };
import type { Model } from "../types.ts";

export const DEEPINFRA_MODELS = values as {
	"ByteDance/Seed-1.8": Model<"openai-completions"> & {
		id: "ByteDance/Seed-1.8";
		provider: "deepinfra";
	};
	"ByteDance/Seed-2.0-code": Model<"openai-completions"> & {
		id: "ByteDance/Seed-2.0-code";
		provider: "deepinfra";
	};
	"ByteDance/Seed-2.0-mini": Model<"openai-completions"> & {
		id: "ByteDance/Seed-2.0-mini";
		provider: "deepinfra";
	};
	"ByteDance/Seed-2.0-pro": Model<"openai-completions"> & {
		id: "ByteDance/Seed-2.0-pro";
		provider: "deepinfra";
	};
	"Gryphe/MythoMax-L2-13b": Model<"openai-completions"> & {
		id: "Gryphe/MythoMax-L2-13b";
		provider: "deepinfra";
	};
	"MiniMaxAI/MiniMax-M2.7": Model<"openai-completions"> & {
		id: "MiniMaxAI/MiniMax-M2.7";
		provider: "deepinfra";
	};
	"MiniMaxAI/MiniMax-M2.7-Turbo": Model<"openai-completions"> & {
		id: "MiniMaxAI/MiniMax-M2.7-Turbo";
		provider: "deepinfra";
	};
	"MiniMaxAI/MiniMax-M3": Model<"openai-completions"> & {
		id: "MiniMaxAI/MiniMax-M3";
		provider: "deepinfra";
	};
	"NousResearch/Hermes-3-Llama-3.1-405B": Model<"openai-completions"> & {
		id: "NousResearch/Hermes-3-Llama-3.1-405B";
		provider: "deepinfra";
	};
	"NousResearch/Hermes-3-Llama-3.1-70B": Model<"openai-completions"> & {
		id: "NousResearch/Hermes-3-Llama-3.1-70B";
		provider: "deepinfra";
	};
	"Qwen/Qwen2.5-72B-Instruct": Model<"openai-completions"> & {
		id: "Qwen/Qwen2.5-72B-Instruct";
		provider: "deepinfra";
	};
	"Qwen/Qwen3-14B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-14B";
		provider: "deepinfra";
	};
	"Qwen/Qwen3-235B-A22B-Instruct-2507": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-235B-A22B-Instruct-2507";
		provider: "deepinfra";
	};
	"Qwen/Qwen3-30B-A3B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-30B-A3B";
		provider: "deepinfra";
	};
	"Qwen/Qwen3-32B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-32B";
		provider: "deepinfra";
	};
	"Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo";
		provider: "deepinfra";
	};
	"Qwen/Qwen3-Max": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-Max";
		provider: "deepinfra";
	};
	"Qwen/Qwen3-Next-80B-A3B-Instruct": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-Next-80B-A3B-Instruct";
		provider: "deepinfra";
	};
	"Qwen/Qwen3-VL-235B-A22B-Instruct": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-VL-235B-A22B-Instruct";
		provider: "deepinfra";
	};
	"Qwen/Qwen3-VL-30B-A3B-Instruct": Model<"openai-completions"> & {
		id: "Qwen/Qwen3-VL-30B-A3B-Instruct";
		provider: "deepinfra";
	};
	"Qwen/Qwen3.5-122B-A10B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.5-122B-A10B";
		provider: "deepinfra";
	};
	"Qwen/Qwen3.5-27B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.5-27B";
		provider: "deepinfra";
	};
	"Qwen/Qwen3.5-35B-A3B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.5-35B-A3B";
		provider: "deepinfra";
	};
	"Qwen/Qwen3.5-397B-A17B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.5-397B-A17B";
		provider: "deepinfra";
	};
	"Qwen/Qwen3.5-9B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.5-9B";
		provider: "deepinfra";
	};
	"Qwen/Qwen3.6-27B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.6-27B";
		provider: "deepinfra";
	};
	"Qwen/Qwen3.6-35B-A3B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.6-35B-A3B";
		provider: "deepinfra";
	};
	"Qwen/Qwen3.7-Max": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.7-Max";
		provider: "deepinfra";
	};
	"Qwen/Qwen3.8-2.4T-A95B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.8-2.4T-A95B";
		provider: "deepinfra";
	};
	"Qwen/Qwen3.8-27B": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.8-27B";
		provider: "deepinfra";
	};
	"Qwen/Qwen3.8-Max": Model<"openai-completions"> & {
		id: "Qwen/Qwen3.8-Max";
		provider: "deepinfra";
	};
	"Sao10K/L3-8B-Lunaris-v1-Turbo": Model<"openai-completions"> & {
		id: "Sao10K/L3-8B-Lunaris-v1-Turbo";
		provider: "deepinfra";
	};
	"Sao10K/L3.1-70B-Euryale-v2.2": Model<"openai-completions"> & {
		id: "Sao10K/L3.1-70B-Euryale-v2.2";
		provider: "deepinfra";
	};
	"XiaomiMiMo/MiMo-V2.5": Model<"openai-completions"> & {
		id: "XiaomiMiMo/MiMo-V2.5";
		provider: "deepinfra";
	};
	"XiaomiMiMo/MiMo-V2.5-Pro": Model<"openai-completions"> & {
		id: "XiaomiMiMo/MiMo-V2.5-Pro";
		provider: "deepinfra";
	};
	"anthropic/claude-fable-5": Model<"openai-completions"> & {
		id: "anthropic/claude-fable-5";
		provider: "deepinfra";
	};
	"anthropic/claude-haiku-4-5": Model<"openai-completions"> & {
		id: "anthropic/claude-haiku-4-5";
		provider: "deepinfra";
	};
	"anthropic/claude-opus-4-7": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-4-7";
		provider: "deepinfra";
	};
	"anthropic/claude-opus-4-8": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-4-8";
		provider: "deepinfra";
	};
	"anthropic/claude-opus-5": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-5";
		provider: "deepinfra";
	};
	"anthropic/claude-sonnet-4-6": Model<"openai-completions"> & {
		id: "anthropic/claude-sonnet-4-6";
		provider: "deepinfra";
	};
	"anthropic/claude-sonnet-5": Model<"openai-completions"> & {
		id: "anthropic/claude-sonnet-5";
		provider: "deepinfra";
	};
	"deepseek-ai/DeepSeek-R1-0528": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-R1-0528";
		provider: "deepinfra";
	};
	"deepseek-ai/DeepSeek-V3": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V3";
		provider: "deepinfra";
	};
	"deepseek-ai/DeepSeek-V3-0324": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V3-0324";
		provider: "deepinfra";
	};
	"deepseek-ai/DeepSeek-V3.1": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V3.1";
		provider: "deepinfra";
	};
	"deepseek-ai/DeepSeek-V3.2": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V3.2";
		provider: "deepinfra";
	};
	"deepseek-ai/DeepSeek-V4-Flash": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V4-Flash";
		provider: "deepinfra";
	};
	"deepseek-ai/DeepSeek-V4-Flash-0731": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V4-Flash-0731";
		provider: "deepinfra";
	};
	"deepseek-ai/DeepSeek-V4-Flash-Vision-Exp": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp";
		provider: "deepinfra";
	};
	"deepseek-ai/DeepSeek-V4-Pro": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V4-Pro";
		provider: "deepinfra";
	};
	"deepseek-ai/DeepSeek-V4-Pro-0813": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V4-Pro-0813";
		provider: "deepinfra";
	};
	"google/gemini-2.5-flash": Model<"openai-completions"> & {
		id: "google/gemini-2.5-flash";
		provider: "deepinfra";
	};
	"google/gemini-2.5-pro": Model<"openai-completions"> & {
		id: "google/gemini-2.5-pro";
		provider: "deepinfra";
	};
	"google/gemini-3.1-flash-lite": Model<"openai-completions"> & {
		id: "google/gemini-3.1-flash-lite";
		provider: "deepinfra";
	};
	"google/gemini-3.1-pro": Model<"openai-completions"> & {
		id: "google/gemini-3.1-pro";
		provider: "deepinfra";
	};
	"google/gemini-3.5-flash": Model<"openai-completions"> & {
		id: "google/gemini-3.5-flash";
		provider: "deepinfra";
	};
	"google/gemini-3.7-flash": Model<"openai-completions"> & {
		id: "google/gemini-3.7-flash";
		provider: "deepinfra";
	};
	"google/gemma-3-12b-it": Model<"openai-completions"> & {
		id: "google/gemma-3-12b-it";
		provider: "deepinfra";
	};
	"google/gemma-3-27b-it": Model<"openai-completions"> & {
		id: "google/gemma-3-27b-it";
		provider: "deepinfra";
	};
	"google/gemma-3-4b-it": Model<"openai-completions"> & {
		id: "google/gemma-3-4b-it";
		provider: "deepinfra";
	};
	"google/gemma-4-26B-A4B-it": Model<"openai-completions"> & {
		id: "google/gemma-4-26B-A4B-it";
		provider: "deepinfra";
	};
	"google/gemma-4-31B-it": Model<"openai-completions"> & {
		id: "google/gemma-4-31B-it";
		provider: "deepinfra";
	};
	"google/gemma-4-31B-it-Ultra": Model<"openai-completions"> & {
		id: "google/gemma-4-31B-it-Ultra";
		provider: "deepinfra";
	};
	"google/gemma-4-31B-it-turbo": Model<"openai-completions"> & {
		id: "google/gemma-4-31B-it-turbo";
		provider: "deepinfra";
	};
	"google/gemma-4-E4B-it": Model<"openai-completions"> & {
		id: "google/gemma-4-E4B-it";
		provider: "deepinfra";
	};
	"ibm-granite/granite-4.2-30b": Model<"openai-completions"> & {
		id: "ibm-granite/granite-4.2-30b";
		provider: "deepinfra";
	};
	"ibm-granite/granite-4.2-3b": Model<"openai-completions"> & {
		id: "ibm-granite/granite-4.2-3b";
		provider: "deepinfra";
	};
	"ibm-granite/granite-4.2-8b": Model<"openai-completions"> & {
		id: "ibm-granite/granite-4.2-8b";
		provider: "deepinfra";
	};
	"inclusionAI/Ling-3.0-flash": Model<"openai-completions"> & {
		id: "inclusionAI/Ling-3.0-flash";
		provider: "deepinfra";
	};
	"inclusionAI/Ling-3.0-flash-Fin": Model<"openai-completions"> & {
		id: "inclusionAI/Ling-3.0-flash-Fin";
		provider: "deepinfra";
	};
	"meta-llama/Llama-3.3-70B-Instruct-Turbo": Model<"openai-completions"> & {
		id: "meta-llama/Llama-3.3-70B-Instruct-Turbo";
		provider: "deepinfra";
	};
	"meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8": Model<"openai-completions"> & {
		id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8";
		provider: "deepinfra";
	};
	"meta-llama/Llama-4-Scout-17B-16E-Instruct": Model<"openai-completions"> & {
		id: "meta-llama/Llama-4-Scout-17B-16E-Instruct";
		provider: "deepinfra";
	};
	"meta-llama/Llama-Guard-4-12B": Model<"openai-completions"> & {
		id: "meta-llama/Llama-Guard-4-12B";
		provider: "deepinfra";
	};
	"meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo": Model<"openai-completions"> & {
		id: "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo";
		provider: "deepinfra";
	};
	"meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo": Model<"openai-completions"> & {
		id: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo";
		provider: "deepinfra";
	};
	"meta-models/Muse-Glimmer-30B": Model<"openai-completions"> & {
		id: "meta-models/Muse-Glimmer-30B";
		provider: "deepinfra";
	};
	"microsoft/phi-4": Model<"openai-completions"> & {
		id: "microsoft/phi-4";
		provider: "deepinfra";
	};
	"mistralai/Mistral-Nemo-Instruct-2407": Model<"openai-completions"> & {
		id: "mistralai/Mistral-Nemo-Instruct-2407";
		provider: "deepinfra";
	};
	"mistralai/Mistral-Small-24B-Instruct-2501": Model<"openai-completions"> & {
		id: "mistralai/Mistral-Small-24B-Instruct-2501";
		provider: "deepinfra";
	};
	"mistralai/Mistral-Small-3.2-24B-Instruct-2506": Model<"openai-completions"> & {
		id: "mistralai/Mistral-Small-3.2-24B-Instruct-2506";
		provider: "deepinfra";
	};
	"moonshotai/Kimi-K2.6": Model<"openai-completions"> & {
		id: "moonshotai/Kimi-K2.6";
		provider: "deepinfra";
	};
	"moonshotai/Kimi-K2.7-Code": Model<"openai-completions"> & {
		id: "moonshotai/Kimi-K2.7-Code";
		provider: "deepinfra";
	};
	"moonshotai/Kimi-K3": Model<"openai-completions"> & {
		id: "moonshotai/Kimi-K3";
		provider: "deepinfra";
	};
	"nvidia/NVIDIA-Nemotron-3-Super-120B-A12B": Model<"openai-completions"> & {
		id: "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B";
		provider: "deepinfra";
	};
	"nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B": Model<"openai-completions"> & {
		id: "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B";
		provider: "deepinfra";
	};
	"nvidia/NVIDIA-Nemotron-3.5-Lightning": Model<"openai-completions"> & {
		id: "nvidia/NVIDIA-Nemotron-3.5-Lightning";
		provider: "deepinfra";
	};
	"nvidia/Nemotron-3-Nano-30B-A3B": Model<"openai-completions"> & {
		id: "nvidia/Nemotron-3-Nano-30B-A3B";
		provider: "deepinfra";
	};
	"nvidia/Nemotron-Content-Safety-3.5": Model<"openai-completions"> & {
		id: "nvidia/Nemotron-Content-Safety-3.5";
		provider: "deepinfra";
	};
	"openai/gpt-oss-120b": Model<"openai-completions"> & {
		id: "openai/gpt-oss-120b";
		provider: "deepinfra";
	};
	"openai/gpt-oss-120b-Turbo": Model<"openai-completions"> & {
		id: "openai/gpt-oss-120b-Turbo";
		provider: "deepinfra";
	};
	"openai/gpt-oss-120b-Ultra": Model<"openai-completions"> & {
		id: "openai/gpt-oss-120b-Ultra";
		provider: "deepinfra";
	};
	"openai/gpt-oss-20b": Model<"openai-completions"> & {
		id: "openai/gpt-oss-20b";
		provider: "deepinfra";
	};
	"stepfun-ai/Step-3.7-Flash": Model<"openai-completions"> & {
		id: "stepfun-ai/Step-3.7-Flash";
		provider: "deepinfra";
	};
	"tencent/Hy3": Model<"openai-completions"> & {
		id: "tencent/Hy3";
		provider: "deepinfra";
	};
	"thinkingmachines/Inkling": Model<"openai-completions"> & {
		id: "thinkingmachines/Inkling";
		provider: "deepinfra";
	};
	"thinkingmachines/Inkling-Small": Model<"openai-completions"> & {
		id: "thinkingmachines/Inkling-Small";
		provider: "deepinfra";
	};
	"zai-org/GLM-4.6": Model<"openai-completions"> & {
		id: "zai-org/GLM-4.6";
		provider: "deepinfra";
	};
	"zai-org/GLM-4.7": Model<"openai-completions"> & {
		id: "zai-org/GLM-4.7";
		provider: "deepinfra";
	};
	"zai-org/GLM-4.7-Flash": Model<"openai-completions"> & {
		id: "zai-org/GLM-4.7-Flash";
		provider: "deepinfra";
	};
	"zai-org/GLM-5": Model<"openai-completions"> & {
		id: "zai-org/GLM-5";
		provider: "deepinfra";
	};
	"zai-org/GLM-5.1": Model<"openai-completions"> & {
		id: "zai-org/GLM-5.1";
		provider: "deepinfra";
	};
	"zai-org/GLM-5.2": Model<"openai-completions"> & {
		id: "zai-org/GLM-5.2";
		provider: "deepinfra";
	};
	"zai-org/GLM-5.3": Model<"openai-completions"> & {
		id: "zai-org/GLM-5.3";
		provider: "deepinfra";
	};
	"zai-org/GLM-5.3-Flash": Model<"openai-completions"> & {
		id: "zai-org/GLM-5.3-Flash";
		provider: "deepinfra";
	};
};
