// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/fireworks.json" with { type: "json" };
import type { Model } from "../types.ts";

export const FIREWORKS_MODELS = values as {
	"accounts/fireworks/models/deepseek-v4-flash": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/deepseek-v4-flash";
		provider: "fireworks";
	};
	"accounts/fireworks/models/deepseek-v4-pro": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/deepseek-v4-pro";
		provider: "fireworks";
	};
	"accounts/fireworks/models/glm-5p1": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/glm-5p1";
		provider: "fireworks";
	};
	"accounts/fireworks/models/glm-5p2": Model<"openai-completions"> & {
		id: "accounts/fireworks/models/glm-5p2";
		provider: "fireworks";
	};
	"accounts/fireworks/models/gpt-oss-120b": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/gpt-oss-120b";
		provider: "fireworks";
	};
	"accounts/fireworks/models/gpt-oss-20b": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/gpt-oss-20b";
		provider: "fireworks";
	};
	"accounts/fireworks/models/kimi-k2p6": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/kimi-k2p6";
		provider: "fireworks";
	};
	"accounts/fireworks/models/kimi-k2p7-code": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/kimi-k2p7-code";
		provider: "fireworks";
	};
	"accounts/fireworks/models/minimax-m2p7": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/minimax-m2p7";
		provider: "fireworks";
	};
	"accounts/fireworks/models/minimax-m3": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/minimax-m3";
		provider: "fireworks";
	};
	"accounts/fireworks/models/qwen3p7-plus": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/models/qwen3p7-plus";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/glm-5p1-fast": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/glm-5p1-fast";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/glm-5p2-fast": Model<"openai-completions"> & {
		id: "accounts/fireworks/routers/glm-5p2-fast";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/kimi-k2p6-fast": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/kimi-k2p6-fast";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/kimi-k2p6-turbo": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/kimi-k2p6-turbo";
		provider: "fireworks";
	};
	"accounts/fireworks/routers/kimi-k2p7-code-fast": Model<"anthropic-messages"> & {
		id: "accounts/fireworks/routers/kimi-k2p7-code-fast";
		provider: "fireworks";
	};
	"deepseek-v4-flash": Model<"openai-completions"> & {
		id: "deepseek-v4-flash";
		provider: "fireworks";
	};
	"deepseek-v4-flash-0731": Model<"openai-completions"> & {
		id: "deepseek-v4-flash-0731";
		provider: "fireworks";
	};
	"deepseek-v4-flash-vision-exp": Model<"openai-completions"> & {
		id: "deepseek-v4-flash-vision-exp";
		provider: "fireworks";
	};
	"deepseek-v4-pro": Model<"openai-completions"> & {
		id: "deepseek-v4-pro";
		provider: "fireworks";
	};
	"deepseek-v4-pro-0813": Model<"openai-completions"> & {
		id: "deepseek-v4-pro-0813";
		provider: "fireworks";
	};
	"flux-1-schnell-fp8": Model<"openai-completions"> & {
		id: "flux-1-schnell-fp8";
		provider: "fireworks";
	};
	"glm-5": Model<"openai-completions"> & {
		id: "glm-5";
		provider: "fireworks";
	};
	"glm-5.1": Model<"openai-completions"> & {
		id: "glm-5.1";
		provider: "fireworks";
	};
	"glm-5.1-fast": Model<"openai-completions"> & {
		id: "glm-5.1-fast";
		provider: "fireworks";
	};
	"glm-5.2": Model<"openai-completions"> & {
		id: "glm-5.2";
		provider: "fireworks";
	};
	"glm-5.2-fast": Model<"openai-completions"> & {
		id: "glm-5.2-fast";
		provider: "fireworks";
	};
	"glm-5.3": Model<"openai-completions"> & {
		id: "glm-5.3";
		provider: "fireworks";
	};
	"glm-5.3-flash": Model<"openai-completions"> & {
		id: "glm-5.3-flash";
		provider: "fireworks";
	};
	"gpt-oss-120b": Model<"openai-completions"> & {
		id: "gpt-oss-120b";
		provider: "fireworks";
	};
	"gpt-oss-20b": Model<"openai-completions"> & {
		id: "gpt-oss-20b";
		provider: "fireworks";
	};
	"inkling": Model<"openai-completions"> & {
		id: "inkling";
		provider: "fireworks";
	};
	"kimi-k2.5": Model<"openai-completions"> & {
		id: "kimi-k2.5";
		provider: "fireworks";
	};
	"kimi-k2.6": Model<"openai-completions"> & {
		id: "kimi-k2.6";
		provider: "fireworks";
	};
	"kimi-k2.6-fast": Model<"openai-completions"> & {
		id: "kimi-k2.6-fast";
		provider: "fireworks";
	};
	"kimi-k2.7-code": Model<"openai-completions"> & {
		id: "kimi-k2.7-code";
		provider: "fireworks";
	};
	"kimi-k2.7-code-fast": Model<"openai-completions"> & {
		id: "kimi-k2.7-code-fast";
		provider: "fireworks";
	};
	"kimi-k3": Model<"openai-completions"> & {
		id: "kimi-k3";
		provider: "fireworks";
	};
	"minimax-m2.5": Model<"openai-completions"> & {
		id: "minimax-m2.5";
		provider: "fireworks";
	};
	"minimax-m2.7": Model<"openai-completions"> & {
		id: "minimax-m2.7";
		provider: "fireworks";
	};
	"minimax-m3": Model<"openai-completions"> & {
		id: "minimax-m3";
		provider: "fireworks";
	};
	"muse-glimmer-30b": Model<"openai-completions"> & {
		id: "muse-glimmer-30b";
		provider: "fireworks";
	};
	"nemotron-3-ultra-nvfp4": Model<"openai-completions"> & {
		id: "nemotron-3-ultra-nvfp4";
		provider: "fireworks";
	};
	"nemotron-lightning-3.5-30b-a3b": Model<"openai-completions"> & {
		id: "nemotron-lightning-3.5-30b-a3b";
		provider: "fireworks";
	};
	"qwen3-embedding-8b": Model<"openai-completions"> & {
		id: "qwen3-embedding-8b";
		provider: "fireworks";
	};
	"qwen3-reranker-8b": Model<"openai-completions"> & {
		id: "qwen3-reranker-8b";
		provider: "fireworks";
	};
	"qwen3.6-plus": Model<"openai-completions"> & {
		id: "qwen3.6-plus";
		provider: "fireworks";
	};
	"qwen3.7-plus": Model<"openai-completions"> & {
		id: "qwen3.7-plus";
		provider: "fireworks";
	};
	"qwen3.8-2.4t-a95b": Model<"openai-completions"> & {
		id: "qwen3.8-2.4t-a95b";
		provider: "fireworks";
	};
	"qwen3.8-max": Model<"openai-completions"> & {
		id: "qwen3.8-max";
		provider: "fireworks";
	};
};
