// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/firepass.json" with { type: "json" };
import type { Model } from "../types.ts";

export const FIREPASS_MODELS = values as {
	"kimi-k2.6-turbo": Model<"openai-completions"> & {
		id: "kimi-k2.6-turbo";
		provider: "firepass";
	};
};
