// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/gmi-cloud.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const GMI_CLOUD_MODELS: ModelCatalog<typeof values, "gmi-cloud"> =
	flattenModelCatalog("gmi-cloud", values);
