// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/gmi-cloud.json" with { type: "json" };
import type { Model } from "../types.ts";

export const GMI_CLOUD_MODELS = values as {
	"deepseek-ai/DeepSeek-V4-Flash": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V4-Flash";
		provider: "gmi-cloud";
	};
};
