// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/kilo.json" with { type: "json" };
import type { Model } from "../types.ts";

export const KILO_MODELS = values as {
	"ai21/jamba-large-1.7": Model<"openai-completions"> & {
		id: "ai21/jamba-large-1.7";
		provider: "kilo";
	};
	"aion-labs/aion-1.0": Model<"openai-completions"> & {
		id: "aion-labs/aion-1.0";
		provider: "kilo";
	};
	"aion-labs/aion-1.0-mini": Model<"openai-completions"> & {
		id: "aion-labs/aion-1.0-mini";
		provider: "kilo";
	};
	"aion-labs/aion-2.0": Model<"openai-completions"> & {
		id: "aion-labs/aion-2.0";
		provider: "kilo";
	};
	"aion-labs/aion-3.0": Model<"openai-completions"> & {
		id: "aion-labs/aion-3.0";
		provider: "kilo";
	};
	"aion-labs/aion-3.0-mini": Model<"openai-completions"> & {
		id: "aion-labs/aion-3.0-mini";
		provider: "kilo";
	};
	"aion-labs/aion-rp-llama-3.1-8b": Model<"openai-completions"> & {
		id: "aion-labs/aion-rp-llama-3.1-8b";
		provider: "kilo";
	};
	"alfredpros/codellama-7b-instruct-solidity": Model<"openai-completions"> & {
		id: "alfredpros/codellama-7b-instruct-solidity";
		provider: "kilo";
	};
	"alibaba/tongyi-deepresearch-30b-a3b": Model<"openai-completions"> & {
		id: "alibaba/tongyi-deepresearch-30b-a3b";
		provider: "kilo";
	};
	"allenai/molmo-2-8b": Model<"openai-completions"> & {
		id: "allenai/molmo-2-8b";
		provider: "kilo";
	};
	"allenai/olmo-2-0325-32b-instruct": Model<"openai-completions"> & {
		id: "allenai/olmo-2-0325-32b-instruct";
		provider: "kilo";
	};
	"allenai/olmo-3-32b-think": Model<"openai-completions"> & {
		id: "allenai/olmo-3-32b-think";
		provider: "kilo";
	};
	"allenai/olmo-3-7b-instruct": Model<"openai-completions"> & {
		id: "allenai/olmo-3-7b-instruct";
		provider: "kilo";
	};
	"allenai/olmo-3-7b-think": Model<"openai-completions"> & {
		id: "allenai/olmo-3-7b-think";
		provider: "kilo";
	};
	"allenai/olmo-3.1-32b-instruct": Model<"openai-completions"> & {
		id: "allenai/olmo-3.1-32b-instruct";
		provider: "kilo";
	};
	"allenai/olmo-3.1-32b-think": Model<"openai-completions"> & {
		id: "allenai/olmo-3.1-32b-think";
		provider: "kilo";
	};
	"alpindale/goliath-120b": Model<"openai-completions"> & {
		id: "alpindale/goliath-120b";
		provider: "kilo";
	};
	"amazon/nova-2-lite-v1": Model<"openai-completions"> & {
		id: "amazon/nova-2-lite-v1";
		provider: "kilo";
	};
	"amazon/nova-lite-v1": Model<"openai-completions"> & {
		id: "amazon/nova-lite-v1";
		provider: "kilo";
	};
	"amazon/nova-micro-v1": Model<"openai-completions"> & {
		id: "amazon/nova-micro-v1";
		provider: "kilo";
	};
	"amazon/nova-premier-v1": Model<"openai-completions"> & {
		id: "amazon/nova-premier-v1";
		provider: "kilo";
	};
	"amazon/nova-pro-v1": Model<"openai-completions"> & {
		id: "amazon/nova-pro-v1";
		provider: "kilo";
	};
	"anthracite-org/magnum-v4-72b": Model<"openai-completions"> & {
		id: "anthracite-org/magnum-v4-72b";
		provider: "kilo";
	};
	"anthropic/claude-3-haiku": Model<"openai-completions"> & {
		id: "anthropic/claude-3-haiku";
		provider: "kilo";
	};
	"anthropic/claude-3.5-haiku": Model<"openai-completions"> & {
		id: "anthropic/claude-3.5-haiku";
		provider: "kilo";
	};
	"anthropic/claude-3.5-sonnet": Model<"openai-completions"> & {
		id: "anthropic/claude-3.5-sonnet";
		provider: "kilo";
	};
	"anthropic/claude-3.7-sonnet": Model<"openai-completions"> & {
		id: "anthropic/claude-3.7-sonnet";
		provider: "kilo";
	};
	"anthropic/claude-3.7-sonnet:thinking": Model<"openai-completions"> & {
		id: "anthropic/claude-3.7-sonnet:thinking";
		provider: "kilo";
	};
	"anthropic/claude-fable-5": Model<"openai-completions"> & {
		id: "anthropic/claude-fable-5";
		provider: "kilo";
	};
	"anthropic/claude-haiku-4.5": Model<"openai-completions"> & {
		id: "anthropic/claude-haiku-4.5";
		provider: "kilo";
	};
	"anthropic/claude-opus-4": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-4";
		provider: "kilo";
	};
	"anthropic/claude-opus-4.1": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-4.1";
		provider: "kilo";
	};
	"anthropic/claude-opus-4.5": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-4.5";
		provider: "kilo";
	};
	"anthropic/claude-opus-4.6": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-4.6";
		provider: "kilo";
	};
	"anthropic/claude-opus-4.6-fast": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-4.6-fast";
		provider: "kilo";
	};
	"anthropic/claude-opus-4.7": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-4.7";
		provider: "kilo";
	};
	"anthropic/claude-opus-4.7-fast": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-4.7-fast";
		provider: "kilo";
	};
	"anthropic/claude-opus-4.8": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-4.8";
		provider: "kilo";
	};
	"anthropic/claude-opus-4.8-fast": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-4.8-fast";
		provider: "kilo";
	};
	"anthropic/claude-opus-5": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-5";
		provider: "kilo";
	};
	"anthropic/claude-opus-5-fast": Model<"openai-completions"> & {
		id: "anthropic/claude-opus-5-fast";
		provider: "kilo";
	};
	"anthropic/claude-sonnet-4": Model<"openai-completions"> & {
		id: "anthropic/claude-sonnet-4";
		provider: "kilo";
	};
	"anthropic/claude-sonnet-4.5": Model<"openai-completions"> & {
		id: "anthropic/claude-sonnet-4.5";
		provider: "kilo";
	};
	"anthropic/claude-sonnet-4.6": Model<"openai-completions"> & {
		id: "anthropic/claude-sonnet-4.6";
		provider: "kilo";
	};
	"anthropic/claude-sonnet-5": Model<"openai-completions"> & {
		id: "anthropic/claude-sonnet-5";
		provider: "kilo";
	};
	"arcee-ai/coder-large": Model<"openai-completions"> & {
		id: "arcee-ai/coder-large";
		provider: "kilo";
	};
	"arcee-ai/maestro-reasoning": Model<"openai-completions"> & {
		id: "arcee-ai/maestro-reasoning";
		provider: "kilo";
	};
	"arcee-ai/spotlight": Model<"openai-completions"> & {
		id: "arcee-ai/spotlight";
		provider: "kilo";
	};
	"arcee-ai/trinity-large-preview": Model<"openai-completions"> & {
		id: "arcee-ai/trinity-large-preview";
		provider: "kilo";
	};
	"arcee-ai/trinity-large-preview:free": Model<"openai-completions"> & {
		id: "arcee-ai/trinity-large-preview:free";
		provider: "kilo";
	};
	"arcee-ai/trinity-large-thinking": Model<"openai-completions"> & {
		id: "arcee-ai/trinity-large-thinking";
		provider: "kilo";
	};
	"arcee-ai/trinity-large-thinking:free": Model<"openai-completions"> & {
		id: "arcee-ai/trinity-large-thinking:free";
		provider: "kilo";
	};
	"arcee-ai/trinity-mini": Model<"openai-completions"> & {
		id: "arcee-ai/trinity-mini";
		provider: "kilo";
	};
	"arcee-ai/virtuoso-large": Model<"openai-completions"> & {
		id: "arcee-ai/virtuoso-large";
		provider: "kilo";
	};
	"baidu/cobuddy:free": Model<"openai-completions"> & {
		id: "baidu/cobuddy:free";
		provider: "kilo";
	};
	"baidu/ernie-4.5-21b-a3b": Model<"openai-completions"> & {
		id: "baidu/ernie-4.5-21b-a3b";
		provider: "kilo";
	};
	"baidu/ernie-4.5-300b-a47b": Model<"openai-completions"> & {
		id: "baidu/ernie-4.5-300b-a47b";
		provider: "kilo";
	};
	"baidu/ernie-4.5-vl-28b-a3b": Model<"openai-completions"> & {
		id: "baidu/ernie-4.5-vl-28b-a3b";
		provider: "kilo";
	};
	"baidu/ernie-4.5-vl-424b-a47b": Model<"openai-completions"> & {
		id: "baidu/ernie-4.5-vl-424b-a47b";
		provider: "kilo";
	};
	"baidu/qianfan-ocr-fast": Model<"openai-completions"> & {
		id: "baidu/qianfan-ocr-fast";
		provider: "kilo";
	};
	"baidu/qianfan-ocr-fast:free": Model<"openai-completions"> & {
		id: "baidu/qianfan-ocr-fast:free";
		provider: "kilo";
	};
	"bytedance-seed/dola-seed-2.0-pro:free": Model<"openai-completions"> & {
		id: "bytedance-seed/dola-seed-2.0-pro:free";
		provider: "kilo";
	};
	"bytedance-seed/seed-1.6": Model<"openai-completions"> & {
		id: "bytedance-seed/seed-1.6";
		provider: "kilo";
	};
	"bytedance-seed/seed-1.6-flash": Model<"openai-completions"> & {
		id: "bytedance-seed/seed-1.6-flash";
		provider: "kilo";
	};
	"bytedance-seed/seed-2.0-lite": Model<"openai-completions"> & {
		id: "bytedance-seed/seed-2.0-lite";
		provider: "kilo";
	};
	"bytedance-seed/seed-2.0-mini": Model<"openai-completions"> & {
		id: "bytedance-seed/seed-2.0-mini";
		provider: "kilo";
	};
	"bytedance/ui-tars-1.5-7b": Model<"openai-completions"> & {
		id: "bytedance/ui-tars-1.5-7b";
		provider: "kilo";
	};
	"cognitivecomputations/dolphin-mistral-24b-venice-edition": Model<"openai-completions"> & {
		id: "cognitivecomputations/dolphin-mistral-24b-venice-edition";
		provider: "kilo";
	};
	"cohere/command-a": Model<"openai-completions"> & {
		id: "cohere/command-a";
		provider: "kilo";
	};
	"cohere/command-r-08-2024": Model<"openai-completions"> & {
		id: "cohere/command-r-08-2024";
		provider: "kilo";
	};
	"cohere/command-r-plus-08-2024": Model<"openai-completions"> & {
		id: "cohere/command-r-plus-08-2024";
		provider: "kilo";
	};
	"cohere/command-r7b-12-2024": Model<"openai-completions"> & {
		id: "cohere/command-r7b-12-2024";
		provider: "kilo";
	};
	"cohere/north-mini-code:free": Model<"openai-completions"> & {
		id: "cohere/north-mini-code:free";
		provider: "kilo";
	};
	"corethink:free": Model<"openai-completions"> & {
		id: "corethink:free";
		provider: "kilo";
	};
	"deepcogito/cogito-v2.1-671b": Model<"openai-completions"> & {
		id: "deepcogito/cogito-v2.1-671b";
		provider: "kilo";
	};
	"deepseek/deepseek-chat": Model<"openai-completions"> & {
		id: "deepseek/deepseek-chat";
		provider: "kilo";
	};
	"deepseek/deepseek-chat-v3-0324": Model<"openai-completions"> & {
		id: "deepseek/deepseek-chat-v3-0324";
		provider: "kilo";
	};
	"deepseek/deepseek-chat-v3.1": Model<"openai-completions"> & {
		id: "deepseek/deepseek-chat-v3.1";
		provider: "kilo";
	};
	"deepseek/deepseek-r1": Model<"openai-completions"> & {
		id: "deepseek/deepseek-r1";
		provider: "kilo";
	};
	"deepseek/deepseek-r1-0528": Model<"openai-completions"> & {
		id: "deepseek/deepseek-r1-0528";
		provider: "kilo";
	};
	"deepseek/deepseek-r1-distill-llama-70b": Model<"openai-completions"> & {
		id: "deepseek/deepseek-r1-distill-llama-70b";
		provider: "kilo";
	};
	"deepseek/deepseek-r1-distill-qwen-32b": Model<"openai-completions"> & {
		id: "deepseek/deepseek-r1-distill-qwen-32b";
		provider: "kilo";
	};
	"deepseek/deepseek-v3.1-terminus": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3.1-terminus";
		provider: "kilo";
	};
	"deepseek/deepseek-v3.1-terminus:exacto": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3.1-terminus:exacto";
		provider: "kilo";
	};
	"deepseek/deepseek-v3.2": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3.2";
		provider: "kilo";
	};
	"deepseek/deepseek-v3.2-exp": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3.2-exp";
		provider: "kilo";
	};
	"deepseek/deepseek-v3.2-speciale": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3.2-speciale";
		provider: "kilo";
	};
	"deepseek/deepseek-v4-flash": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-flash";
		provider: "kilo";
	};
	"deepseek/deepseek-v4-flash-0731": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-flash-0731";
		provider: "kilo";
	};
	"deepseek/deepseek-v4-flash:discounted": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-flash:discounted";
		provider: "kilo";
	};
	"deepseek/deepseek-v4-flash:free": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-flash:free";
		provider: "kilo";
	};
	"deepseek/deepseek-v4-pro": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-pro";
		provider: "kilo";
	};
	"deepseek/deepseek-v4-pro:discounted": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-pro:discounted";
		provider: "kilo";
	};
	"eleutherai/llemma_7b": Model<"openai-completions"> & {
		id: "eleutherai/llemma_7b";
		provider: "kilo";
	};
	"essentialai/rnj-1-instruct": Model<"openai-completions"> & {
		id: "essentialai/rnj-1-instruct";
		provider: "kilo";
	};
	"giga-potato": Model<"openai-completions"> & {
		id: "giga-potato";
		provider: "kilo";
	};
	"google/gemini-2.0-flash-001": Model<"openai-completions"> & {
		id: "google/gemini-2.0-flash-001";
		provider: "kilo";
	};
	"google/gemini-2.0-flash-lite-001": Model<"openai-completions"> & {
		id: "google/gemini-2.0-flash-lite-001";
		provider: "kilo";
	};
	"google/gemini-2.5-flash": Model<"openai-completions"> & {
		id: "google/gemini-2.5-flash";
		provider: "kilo";
	};
	"google/gemini-2.5-flash-image": Model<"openai-completions"> & {
		id: "google/gemini-2.5-flash-image";
		provider: "kilo";
	};
	"google/gemini-2.5-flash-lite": Model<"openai-completions"> & {
		id: "google/gemini-2.5-flash-lite";
		provider: "kilo";
	};
	"google/gemini-2.5-flash-lite-preview-09-2025": Model<"openai-completions"> & {
		id: "google/gemini-2.5-flash-lite-preview-09-2025";
		provider: "kilo";
	};
	"google/gemini-2.5-pro": Model<"openai-completions"> & {
		id: "google/gemini-2.5-pro";
		provider: "kilo";
	};
	"google/gemini-2.5-pro-preview": Model<"openai-completions"> & {
		id: "google/gemini-2.5-pro-preview";
		provider: "kilo";
	};
	"google/gemini-2.5-pro-preview-05-06": Model<"openai-completions"> & {
		id: "google/gemini-2.5-pro-preview-05-06";
		provider: "kilo";
	};
	"google/gemini-3-flash-preview": Model<"openai-completions"> & {
		id: "google/gemini-3-flash-preview";
		provider: "kilo";
	};
	"google/gemini-3-pro-image": Model<"openai-completions"> & {
		id: "google/gemini-3-pro-image";
		provider: "kilo";
	};
	"google/gemini-3-pro-image-preview": Model<"openai-completions"> & {
		id: "google/gemini-3-pro-image-preview";
		provider: "kilo";
	};
	"google/gemini-3-pro-preview": Model<"openai-completions"> & {
		id: "google/gemini-3-pro-preview";
		provider: "kilo";
	};
	"google/gemini-3.1-flash-image": Model<"openai-completions"> & {
		id: "google/gemini-3.1-flash-image";
		provider: "kilo";
	};
	"google/gemini-3.1-flash-image-preview": Model<"openai-completions"> & {
		id: "google/gemini-3.1-flash-image-preview";
		provider: "kilo";
	};
	"google/gemini-3.1-flash-lite": Model<"openai-completions"> & {
		id: "google/gemini-3.1-flash-lite";
		provider: "kilo";
	};
	"google/gemini-3.1-flash-lite-image": Model<"openai-completions"> & {
		id: "google/gemini-3.1-flash-lite-image";
		provider: "kilo";
	};
	"google/gemini-3.1-flash-lite-preview": Model<"openai-completions"> & {
		id: "google/gemini-3.1-flash-lite-preview";
		provider: "kilo";
	};
	"google/gemini-3.1-pro-preview": Model<"openai-completions"> & {
		id: "google/gemini-3.1-pro-preview";
		provider: "kilo";
	};
	"google/gemini-3.1-pro-preview-customtools": Model<"openai-completions"> & {
		id: "google/gemini-3.1-pro-preview-customtools";
		provider: "kilo";
	};
	"google/gemini-3.5-flash": Model<"openai-completions"> & {
		id: "google/gemini-3.5-flash";
		provider: "kilo";
	};
	"google/gemini-3.5-flash-lite": Model<"openai-completions"> & {
		id: "google/gemini-3.5-flash-lite";
		provider: "kilo";
	};
	"google/gemini-3.6-flash": Model<"openai-completions"> & {
		id: "google/gemini-3.6-flash";
		provider: "kilo";
	};
	"google/gemma-2-27b-it": Model<"openai-completions"> & {
		id: "google/gemma-2-27b-it";
		provider: "kilo";
	};
	"google/gemma-2-9b-it": Model<"openai-completions"> & {
		id: "google/gemma-2-9b-it";
		provider: "kilo";
	};
	"google/gemma-3-12b-it": Model<"openai-completions"> & {
		id: "google/gemma-3-12b-it";
		provider: "kilo";
	};
	"google/gemma-3-27b-it": Model<"openai-completions"> & {
		id: "google/gemma-3-27b-it";
		provider: "kilo";
	};
	"google/gemma-3-4b-it": Model<"openai-completions"> & {
		id: "google/gemma-3-4b-it";
		provider: "kilo";
	};
	"google/gemma-3n-e4b-it": Model<"openai-completions"> & {
		id: "google/gemma-3n-e4b-it";
		provider: "kilo";
	};
	"google/gemma-4-26b-a4b-it": Model<"openai-completions"> & {
		id: "google/gemma-4-26b-a4b-it";
		provider: "kilo";
	};
	"google/gemma-4-31b-it": Model<"openai-completions"> & {
		id: "google/gemma-4-31b-it";
		provider: "kilo";
	};
	"google/lyria-3-clip-preview": Model<"openai-completions"> & {
		id: "google/lyria-3-clip-preview";
		provider: "kilo";
	};
	"google/lyria-3-pro-preview": Model<"openai-completions"> & {
		id: "google/lyria-3-pro-preview";
		provider: "kilo";
	};
	"gryphe/mythomax-l2-13b": Model<"openai-completions"> & {
		id: "gryphe/mythomax-l2-13b";
		provider: "kilo";
	};
	"ibm-granite/granite-4.0-h-micro": Model<"openai-completions"> & {
		id: "ibm-granite/granite-4.0-h-micro";
		provider: "kilo";
	};
	"ibm-granite/granite-4.1-8b": Model<"openai-completions"> & {
		id: "ibm-granite/granite-4.1-8b";
		provider: "kilo";
	};
	"inception/mercury": Model<"openai-completions"> & {
		id: "inception/mercury";
		provider: "kilo";
	};
	"inception/mercury-2": Model<"openai-completions"> & {
		id: "inception/mercury-2";
		provider: "kilo";
	};
	"inception/mercury-coder": Model<"openai-completions"> & {
		id: "inception/mercury-coder";
		provider: "kilo";
	};
	"inclusionai/ling-2.6-1t": Model<"openai-completions"> & {
		id: "inclusionai/ling-2.6-1t";
		provider: "kilo";
	};
	"inclusionai/ling-2.6-1t:free": Model<"openai-completions"> & {
		id: "inclusionai/ling-2.6-1t:free";
		provider: "kilo";
	};
	"inclusionai/ling-2.6-flash": Model<"openai-completions"> & {
		id: "inclusionai/ling-2.6-flash";
		provider: "kilo";
	};
	"inclusionai/ling-2.6-flash:free": Model<"openai-completions"> & {
		id: "inclusionai/ling-2.6-flash:free";
		provider: "kilo";
	};
	"inclusionai/ling-3.0-flash": Model<"openai-completions"> & {
		id: "inclusionai/ling-3.0-flash";
		provider: "kilo";
	};
	"inclusionai/ling-3.0-flash:free": Model<"openai-completions"> & {
		id: "inclusionai/ling-3.0-flash:free";
		provider: "kilo";
	};
	"inclusionai/ling-3.0-tiny:free": Model<"openai-completions"> & {
		id: "inclusionai/ling-3.0-tiny:free";
		provider: "kilo";
	};
	"inclusionai/ring-2.6-1t": Model<"openai-completions"> & {
		id: "inclusionai/ring-2.6-1t";
		provider: "kilo";
	};
	"inclusionai/ring-2.6-1t:free": Model<"openai-completions"> & {
		id: "inclusionai/ring-2.6-1t:free";
		provider: "kilo";
	};
	"inflection/inflection-3-pi": Model<"openai-completions"> & {
		id: "inflection/inflection-3-pi";
		provider: "kilo";
	};
	"inflection/inflection-3-productivity": Model<"openai-completions"> & {
		id: "inflection/inflection-3-productivity";
		provider: "kilo";
	};
	"kilo-auto/balanced": Model<"openai-completions"> & {
		id: "kilo-auto/balanced";
		provider: "kilo";
	};
	"kilo-auto/efficient": Model<"openai-completions"> & {
		id: "kilo-auto/efficient";
		provider: "kilo";
	};
	"kilo-auto/free": Model<"openai-completions"> & {
		id: "kilo-auto/free";
		provider: "kilo";
	};
	"kilo-auto/frontier": Model<"openai-completions"> & {
		id: "kilo-auto/frontier";
		provider: "kilo";
	};
	"kilo-auto/small": Model<"openai-completions"> & {
		id: "kilo-auto/small";
		provider: "kilo";
	};
	"kilo/auto": Model<"openai-completions"> & {
		id: "kilo/auto";
		provider: "kilo";
	};
	"kilo/auto-free": Model<"openai-completions"> & {
		id: "kilo/auto-free";
		provider: "kilo";
	};
	"kilo/auto-small": Model<"openai-completions"> & {
		id: "kilo/auto-small";
		provider: "kilo";
	};
	"kwaipilot/kat-coder-air-v2.5": Model<"openai-completions"> & {
		id: "kwaipilot/kat-coder-air-v2.5";
		provider: "kilo";
	};
	"kwaipilot/kat-coder-pro": Model<"openai-completions"> & {
		id: "kwaipilot/kat-coder-pro";
		provider: "kilo";
	};
	"kwaipilot/kat-coder-pro-v2": Model<"openai-completions"> & {
		id: "kwaipilot/kat-coder-pro-v2";
		provider: "kilo";
	};
	"kwaipilot/kat-coder-pro-v2.5": Model<"openai-completions"> & {
		id: "kwaipilot/kat-coder-pro-v2.5";
		provider: "kilo";
	};
	"kwaipilot/kat-coder-pro-v2.5:free": Model<"openai-completions"> & {
		id: "kwaipilot/kat-coder-pro-v2.5:free";
		provider: "kilo";
	};
	"liquid/lfm-2-24b-a2b": Model<"openai-completions"> & {
		id: "liquid/lfm-2-24b-a2b";
		provider: "kilo";
	};
	"liquid/lfm-2.2-6b": Model<"openai-completions"> & {
		id: "liquid/lfm-2.2-6b";
		provider: "kilo";
	};
	"liquid/lfm2-8b-a1b": Model<"openai-completions"> & {
		id: "liquid/lfm2-8b-a1b";
		provider: "kilo";
	};
	"mancer/weaver": Model<"openai-completions"> & {
		id: "mancer/weaver";
		provider: "kilo";
	};
	"meituan/longcat-2.0": Model<"openai-completions"> & {
		id: "meituan/longcat-2.0";
		provider: "kilo";
	};
	"meituan/longcat-flash-chat": Model<"openai-completions"> & {
		id: "meituan/longcat-flash-chat";
		provider: "kilo";
	};
	"meta-llama/llama-3-70b-instruct": Model<"openai-completions"> & {
		id: "meta-llama/llama-3-70b-instruct";
		provider: "kilo";
	};
	"meta-llama/llama-3-8b-instruct": Model<"openai-completions"> & {
		id: "meta-llama/llama-3-8b-instruct";
		provider: "kilo";
	};
	"meta-llama/llama-3.1-405b": Model<"openai-completions"> & {
		id: "meta-llama/llama-3.1-405b";
		provider: "kilo";
	};
	"meta-llama/llama-3.1-405b-instruct": Model<"openai-completions"> & {
		id: "meta-llama/llama-3.1-405b-instruct";
		provider: "kilo";
	};
	"meta-llama/llama-3.1-70b-instruct": Model<"openai-completions"> & {
		id: "meta-llama/llama-3.1-70b-instruct";
		provider: "kilo";
	};
	"meta-llama/llama-3.1-8b-instruct": Model<"openai-completions"> & {
		id: "meta-llama/llama-3.1-8b-instruct";
		provider: "kilo";
	};
	"meta-llama/llama-3.2-11b-vision-instruct": Model<"openai-completions"> & {
		id: "meta-llama/llama-3.2-11b-vision-instruct";
		provider: "kilo";
	};
	"meta-llama/llama-3.2-1b-instruct": Model<"openai-completions"> & {
		id: "meta-llama/llama-3.2-1b-instruct";
		provider: "kilo";
	};
	"meta-llama/llama-3.2-3b-instruct": Model<"openai-completions"> & {
		id: "meta-llama/llama-3.2-3b-instruct";
		provider: "kilo";
	};
	"meta-llama/llama-3.3-70b-instruct": Model<"openai-completions"> & {
		id: "meta-llama/llama-3.3-70b-instruct";
		provider: "kilo";
	};
	"meta-llama/llama-4-maverick": Model<"openai-completions"> & {
		id: "meta-llama/llama-4-maverick";
		provider: "kilo";
	};
	"meta-llama/llama-4-scout": Model<"openai-completions"> & {
		id: "meta-llama/llama-4-scout";
		provider: "kilo";
	};
	"meta-llama/llama-guard-2-8b": Model<"openai-completions"> & {
		id: "meta-llama/llama-guard-2-8b";
		provider: "kilo";
	};
	"meta-llama/llama-guard-3-8b": Model<"openai-completions"> & {
		id: "meta-llama/llama-guard-3-8b";
		provider: "kilo";
	};
	"meta-llama/llama-guard-4-12b": Model<"openai-completions"> & {
		id: "meta-llama/llama-guard-4-12b";
		provider: "kilo";
	};
	"meta-llama/llama-guard-4-12b:free": Model<"openai-completions"> & {
		id: "meta-llama/llama-guard-4-12b:free";
		provider: "kilo";
	};
	"meta/muse-spark-1.1": Model<"openai-completions"> & {
		id: "meta/muse-spark-1.1";
		provider: "kilo";
	};
	"meta/muse-spark-1.2": Model<"openai-completions"> & {
		id: "meta/muse-spark-1.2";
		provider: "kilo";
	};
	"microsoft/phi-4": Model<"openai-completions"> & {
		id: "microsoft/phi-4";
		provider: "kilo";
	};
	"microsoft/phi-4-mini-instruct": Model<"openai-completions"> & {
		id: "microsoft/phi-4-mini-instruct";
		provider: "kilo";
	};
	"microsoft/wizardlm-2-8x22b": Model<"openai-completions"> & {
		id: "microsoft/wizardlm-2-8x22b";
		provider: "kilo";
	};
	"minimax/minimax-01": Model<"openai-completions"> & {
		id: "minimax/minimax-01";
		provider: "kilo";
	};
	"minimax/minimax-m1": Model<"openai-completions"> & {
		id: "minimax/minimax-m1";
		provider: "kilo";
	};
	"minimax/minimax-m2": Model<"openai-completions"> & {
		id: "minimax/minimax-m2";
		provider: "kilo";
	};
	"minimax/minimax-m2-her": Model<"openai-completions"> & {
		id: "minimax/minimax-m2-her";
		provider: "kilo";
	};
	"minimax/minimax-m2.1": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.1";
		provider: "kilo";
	};
	"minimax/minimax-m2.5": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.5";
		provider: "kilo";
	};
	"minimax/minimax-m2.5:free": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.5:free";
		provider: "kilo";
	};
	"minimax/minimax-m2.7": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.7";
		provider: "kilo";
	};
	"minimax/minimax-m3": Model<"openai-completions"> & {
		id: "minimax/minimax-m3";
		provider: "kilo";
	};
	"minimax/minimax-m3:discounted": Model<"openai-completions"> & {
		id: "minimax/minimax-m3:discounted";
		provider: "kilo";
	};
	"mistralai/codestral-2508": Model<"openai-completions"> & {
		id: "mistralai/codestral-2508";
		provider: "kilo";
	};
	"mistralai/devstral-2512": Model<"openai-completions"> & {
		id: "mistralai/devstral-2512";
		provider: "kilo";
	};
	"mistralai/devstral-medium": Model<"openai-completions"> & {
		id: "mistralai/devstral-medium";
		provider: "kilo";
	};
	"mistralai/devstral-small": Model<"openai-completions"> & {
		id: "mistralai/devstral-small";
		provider: "kilo";
	};
	"mistralai/ministral-14b-2512": Model<"openai-completions"> & {
		id: "mistralai/ministral-14b-2512";
		provider: "kilo";
	};
	"mistralai/ministral-3b-2512": Model<"openai-completions"> & {
		id: "mistralai/ministral-3b-2512";
		provider: "kilo";
	};
	"mistralai/ministral-8b-2512": Model<"openai-completions"> & {
		id: "mistralai/ministral-8b-2512";
		provider: "kilo";
	};
	"mistralai/mistral-7b-instruct": Model<"openai-completions"> & {
		id: "mistralai/mistral-7b-instruct";
		provider: "kilo";
	};
	"mistralai/mistral-7b-instruct-v0.1": Model<"openai-completions"> & {
		id: "mistralai/mistral-7b-instruct-v0.1";
		provider: "kilo";
	};
	"mistralai/mistral-7b-instruct-v0.3": Model<"openai-completions"> & {
		id: "mistralai/mistral-7b-instruct-v0.3";
		provider: "kilo";
	};
	"mistralai/mistral-large": Model<"openai-completions"> & {
		id: "mistralai/mistral-large";
		provider: "kilo";
	};
	"mistralai/mistral-large-2407": Model<"openai-completions"> & {
		id: "mistralai/mistral-large-2407";
		provider: "kilo";
	};
	"mistralai/mistral-large-2411": Model<"openai-completions"> & {
		id: "mistralai/mistral-large-2411";
		provider: "kilo";
	};
	"mistralai/mistral-large-2512": Model<"openai-completions"> & {
		id: "mistralai/mistral-large-2512";
		provider: "kilo";
	};
	"mistralai/mistral-medium-3": Model<"openai-completions"> & {
		id: "mistralai/mistral-medium-3";
		provider: "kilo";
	};
	"mistralai/mistral-medium-3-5": Model<"openai-completions"> & {
		id: "mistralai/mistral-medium-3-5";
		provider: "kilo";
	};
	"mistralai/mistral-medium-3.1": Model<"openai-completions"> & {
		id: "mistralai/mistral-medium-3.1";
		provider: "kilo";
	};
	"mistralai/mistral-nemo": Model<"openai-completions"> & {
		id: "mistralai/mistral-nemo";
		provider: "kilo";
	};
	"mistralai/mistral-saba": Model<"openai-completions"> & {
		id: "mistralai/mistral-saba";
		provider: "kilo";
	};
	"mistralai/mistral-small-24b-instruct-2501": Model<"openai-completions"> & {
		id: "mistralai/mistral-small-24b-instruct-2501";
		provider: "kilo";
	};
	"mistralai/mistral-small-2603": Model<"openai-completions"> & {
		id: "mistralai/mistral-small-2603";
		provider: "kilo";
	};
	"mistralai/mistral-small-3.1-24b-instruct": Model<"openai-completions"> & {
		id: "mistralai/mistral-small-3.1-24b-instruct";
		provider: "kilo";
	};
	"mistralai/mistral-small-3.2-24b-instruct": Model<"openai-completions"> & {
		id: "mistralai/mistral-small-3.2-24b-instruct";
		provider: "kilo";
	};
	"mistralai/mistral-small-creative": Model<"openai-completions"> & {
		id: "mistralai/mistral-small-creative";
		provider: "kilo";
	};
	"mistralai/mixtral-8x22b-instruct": Model<"openai-completions"> & {
		id: "mistralai/mixtral-8x22b-instruct";
		provider: "kilo";
	};
	"mistralai/mixtral-8x7b-instruct": Model<"openai-completions"> & {
		id: "mistralai/mixtral-8x7b-instruct";
		provider: "kilo";
	};
	"mistralai/pixtral-large-2411": Model<"openai-completions"> & {
		id: "mistralai/pixtral-large-2411";
		provider: "kilo";
	};
	"mistralai/voxtral-small-24b-2507": Model<"openai-completions"> & {
		id: "mistralai/voxtral-small-24b-2507";
		provider: "kilo";
	};
	"moonshotai/kimi-k2": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2";
		provider: "kilo";
	};
	"moonshotai/kimi-k2-0905": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2-0905";
		provider: "kilo";
	};
	"moonshotai/kimi-k2-0905:exacto": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2-0905:exacto";
		provider: "kilo";
	};
	"moonshotai/kimi-k2-thinking": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2-thinking";
		provider: "kilo";
	};
	"moonshotai/kimi-k2.5": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.5";
		provider: "kilo";
	};
	"moonshotai/kimi-k2.5:free": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.5:free";
		provider: "kilo";
	};
	"moonshotai/kimi-k2.6": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.6";
		provider: "kilo";
	};
	"moonshotai/kimi-k2.6:free": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.6:free";
		provider: "kilo";
	};
	"moonshotai/kimi-k2.7-code": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.7-code";
		provider: "kilo";
	};
	"moonshotai/kimi-k3": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k3";
		provider: "kilo";
	};
	"morph-warp-grep-v2": Model<"openai-completions"> & {
		id: "morph-warp-grep-v2";
		provider: "kilo";
	};
	"morph/morph-v3-fast": Model<"openai-completions"> & {
		id: "morph/morph-v3-fast";
		provider: "kilo";
	};
	"morph/morph-v3-large": Model<"openai-completions"> & {
		id: "morph/morph-v3-large";
		provider: "kilo";
	};
	"neversleep/llama-3.1-lumimaid-8b": Model<"openai-completions"> & {
		id: "neversleep/llama-3.1-lumimaid-8b";
		provider: "kilo";
	};
	"neversleep/noromaid-20b": Model<"openai-completions"> & {
		id: "neversleep/noromaid-20b";
		provider: "kilo";
	};
	"nex-agi/deepseek-v3.1-nex-n1": Model<"openai-completions"> & {
		id: "nex-agi/deepseek-v3.1-nex-n1";
		provider: "kilo";
	};
	"nex-agi/nex-n2-mini": Model<"openai-completions"> & {
		id: "nex-agi/nex-n2-mini";
		provider: "kilo";
	};
	"nex-agi/nex-n2-pro": Model<"openai-completions"> & {
		id: "nex-agi/nex-n2-pro";
		provider: "kilo";
	};
	"nex-agi/nex-n2-pro:free": Model<"openai-completions"> & {
		id: "nex-agi/nex-n2-pro:free";
		provider: "kilo";
	};
	"nousresearch/hermes-2-pro-llama-3-8b": Model<"openai-completions"> & {
		id: "nousresearch/hermes-2-pro-llama-3-8b";
		provider: "kilo";
	};
	"nousresearch/hermes-3-llama-3.1-405b": Model<"openai-completions"> & {
		id: "nousresearch/hermes-3-llama-3.1-405b";
		provider: "kilo";
	};
	"nousresearch/hermes-3-llama-3.1-70b": Model<"openai-completions"> & {
		id: "nousresearch/hermes-3-llama-3.1-70b";
		provider: "kilo";
	};
	"nousresearch/hermes-4-405b": Model<"openai-completions"> & {
		id: "nousresearch/hermes-4-405b";
		provider: "kilo";
	};
	"nousresearch/hermes-4-70b": Model<"openai-completions"> & {
		id: "nousresearch/hermes-4-70b";
		provider: "kilo";
	};
	"nvidia/llama-3.1-nemotron-70b-instruct": Model<"openai-completions"> & {
		id: "nvidia/llama-3.1-nemotron-70b-instruct";
		provider: "kilo";
	};
	"nvidia/llama-3.1-nemotron-ultra-253b-v1": Model<"openai-completions"> & {
		id: "nvidia/llama-3.1-nemotron-ultra-253b-v1";
		provider: "kilo";
	};
	"nvidia/llama-3.3-nemotron-super-49b-v1.5": Model<"openai-completions"> & {
		id: "nvidia/llama-3.3-nemotron-super-49b-v1.5";
		provider: "kilo";
	};
	"nvidia/nemotron-3-nano-30b-a3b": Model<"openai-completions"> & {
		id: "nvidia/nemotron-3-nano-30b-a3b";
		provider: "kilo";
	};
	"nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free": Model<"openai-completions"> & {
		id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free";
		provider: "kilo";
	};
	"nvidia/nemotron-3-super-120b-a12b": Model<"openai-completions"> & {
		id: "nvidia/nemotron-3-super-120b-a12b";
		provider: "kilo";
	};
	"nvidia/nemotron-3-super-120b-a12b:free": Model<"openai-completions"> & {
		id: "nvidia/nemotron-3-super-120b-a12b:free";
		provider: "kilo";
	};
	"nvidia/nemotron-3-ultra-550b-a55b": Model<"openai-completions"> & {
		id: "nvidia/nemotron-3-ultra-550b-a55b";
		provider: "kilo";
	};
	"nvidia/nemotron-3-ultra-550b-a55b:free": Model<"openai-completions"> & {
		id: "nvidia/nemotron-3-ultra-550b-a55b:free";
		provider: "kilo";
	};
	"nvidia/nemotron-3.5-content-safety:free": Model<"openai-completions"> & {
		id: "nvidia/nemotron-3.5-content-safety:free";
		provider: "kilo";
	};
	"nvidia/nemotron-nano-12b-v2-vl": Model<"openai-completions"> & {
		id: "nvidia/nemotron-nano-12b-v2-vl";
		provider: "kilo";
	};
	"nvidia/nemotron-nano-9b-v2": Model<"openai-completions"> & {
		id: "nvidia/nemotron-nano-9b-v2";
		provider: "kilo";
	};
	"openai/gpt-3.5-turbo": Model<"openai-completions"> & {
		id: "openai/gpt-3.5-turbo";
		provider: "kilo";
	};
	"openai/gpt-3.5-turbo-0613": Model<"openai-completions"> & {
		id: "openai/gpt-3.5-turbo-0613";
		provider: "kilo";
	};
	"openai/gpt-3.5-turbo-16k": Model<"openai-completions"> & {
		id: "openai/gpt-3.5-turbo-16k";
		provider: "kilo";
	};
	"openai/gpt-3.5-turbo-instruct": Model<"openai-completions"> & {
		id: "openai/gpt-3.5-turbo-instruct";
		provider: "kilo";
	};
	"openai/gpt-4": Model<"openai-completions"> & {
		id: "openai/gpt-4";
		provider: "kilo";
	};
	"openai/gpt-4-0314": Model<"openai-completions"> & {
		id: "openai/gpt-4-0314";
		provider: "kilo";
	};
	"openai/gpt-4-1106-preview": Model<"openai-completions"> & {
		id: "openai/gpt-4-1106-preview";
		provider: "kilo";
	};
	"openai/gpt-4-turbo": Model<"openai-completions"> & {
		id: "openai/gpt-4-turbo";
		provider: "kilo";
	};
	"openai/gpt-4-turbo-preview": Model<"openai-completions"> & {
		id: "openai/gpt-4-turbo-preview";
		provider: "kilo";
	};
	"openai/gpt-4.1": Model<"openai-completions"> & {
		id: "openai/gpt-4.1";
		provider: "kilo";
	};
	"openai/gpt-4.1-mini": Model<"openai-completions"> & {
		id: "openai/gpt-4.1-mini";
		provider: "kilo";
	};
	"openai/gpt-4.1-nano": Model<"openai-completions"> & {
		id: "openai/gpt-4.1-nano";
		provider: "kilo";
	};
	"openai/gpt-4o": Model<"openai-completions"> & {
		id: "openai/gpt-4o";
		provider: "kilo";
	};
	"openai/gpt-4o-2024-05-13": Model<"openai-completions"> & {
		id: "openai/gpt-4o-2024-05-13";
		provider: "kilo";
	};
	"openai/gpt-4o-2024-08-06": Model<"openai-completions"> & {
		id: "openai/gpt-4o-2024-08-06";
		provider: "kilo";
	};
	"openai/gpt-4o-2024-11-20": Model<"openai-completions"> & {
		id: "openai/gpt-4o-2024-11-20";
		provider: "kilo";
	};
	"openai/gpt-4o-audio-preview": Model<"openai-completions"> & {
		id: "openai/gpt-4o-audio-preview";
		provider: "kilo";
	};
	"openai/gpt-4o-mini": Model<"openai-completions"> & {
		id: "openai/gpt-4o-mini";
		provider: "kilo";
	};
	"openai/gpt-4o-mini-2024-07-18": Model<"openai-completions"> & {
		id: "openai/gpt-4o-mini-2024-07-18";
		provider: "kilo";
	};
	"openai/gpt-4o-mini-search-preview": Model<"openai-completions"> & {
		id: "openai/gpt-4o-mini-search-preview";
		provider: "kilo";
	};
	"openai/gpt-4o-search-preview": Model<"openai-completions"> & {
		id: "openai/gpt-4o-search-preview";
		provider: "kilo";
	};
	"openai/gpt-4o:extended": Model<"openai-completions"> & {
		id: "openai/gpt-4o:extended";
		provider: "kilo";
	};
	"openai/gpt-5": Model<"openai-completions"> & {
		id: "openai/gpt-5";
		provider: "kilo";
	};
	"openai/gpt-5-chat": Model<"openai-completions"> & {
		id: "openai/gpt-5-chat";
		provider: "kilo";
	};
	"openai/gpt-5-codex": Model<"openai-completions"> & {
		id: "openai/gpt-5-codex";
		provider: "kilo";
	};
	"openai/gpt-5-image": Model<"openai-completions"> & {
		id: "openai/gpt-5-image";
		provider: "kilo";
	};
	"openai/gpt-5-image-mini": Model<"openai-completions"> & {
		id: "openai/gpt-5-image-mini";
		provider: "kilo";
	};
	"openai/gpt-5-mini": Model<"openai-completions"> & {
		id: "openai/gpt-5-mini";
		provider: "kilo";
	};
	"openai/gpt-5-nano": Model<"openai-completions"> & {
		id: "openai/gpt-5-nano";
		provider: "kilo";
	};
	"openai/gpt-5-pro": Model<"openai-completions"> & {
		id: "openai/gpt-5-pro";
		provider: "kilo";
	};
	"openai/gpt-5.1": Model<"openai-completions"> & {
		id: "openai/gpt-5.1";
		provider: "kilo";
	};
	"openai/gpt-5.1-chat": Model<"openai-completions"> & {
		id: "openai/gpt-5.1-chat";
		provider: "kilo";
	};
	"openai/gpt-5.1-codex": Model<"openai-completions"> & {
		id: "openai/gpt-5.1-codex";
		provider: "kilo";
	};
	"openai/gpt-5.1-codex-max": Model<"openai-completions"> & {
		id: "openai/gpt-5.1-codex-max";
		provider: "kilo";
	};
	"openai/gpt-5.1-codex-mini": Model<"openai-completions"> & {
		id: "openai/gpt-5.1-codex-mini";
		provider: "kilo";
	};
	"openai/gpt-5.2": Model<"openai-completions"> & {
		id: "openai/gpt-5.2";
		provider: "kilo";
	};
	"openai/gpt-5.2-chat": Model<"openai-completions"> & {
		id: "openai/gpt-5.2-chat";
		provider: "kilo";
	};
	"openai/gpt-5.2-codex": Model<"openai-completions"> & {
		id: "openai/gpt-5.2-codex";
		provider: "kilo";
	};
	"openai/gpt-5.2-pro": Model<"openai-completions"> & {
		id: "openai/gpt-5.2-pro";
		provider: "kilo";
	};
	"openai/gpt-5.3-chat": Model<"openai-completions"> & {
		id: "openai/gpt-5.3-chat";
		provider: "kilo";
	};
	"openai/gpt-5.3-codex": Model<"openai-completions"> & {
		id: "openai/gpt-5.3-codex";
		provider: "kilo";
	};
	"openai/gpt-5.4": Model<"openai-completions"> & {
		id: "openai/gpt-5.4";
		provider: "kilo";
	};
	"openai/gpt-5.4-image-2": Model<"openai-completions"> & {
		id: "openai/gpt-5.4-image-2";
		provider: "kilo";
	};
	"openai/gpt-5.4-mini": Model<"openai-completions"> & {
		id: "openai/gpt-5.4-mini";
		provider: "kilo";
	};
	"openai/gpt-5.4-nano": Model<"openai-completions"> & {
		id: "openai/gpt-5.4-nano";
		provider: "kilo";
	};
	"openai/gpt-5.4-pro": Model<"openai-completions"> & {
		id: "openai/gpt-5.4-pro";
		provider: "kilo";
	};
	"openai/gpt-5.5": Model<"openai-completions"> & {
		id: "openai/gpt-5.5";
		provider: "kilo";
	};
	"openai/gpt-5.5-pro": Model<"openai-completions"> & {
		id: "openai/gpt-5.5-pro";
		provider: "kilo";
	};
	"openai/gpt-5.6-luna": Model<"openai-completions"> & {
		id: "openai/gpt-5.6-luna";
		provider: "kilo";
	};
	"openai/gpt-5.6-luna-pro": Model<"openai-completions"> & {
		id: "openai/gpt-5.6-luna-pro";
		provider: "kilo";
	};
	"openai/gpt-5.6-sol": Model<"openai-completions"> & {
		id: "openai/gpt-5.6-sol";
		provider: "kilo";
	};
	"openai/gpt-5.6-sol-pro": Model<"openai-completions"> & {
		id: "openai/gpt-5.6-sol-pro";
		provider: "kilo";
	};
	"openai/gpt-5.6-terra": Model<"openai-completions"> & {
		id: "openai/gpt-5.6-terra";
		provider: "kilo";
	};
	"openai/gpt-5.6-terra-pro": Model<"openai-completions"> & {
		id: "openai/gpt-5.6-terra-pro";
		provider: "kilo";
	};
	"openai/gpt-audio": Model<"openai-completions"> & {
		id: "openai/gpt-audio";
		provider: "kilo";
	};
	"openai/gpt-audio-mini": Model<"openai-completions"> & {
		id: "openai/gpt-audio-mini";
		provider: "kilo";
	};
	"openai/gpt-chat-latest": Model<"openai-completions"> & {
		id: "openai/gpt-chat-latest";
		provider: "kilo";
	};
	"openai/gpt-oss-120b": Model<"openai-completions"> & {
		id: "openai/gpt-oss-120b";
		provider: "kilo";
	};
	"openai/gpt-oss-120b:exacto": Model<"openai-completions"> & {
		id: "openai/gpt-oss-120b:exacto";
		provider: "kilo";
	};
	"openai/gpt-oss-20b": Model<"openai-completions"> & {
		id: "openai/gpt-oss-20b";
		provider: "kilo";
	};
	"openai/gpt-oss-safeguard-20b": Model<"openai-completions"> & {
		id: "openai/gpt-oss-safeguard-20b";
		provider: "kilo";
	};
	"openai/o1": Model<"openai-completions"> & {
		id: "openai/o1";
		provider: "kilo";
	};
	"openai/o1-pro": Model<"openai-completions"> & {
		id: "openai/o1-pro";
		provider: "kilo";
	};
	"openai/o3": Model<"openai-completions"> & {
		id: "openai/o3";
		provider: "kilo";
	};
	"openai/o3-deep-research": Model<"openai-completions"> & {
		id: "openai/o3-deep-research";
		provider: "kilo";
	};
	"openai/o3-mini": Model<"openai-completions"> & {
		id: "openai/o3-mini";
		provider: "kilo";
	};
	"openai/o3-mini-high": Model<"openai-completions"> & {
		id: "openai/o3-mini-high";
		provider: "kilo";
	};
	"openai/o3-pro": Model<"openai-completions"> & {
		id: "openai/o3-pro";
		provider: "kilo";
	};
	"openai/o4-mini": Model<"openai-completions"> & {
		id: "openai/o4-mini";
		provider: "kilo";
	};
	"openai/o4-mini-deep-research": Model<"openai-completions"> & {
		id: "openai/o4-mini-deep-research";
		provider: "kilo";
	};
	"openai/o4-mini-high": Model<"openai-completions"> & {
		id: "openai/o4-mini-high";
		provider: "kilo";
	};
	"opengvlab/internvl3-78b": Model<"openai-completions"> & {
		id: "opengvlab/internvl3-78b";
		provider: "kilo";
	};
	"openrouter/auto": Model<"openai-completions"> & {
		id: "openrouter/auto";
		provider: "kilo";
	};
	"openrouter/auto-beta": Model<"openai-completions"> & {
		id: "openrouter/auto-beta";
		provider: "kilo";
	};
	"openrouter/bodybuilder": Model<"openai-completions"> & {
		id: "openrouter/bodybuilder";
		provider: "kilo";
	};
	"openrouter/elephant-alpha": Model<"openai-completions"> & {
		id: "openrouter/elephant-alpha";
		provider: "kilo";
	};
	"openrouter/free": Model<"openai-completions"> & {
		id: "openrouter/free";
		provider: "kilo";
	};
	"openrouter/fusion": Model<"openai-completions"> & {
		id: "openrouter/fusion";
		provider: "kilo";
	};
	"openrouter/healer-alpha": Model<"openai-completions"> & {
		id: "openrouter/healer-alpha";
		provider: "kilo";
	};
	"openrouter/hunter-alpha": Model<"openai-completions"> & {
		id: "openrouter/hunter-alpha";
		provider: "kilo";
	};
	"openrouter/owl-alpha": Model<"openai-completions"> & {
		id: "openrouter/owl-alpha";
		provider: "kilo";
	};
	"openrouter/pareto-code": Model<"openai-completions"> & {
		id: "openrouter/pareto-code";
		provider: "kilo";
	};
	"perceptron/perceptron-mk1": Model<"openai-completions"> & {
		id: "perceptron/perceptron-mk1";
		provider: "kilo";
	};
	"perplexity/sonar": Model<"openai-completions"> & {
		id: "perplexity/sonar";
		provider: "kilo";
	};
	"perplexity/sonar-deep-research": Model<"openai-completions"> & {
		id: "perplexity/sonar-deep-research";
		provider: "kilo";
	};
	"perplexity/sonar-pro": Model<"openai-completions"> & {
		id: "perplexity/sonar-pro";
		provider: "kilo";
	};
	"perplexity/sonar-pro-search": Model<"openai-completions"> & {
		id: "perplexity/sonar-pro-search";
		provider: "kilo";
	};
	"poolside/laguna-m.1": Model<"openai-completions"> & {
		id: "poolside/laguna-m.1";
		provider: "kilo";
	};
	"poolside/laguna-m.1:free": Model<"openai-completions"> & {
		id: "poolside/laguna-m.1:free";
		provider: "kilo";
	};
	"poolside/laguna-s-2.1": Model<"openai-completions"> & {
		id: "poolside/laguna-s-2.1";
		provider: "kilo";
	};
	"poolside/laguna-s-2.1:free": Model<"openai-completions"> & {
		id: "poolside/laguna-s-2.1:free";
		provider: "kilo";
	};
	"poolside/laguna-xs-2.1": Model<"openai-completions"> & {
		id: "poolside/laguna-xs-2.1";
		provider: "kilo";
	};
	"poolside/laguna-xs-2.1:free": Model<"openai-completions"> & {
		id: "poolside/laguna-xs-2.1:free";
		provider: "kilo";
	};
	"poolside/laguna-xs.2": Model<"openai-completions"> & {
		id: "poolside/laguna-xs.2";
		provider: "kilo";
	};
	"poolside/laguna-xs.2:free": Model<"openai-completions"> & {
		id: "poolside/laguna-xs.2:free";
		provider: "kilo";
	};
	"prime-intellect/intellect-3": Model<"openai-completions"> & {
		id: "prime-intellect/intellect-3";
		provider: "kilo";
	};
	"qwen/qwen-2.5-72b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen-2.5-72b-instruct";
		provider: "kilo";
	};
	"qwen/qwen-2.5-7b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen-2.5-7b-instruct";
		provider: "kilo";
	};
	"qwen/qwen-2.5-coder-32b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen-2.5-coder-32b-instruct";
		provider: "kilo";
	};
	"qwen/qwen-2.5-vl-7b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen-2.5-vl-7b-instruct";
		provider: "kilo";
	};
	"qwen/qwen-max": Model<"openai-completions"> & {
		id: "qwen/qwen-max";
		provider: "kilo";
	};
	"qwen/qwen-plus": Model<"openai-completions"> & {
		id: "qwen/qwen-plus";
		provider: "kilo";
	};
	"qwen/qwen-plus-2025-07-28": Model<"openai-completions"> & {
		id: "qwen/qwen-plus-2025-07-28";
		provider: "kilo";
	};
	"qwen/qwen-plus-2025-07-28:thinking": Model<"openai-completions"> & {
		id: "qwen/qwen-plus-2025-07-28:thinking";
		provider: "kilo";
	};
	"qwen/qwen-turbo": Model<"openai-completions"> & {
		id: "qwen/qwen-turbo";
		provider: "kilo";
	};
	"qwen/qwen-vl-max": Model<"openai-completions"> & {
		id: "qwen/qwen-vl-max";
		provider: "kilo";
	};
	"qwen/qwen-vl-plus": Model<"openai-completions"> & {
		id: "qwen/qwen-vl-plus";
		provider: "kilo";
	};
	"qwen/qwen2.5-coder-7b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen2.5-coder-7b-instruct";
		provider: "kilo";
	};
	"qwen/qwen2.5-vl-32b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen2.5-vl-32b-instruct";
		provider: "kilo";
	};
	"qwen/qwen2.5-vl-72b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen2.5-vl-72b-instruct";
		provider: "kilo";
	};
	"qwen/qwen3-14b": Model<"openai-completions"> & {
		id: "qwen/qwen3-14b";
		provider: "kilo";
	};
	"qwen/qwen3-235b-a22b": Model<"openai-completions"> & {
		id: "qwen/qwen3-235b-a22b";
		provider: "kilo";
	};
	"qwen/qwen3-235b-a22b-2507": Model<"openai-completions"> & {
		id: "qwen/qwen3-235b-a22b-2507";
		provider: "kilo";
	};
	"qwen/qwen3-235b-a22b-thinking-2507": Model<"openai-completions"> & {
		id: "qwen/qwen3-235b-a22b-thinking-2507";
		provider: "kilo";
	};
	"qwen/qwen3-30b-a3b": Model<"openai-completions"> & {
		id: "qwen/qwen3-30b-a3b";
		provider: "kilo";
	};
	"qwen/qwen3-30b-a3b-instruct-2507": Model<"openai-completions"> & {
		id: "qwen/qwen3-30b-a3b-instruct-2507";
		provider: "kilo";
	};
	"qwen/qwen3-30b-a3b-thinking-2507": Model<"openai-completions"> & {
		id: "qwen/qwen3-30b-a3b-thinking-2507";
		provider: "kilo";
	};
	"qwen/qwen3-32b": Model<"openai-completions"> & {
		id: "qwen/qwen3-32b";
		provider: "kilo";
	};
	"qwen/qwen3-8b": Model<"openai-completions"> & {
		id: "qwen/qwen3-8b";
		provider: "kilo";
	};
	"qwen/qwen3-coder": Model<"openai-completions"> & {
		id: "qwen/qwen3-coder";
		provider: "kilo";
	};
	"qwen/qwen3-coder-30b-a3b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen3-coder-30b-a3b-instruct";
		provider: "kilo";
	};
	"qwen/qwen3-coder-flash": Model<"openai-completions"> & {
		id: "qwen/qwen3-coder-flash";
		provider: "kilo";
	};
	"qwen/qwen3-coder-next": Model<"openai-completions"> & {
		id: "qwen/qwen3-coder-next";
		provider: "kilo";
	};
	"qwen/qwen3-coder-plus": Model<"openai-completions"> & {
		id: "qwen/qwen3-coder-plus";
		provider: "kilo";
	};
	"qwen/qwen3-coder:exacto": Model<"openai-completions"> & {
		id: "qwen/qwen3-coder:exacto";
		provider: "kilo";
	};
	"qwen/qwen3-max": Model<"openai-completions"> & {
		id: "qwen/qwen3-max";
		provider: "kilo";
	};
	"qwen/qwen3-max-thinking": Model<"openai-completions"> & {
		id: "qwen/qwen3-max-thinking";
		provider: "kilo";
	};
	"qwen/qwen3-next-80b-a3b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen3-next-80b-a3b-instruct";
		provider: "kilo";
	};
	"qwen/qwen3-next-80b-a3b-thinking": Model<"openai-completions"> & {
		id: "qwen/qwen3-next-80b-a3b-thinking";
		provider: "kilo";
	};
	"qwen/qwen3-vl-235b-a22b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen3-vl-235b-a22b-instruct";
		provider: "kilo";
	};
	"qwen/qwen3-vl-235b-a22b-thinking": Model<"openai-completions"> & {
		id: "qwen/qwen3-vl-235b-a22b-thinking";
		provider: "kilo";
	};
	"qwen/qwen3-vl-30b-a3b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen3-vl-30b-a3b-instruct";
		provider: "kilo";
	};
	"qwen/qwen3-vl-30b-a3b-thinking": Model<"openai-completions"> & {
		id: "qwen/qwen3-vl-30b-a3b-thinking";
		provider: "kilo";
	};
	"qwen/qwen3-vl-32b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen3-vl-32b-instruct";
		provider: "kilo";
	};
	"qwen/qwen3-vl-8b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen3-vl-8b-instruct";
		provider: "kilo";
	};
	"qwen/qwen3-vl-8b-thinking": Model<"openai-completions"> & {
		id: "qwen/qwen3-vl-8b-thinking";
		provider: "kilo";
	};
	"qwen/qwen3.5-122b-a10b": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-122b-a10b";
		provider: "kilo";
	};
	"qwen/qwen3.5-27b": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-27b";
		provider: "kilo";
	};
	"qwen/qwen3.5-35b-a3b": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-35b-a3b";
		provider: "kilo";
	};
	"qwen/qwen3.5-397b-a17b": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-397b-a17b";
		provider: "kilo";
	};
	"qwen/qwen3.5-9b": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-9b";
		provider: "kilo";
	};
	"qwen/qwen3.5-flash-02-23": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-flash-02-23";
		provider: "kilo";
	};
	"qwen/qwen3.5-plus-02-15": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-plus-02-15";
		provider: "kilo";
	};
	"qwen/qwen3.5-plus-20260420": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-plus-20260420";
		provider: "kilo";
	};
	"qwen/qwen3.6-27b": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-27b";
		provider: "kilo";
	};
	"qwen/qwen3.6-35b-a3b": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-35b-a3b";
		provider: "kilo";
	};
	"qwen/qwen3.6-flash": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-flash";
		provider: "kilo";
	};
	"qwen/qwen3.6-max-preview": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-max-preview";
		provider: "kilo";
	};
	"qwen/qwen3.6-plus": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-plus";
		provider: "kilo";
	};
	"qwen/qwen3.6-plus-preview:free": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-plus-preview:free";
		provider: "kilo";
	};
	"qwen/qwen3.6-plus:free": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-plus:free";
		provider: "kilo";
	};
	"qwen/qwen3.7-flash": Model<"openai-completions"> & {
		id: "qwen/qwen3.7-flash";
		provider: "kilo";
	};
	"qwen/qwen3.7-max": Model<"openai-completions"> & {
		id: "qwen/qwen3.7-max";
		provider: "kilo";
	};
	"qwen/qwen3.7-plus": Model<"openai-completions"> & {
		id: "qwen/qwen3.7-plus";
		provider: "kilo";
	};
	"qwen/qwen3.7-plus:free": Model<"openai-completions"> & {
		id: "qwen/qwen3.7-plus:free";
		provider: "kilo";
	};
	"qwen/qwen3.8-max": Model<"openai-completions"> & {
		id: "qwen/qwen3.8-max";
		provider: "kilo";
	};
	"qwen/qwq-32b": Model<"openai-completions"> & {
		id: "qwen/qwq-32b";
		provider: "kilo";
	};
	"raifle/sorcererlm-8x22b": Model<"openai-completions"> & {
		id: "raifle/sorcererlm-8x22b";
		provider: "kilo";
	};
	"reka/reka-edge": Model<"openai-completions"> & {
		id: "reka/reka-edge";
		provider: "kilo";
	};
	"rekaai/reka-edge": Model<"openai-completions"> & {
		id: "rekaai/reka-edge";
		provider: "kilo";
	};
	"rekaai/reka-flash-3": Model<"openai-completions"> & {
		id: "rekaai/reka-flash-3";
		provider: "kilo";
	};
	"relace/relace-apply-3": Model<"openai-completions"> & {
		id: "relace/relace-apply-3";
		provider: "kilo";
	};
	"relace/relace-search": Model<"openai-completions"> & {
		id: "relace/relace-search";
		provider: "kilo";
	};
	"sakana/fugu-ultra": Model<"openai-completions"> & {
		id: "sakana/fugu-ultra";
		provider: "kilo";
	};
	"sao10k/l3-euryale-70b": Model<"openai-completions"> & {
		id: "sao10k/l3-euryale-70b";
		provider: "kilo";
	};
	"sao10k/l3-lunaris-8b": Model<"openai-completions"> & {
		id: "sao10k/l3-lunaris-8b";
		provider: "kilo";
	};
	"sao10k/l3.1-70b-hanami-x1": Model<"openai-completions"> & {
		id: "sao10k/l3.1-70b-hanami-x1";
		provider: "kilo";
	};
	"sao10k/l3.1-euryale-70b": Model<"openai-completions"> & {
		id: "sao10k/l3.1-euryale-70b";
		provider: "kilo";
	};
	"sao10k/l3.3-euryale-70b": Model<"openai-completions"> & {
		id: "sao10k/l3.3-euryale-70b";
		provider: "kilo";
	};
	"stealth/claude-opus-4.6": Model<"openai-completions"> & {
		id: "stealth/claude-opus-4.6";
		provider: "kilo";
	};
	"stealth/claude-opus-4.7": Model<"openai-completions"> & {
		id: "stealth/claude-opus-4.7";
		provider: "kilo";
	};
	"stealth/claude-opus-4.8": Model<"openai-completions"> & {
		id: "stealth/claude-opus-4.8";
		provider: "kilo";
	};
	"stealth/claude-sonnet-4.6": Model<"openai-completions"> & {
		id: "stealth/claude-sonnet-4.6";
		provider: "kilo";
	};
	"stealth/gpt-5.6-sol": Model<"openai-completions"> & {
		id: "stealth/gpt-5.6-sol";
		provider: "kilo";
	};
	"stealth/qwen3.6-plus": Model<"openai-completions"> & {
		id: "stealth/qwen3.6-plus";
		provider: "kilo";
	};
	"stepfun/step-3.5-flash": Model<"openai-completions"> & {
		id: "stepfun/step-3.5-flash";
		provider: "kilo";
	};
	"stepfun/step-3.5-flash:free": Model<"openai-completions"> & {
		id: "stepfun/step-3.5-flash:free";
		provider: "kilo";
	};
	"stepfun/step-3.7-flash": Model<"openai-completions"> & {
		id: "stepfun/step-3.7-flash";
		provider: "kilo";
	};
	"stepfun/step-3.7-flash:free": Model<"openai-completions"> & {
		id: "stepfun/step-3.7-flash:free";
		provider: "kilo";
	};
	"switchpoint/router": Model<"openai-completions"> & {
		id: "switchpoint/router";
		provider: "kilo";
	};
	"tencent/hunyuan-a13b-instruct": Model<"openai-completions"> & {
		id: "tencent/hunyuan-a13b-instruct";
		provider: "kilo";
	};
	"tencent/hy3": Model<"openai-completions"> & {
		id: "tencent/hy3";
		provider: "kilo";
	};
	"tencent/hy3-preview": Model<"openai-completions"> & {
		id: "tencent/hy3-preview";
		provider: "kilo";
	};
	"tencent/hy3-preview:free": Model<"openai-completions"> & {
		id: "tencent/hy3-preview:free";
		provider: "kilo";
	};
	"tencent/hy3:free": Model<"openai-completions"> & {
		id: "tencent/hy3:free";
		provider: "kilo";
	};
	"thedrummer/cydonia-24b-v4.1": Model<"openai-completions"> & {
		id: "thedrummer/cydonia-24b-v4.1";
		provider: "kilo";
	};
	"thedrummer/rocinante-12b": Model<"openai-completions"> & {
		id: "thedrummer/rocinante-12b";
		provider: "kilo";
	};
	"thedrummer/skyfall-36b-v2": Model<"openai-completions"> & {
		id: "thedrummer/skyfall-36b-v2";
		provider: "kilo";
	};
	"thedrummer/unslopnemo-12b": Model<"openai-completions"> & {
		id: "thedrummer/unslopnemo-12b";
		provider: "kilo";
	};
	"thinkingmachines/inkling": Model<"openai-completions"> & {
		id: "thinkingmachines/inkling";
		provider: "kilo";
	};
	"thinkingmachines/inkling-small": Model<"openai-completions"> & {
		id: "thinkingmachines/inkling-small";
		provider: "kilo";
	};
	"tngtech/deepseek-r1t2-chimera": Model<"openai-completions"> & {
		id: "tngtech/deepseek-r1t2-chimera";
		provider: "kilo";
	};
	"undi95/remm-slerp-l2-13b": Model<"openai-completions"> & {
		id: "undi95/remm-slerp-l2-13b";
		provider: "kilo";
	};
	"upstage/solar-pro-3": Model<"openai-completions"> & {
		id: "upstage/solar-pro-3";
		provider: "kilo";
	};
	"writer/palmyra-x5": Model<"openai-completions"> & {
		id: "writer/palmyra-x5";
		provider: "kilo";
	};
	"x-ai/grok-3": Model<"openai-completions"> & {
		id: "x-ai/grok-3";
		provider: "kilo";
	};
	"x-ai/grok-3-beta": Model<"openai-completions"> & {
		id: "x-ai/grok-3-beta";
		provider: "kilo";
	};
	"x-ai/grok-3-mini": Model<"openai-completions"> & {
		id: "x-ai/grok-3-mini";
		provider: "kilo";
	};
	"x-ai/grok-3-mini-beta": Model<"openai-completions"> & {
		id: "x-ai/grok-3-mini-beta";
		provider: "kilo";
	};
	"x-ai/grok-4": Model<"openai-completions"> & {
		id: "x-ai/grok-4";
		provider: "kilo";
	};
	"x-ai/grok-4-fast": Model<"openai-completions"> & {
		id: "x-ai/grok-4-fast";
		provider: "kilo";
	};
	"x-ai/grok-4.1-fast": Model<"openai-completions"> & {
		id: "x-ai/grok-4.1-fast";
		provider: "kilo";
	};
	"x-ai/grok-4.20": Model<"openai-completions"> & {
		id: "x-ai/grok-4.20";
		provider: "kilo";
	};
	"x-ai/grok-4.20-beta": Model<"openai-completions"> & {
		id: "x-ai/grok-4.20-beta";
		provider: "kilo";
	};
	"x-ai/grok-4.20-multi-agent": Model<"openai-completions"> & {
		id: "x-ai/grok-4.20-multi-agent";
		provider: "kilo";
	};
	"x-ai/grok-4.20-multi-agent-beta": Model<"openai-completions"> & {
		id: "x-ai/grok-4.20-multi-agent-beta";
		provider: "kilo";
	};
	"x-ai/grok-4.3": Model<"openai-completions"> & {
		id: "x-ai/grok-4.3";
		provider: "kilo";
	};
	"x-ai/grok-4.5": Model<"openai-completions"> & {
		id: "x-ai/grok-4.5";
		provider: "kilo";
	};
	"x-ai/grok-build-0.1": Model<"openai-completions"> & {
		id: "x-ai/grok-build-0.1";
		provider: "kilo";
	};
	"x-ai/grok-code-fast-1": Model<"openai-completions"> & {
		id: "x-ai/grok-code-fast-1";
		provider: "kilo";
	};
	"x-ai/grok-code-fast-1:optimized:free": Model<"openai-completions"> & {
		id: "x-ai/grok-code-fast-1:optimized:free";
		provider: "kilo";
	};
	"xiaomi/mimo-v2-flash": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2-flash";
		provider: "kilo";
	};
	"xiaomi/mimo-v2-omni": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2-omni";
		provider: "kilo";
	};
	"xiaomi/mimo-v2-omni:free": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2-omni:free";
		provider: "kilo";
	};
	"xiaomi/mimo-v2-pro": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2-pro";
		provider: "kilo";
	};
	"xiaomi/mimo-v2-pro:free": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2-pro:free";
		provider: "kilo";
	};
	"xiaomi/mimo-v2.5": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2.5";
		provider: "kilo";
	};
	"xiaomi/mimo-v2.5-pro": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2.5-pro";
		provider: "kilo";
	};
	"z-ai/glm-4-32b": Model<"openai-completions"> & {
		id: "z-ai/glm-4-32b";
		provider: "kilo";
	};
	"z-ai/glm-4.5": Model<"openai-completions"> & {
		id: "z-ai/glm-4.5";
		provider: "kilo";
	};
	"z-ai/glm-4.5-air": Model<"openai-completions"> & {
		id: "z-ai/glm-4.5-air";
		provider: "kilo";
	};
	"z-ai/glm-4.5v": Model<"openai-completions"> & {
		id: "z-ai/glm-4.5v";
		provider: "kilo";
	};
	"z-ai/glm-4.6": Model<"openai-completions"> & {
		id: "z-ai/glm-4.6";
		provider: "kilo";
	};
	"z-ai/glm-4.6:exacto": Model<"openai-completions"> & {
		id: "z-ai/glm-4.6:exacto";
		provider: "kilo";
	};
	"z-ai/glm-4.6v": Model<"openai-completions"> & {
		id: "z-ai/glm-4.6v";
		provider: "kilo";
	};
	"z-ai/glm-4.7": Model<"openai-completions"> & {
		id: "z-ai/glm-4.7";
		provider: "kilo";
	};
	"z-ai/glm-4.7-flash": Model<"openai-completions"> & {
		id: "z-ai/glm-4.7-flash";
		provider: "kilo";
	};
	"z-ai/glm-5": Model<"openai-completions"> & {
		id: "z-ai/glm-5";
		provider: "kilo";
	};
	"z-ai/glm-5-turbo": Model<"openai-completions"> & {
		id: "z-ai/glm-5-turbo";
		provider: "kilo";
	};
	"z-ai/glm-5.1": Model<"openai-completions"> & {
		id: "z-ai/glm-5.1";
		provider: "kilo";
	};
	"z-ai/glm-5.2": Model<"openai-completions"> & {
		id: "z-ai/glm-5.2";
		provider: "kilo";
	};
	"z-ai/glm-5v-turbo": Model<"openai-completions"> & {
		id: "z-ai/glm-5v-turbo";
		provider: "kilo";
	};
	"~anthropic/claude-fable-latest": Model<"openai-completions"> & {
		id: "~anthropic/claude-fable-latest";
		provider: "kilo";
	};
	"~anthropic/claude-haiku-latest": Model<"openai-completions"> & {
		id: "~anthropic/claude-haiku-latest";
		provider: "kilo";
	};
	"~anthropic/claude-opus-latest": Model<"openai-completions"> & {
		id: "~anthropic/claude-opus-latest";
		provider: "kilo";
	};
	"~anthropic/claude-sonnet-latest": Model<"openai-completions"> & {
		id: "~anthropic/claude-sonnet-latest";
		provider: "kilo";
	};
	"~deepseek/deepseek-v4-flash-latest": Model<"openai-completions"> & {
		id: "~deepseek/deepseek-v4-flash-latest";
		provider: "kilo";
	};
	"~google/gemini-flash-latest": Model<"openai-completions"> & {
		id: "~google/gemini-flash-latest";
		provider: "kilo";
	};
	"~google/gemini-pro-latest": Model<"openai-completions"> & {
		id: "~google/gemini-pro-latest";
		provider: "kilo";
	};
	"~moonshotai/kimi-latest": Model<"openai-completions"> & {
		id: "~moonshotai/kimi-latest";
		provider: "kilo";
	};
	"~openai/gpt-latest": Model<"openai-completions"> & {
		id: "~openai/gpt-latest";
		provider: "kilo";
	};
	"~openai/gpt-mini-latest": Model<"openai-completions"> & {
		id: "~openai/gpt-mini-latest";
		provider: "kilo";
	};
	"~x-ai/grok-latest": Model<"openai-completions"> & {
		id: "~x-ai/grok-latest";
		provider: "kilo";
	};
};
