// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/meta.json" with { type: "json" };
import type { Model } from "../types.ts";

export const META_MODELS = values as {
	"muse-spark-1.1": Model<"openai-responses"> & {
		id: "muse-spark-1.1";
		provider: "meta";
	};
	"muse-spark-1.2": Model<"openai-responses"> & {
		id: "muse-spark-1.2";
		provider: "meta";
	};
	"muse-spark-1.2-contributor": Model<"openai-responses"> & {
		id: "muse-spark-1.2-contributor";
		provider: "meta";
	};
};
