// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/minimax-code.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const MINIMAX_CODE_MODELS: ModelCatalog<typeof values, "minimax-code"> =
	flattenModelCatalog("minimax-code", values);
