// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/novita.json" with { type: "json" };
import type { Model } from "../types.ts";

export const NOVITA_MODELS = values as {
	"Sao10K/L3-8B-Stheno-v3.2": Model<"openai-completions"> & {
		id: "Sao10K/L3-8B-Stheno-v3.2";
		provider: "novita";
	};
	"baichuan/baichuan-m2-32b": Model<"openai-completions"> & {
		id: "baichuan/baichuan-m2-32b";
		provider: "novita";
	};
	"baidu/cobuddy": Model<"openai-completions"> & {
		id: "baidu/cobuddy";
		provider: "novita";
	};
	"baidu/ernie-4.5-21B-a3b": Model<"openai-completions"> & {
		id: "baidu/ernie-4.5-21B-a3b";
		provider: "novita";
	};
	"baidu/ernie-4.5-vl-424b-a47b": Model<"openai-completions"> & {
		id: "baidu/ernie-4.5-vl-424b-a47b";
		provider: "novita";
	};
	"bunny": Model<"openai-completions"> & {
		id: "bunny";
		provider: "novita";
	};
	"deepseek/deepseek-ocr": Model<"openai-completions"> & {
		id: "deepseek/deepseek-ocr";
		provider: "novita";
	};
	"deepseek/deepseek-ocr-2": Model<"openai-completions"> & {
		id: "deepseek/deepseek-ocr-2";
		provider: "novita";
	};
	"deepseek/deepseek-r1": Model<"openai-completions"> & {
		id: "deepseek/deepseek-r1";
		provider: "novita";
	};
	"deepseek/deepseek-r1-0528": Model<"openai-completions"> & {
		id: "deepseek/deepseek-r1-0528";
		provider: "novita";
	};
	"deepseek/deepseek-r1-0528-qwen3-8b": Model<"openai-completions"> & {
		id: "deepseek/deepseek-r1-0528-qwen3-8b";
		provider: "novita";
	};
	"deepseek/deepseek-r1-distill-llama-70b": Model<"openai-completions"> & {
		id: "deepseek/deepseek-r1-distill-llama-70b";
		provider: "novita";
	};
	"deepseek/deepseek-r1-turbo": Model<"openai-completions"> & {
		id: "deepseek/deepseek-r1-turbo";
		provider: "novita";
	};
	"deepseek/deepseek-r1/community": Model<"openai-completions"> & {
		id: "deepseek/deepseek-r1/community";
		provider: "novita";
	};
	"deepseek/deepseek-v3-0324": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3-0324";
		provider: "novita";
	};
	"deepseek/deepseek-v3-turbo": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3-turbo";
		provider: "novita";
	};
	"deepseek/deepseek-v3.1": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3.1";
		provider: "novita";
	};
	"deepseek/deepseek-v3.1-terminus": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3.1-terminus";
		provider: "novita";
	};
	"deepseek/deepseek-v3.2": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3.2";
		provider: "novita";
	};
	"deepseek/deepseek-v3.2-exp": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3.2-exp";
		provider: "novita";
	};
	"deepseek/deepseek-v3/community": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3/community";
		provider: "novita";
	};
	"deepseek/deepseek-v4-flash": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-flash";
		provider: "novita";
	};
	"deepseek/deepseek-v4-flash-0731": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-flash-0731";
		provider: "novita";
	};
	"deepseek/deepseek-v4-pro": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-pro";
		provider: "novita";
	};
	"deepseek/deepseek_v3": Model<"openai-completions"> & {
		id: "deepseek/deepseek_v3";
		provider: "novita";
	};
	"dev/glm46": Model<"openai-completions"> & {
		id: "dev/glm46";
		provider: "novita";
	};
	"google/gemma-3-12b-it": Model<"openai-completions"> & {
		id: "google/gemma-3-12b-it";
		provider: "novita";
	};
	"google/gemma-3-27b-it": Model<"openai-completions"> & {
		id: "google/gemma-3-27b-it";
		provider: "novita";
	};
	"google/gemma-4-26b-a4b-it": Model<"openai-completions"> & {
		id: "google/gemma-4-26b-a4b-it";
		provider: "novita";
	};
	"google/gemma-4-31b-it": Model<"openai-completions"> & {
		id: "google/gemma-4-31b-it";
		provider: "novita";
	};
	"gryphe/mythomax-l2-13b": Model<"openai-completions"> & {
		id: "gryphe/mythomax-l2-13b";
		provider: "novita";
	};
	"gt-4p": Model<"openai-completions"> & {
		id: "gt-4p";
		provider: "novita";
	};
	"inclusionai/ling-2.6-1t": Model<"openai-completions"> & {
		id: "inclusionai/ling-2.6-1t";
		provider: "novita";
	};
	"inclusionai/ling-2.6-flash": Model<"openai-completions"> & {
		id: "inclusionai/ling-2.6-flash";
		provider: "novita";
	};
	"inclusionai/ling-3.0-flash": Model<"openai-completions"> & {
		id: "inclusionai/ling-3.0-flash";
		provider: "novita";
	};
	"inclusionai/ling-3.0-tiny": Model<"openai-completions"> & {
		id: "inclusionai/ling-3.0-tiny";
		provider: "novita";
	};
	"inclusionai/ring-2.6-1t": Model<"openai-completions"> & {
		id: "inclusionai/ring-2.6-1t";
		provider: "novita";
	};
	"kwaipilot/kat-coder-pro": Model<"openai-completions"> & {
		id: "kwaipilot/kat-coder-pro";
		provider: "novita";
	};
	"meta-llama/llama-3.1-8b-instruct": Model<"openai-completions"> & {
		id: "meta-llama/llama-3.1-8b-instruct";
		provider: "novita";
	};
	"meta-llama/llama-3.2-1b-instruct": Model<"openai-completions"> & {
		id: "meta-llama/llama-3.2-1b-instruct";
		provider: "novita";
	};
	"meta-llama/llama-3.3-70b-instruct": Model<"openai-completions"> & {
		id: "meta-llama/llama-3.3-70b-instruct";
		provider: "novita";
	};
	"meta-llama/llama-4-maverick-17b-128e-instruct-fp8": Model<"openai-completions"> & {
		id: "meta-llama/llama-4-maverick-17b-128e-instruct-fp8";
		provider: "novita";
	};
	"meta-llama/llama-4-scout-17b-16e-instruct": Model<"openai-completions"> & {
		id: "meta-llama/llama-4-scout-17b-16e-instruct";
		provider: "novita";
	};
	"microsoft/wizardlm-2-8x22b": Model<"openai-completions"> & {
		id: "microsoft/wizardlm-2-8x22b";
		provider: "novita";
	};
	"mindai/macaron-v1-tall": Model<"openai-completions"> & {
		id: "mindai/macaron-v1-tall";
		provider: "novita";
	};
	"mindai/macaron-v1-venti": Model<"openai-completions"> & {
		id: "mindai/macaron-v1-venti";
		provider: "novita";
	};
	"minimax/minimax-m2": Model<"openai-completions"> & {
		id: "minimax/minimax-m2";
		provider: "novita";
	};
	"minimax/minimax-m2.1": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.1";
		provider: "novita";
	};
	"minimax/minimax-m2.5": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.5";
		provider: "novita";
	};
	"minimax/minimax-m2.5-highspeed": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.5-highspeed";
		provider: "novita";
	};
	"minimax/minimax-m2.7": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.7";
		provider: "novita";
	};
	"minimax/minimax-m2.7-highspeed": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.7-highspeed";
		provider: "novita";
	};
	"minimax/minimax-m3": Model<"openai-completions"> & {
		id: "minimax/minimax-m3";
		provider: "novita";
	};
	"minimaxai/minimax-m1-80k": Model<"openai-completions"> & {
		id: "minimaxai/minimax-m1-80k";
		provider: "novita";
	};
	"mistralai/mistral-nemo": Model<"openai-completions"> & {
		id: "mistralai/mistral-nemo";
		provider: "novita";
	};
	"moonshotai/kimi-k2-0905": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2-0905";
		provider: "novita";
	};
	"moonshotai/kimi-k2-instruct": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2-instruct";
		provider: "novita";
	};
	"moonshotai/kimi-k2-thinking": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2-thinking";
		provider: "novita";
	};
	"moonshotai/kimi-k2.5": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.5";
		provider: "novita";
	};
	"moonshotai/kimi-k2.6": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.6";
		provider: "novita";
	};
	"moonshotai/kimi-k2.7-code": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.7-code";
		provider: "novita";
	};
	"moonshotai/kimi-k3": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k3";
		provider: "novita";
	};
	"nousresearch/hermes-2-pro-llama-3-8b": Model<"openai-completions"> & {
		id: "nousresearch/hermes-2-pro-llama-3-8b";
		provider: "novita";
	};
	"nvidia/nemotron-3-nano-30b-a3b": Model<"openai-completions"> & {
		id: "nvidia/nemotron-3-nano-30b-a3b";
		provider: "novita";
	};
	"openai/gpt-oss-120b": Model<"openai-completions"> & {
		id: "openai/gpt-oss-120b";
		provider: "novita";
	};
	"openai/gpt-oss-20b": Model<"openai-completions"> & {
		id: "openai/gpt-oss-20b";
		provider: "novita";
	};
	"paddlepaddle/paddleocr-vl": Model<"openai-completions"> & {
		id: "paddlepaddle/paddleocr-vl";
		provider: "novita";
	};
	"qwen/qwen-2.5-72b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen-2.5-72b-instruct";
		provider: "novita";
	};
	"qwen/qwen-mt-plus": Model<"openai-completions"> & {
		id: "qwen/qwen-mt-plus";
		provider: "novita";
	};
	"qwen/qwen3-235b-a22b-fp8": Model<"openai-completions"> & {
		id: "qwen/qwen3-235b-a22b-fp8";
		provider: "novita";
	};
	"qwen/qwen3-235b-a22b-instruct-2507": Model<"openai-completions"> & {
		id: "qwen/qwen3-235b-a22b-instruct-2507";
		provider: "novita";
	};
	"qwen/qwen3-235b-a22b-thinking-2507": Model<"openai-completions"> & {
		id: "qwen/qwen3-235b-a22b-thinking-2507";
		provider: "novita";
	};
	"qwen/qwen3-coder-30b-a3b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen3-coder-30b-a3b-instruct";
		provider: "novita";
	};
	"qwen/qwen3-coder-480b-a35b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen3-coder-480b-a35b-instruct";
		provider: "novita";
	};
	"qwen/qwen3-coder-next": Model<"openai-completions"> & {
		id: "qwen/qwen3-coder-next";
		provider: "novita";
	};
	"qwen/qwen3-max": Model<"openai-completions"> & {
		id: "qwen/qwen3-max";
		provider: "novita";
	};
	"qwen/qwen3-next-80b-a3b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen3-next-80b-a3b-instruct";
		provider: "novita";
	};
	"qwen/qwen3-omni-30b-a3b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen3-omni-30b-a3b-instruct";
		provider: "novita";
	};
	"qwen/qwen3-omni-30b-a3b-thinking": Model<"openai-completions"> & {
		id: "qwen/qwen3-omni-30b-a3b-thinking";
		provider: "novita";
	};
	"qwen/qwen3-vl-235b-a22b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen3-vl-235b-a22b-instruct";
		provider: "novita";
	};
	"qwen/qwen3-vl-235b-a22b-thinking": Model<"openai-completions"> & {
		id: "qwen/qwen3-vl-235b-a22b-thinking";
		provider: "novita";
	};
	"qwen/qwen3-vl-30b-a3b-instruct": Model<"openai-completions"> & {
		id: "qwen/qwen3-vl-30b-a3b-instruct";
		provider: "novita";
	};
	"qwen/qwen3.5-122b-a10b": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-122b-a10b";
		provider: "novita";
	};
	"qwen/qwen3.5-27b": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-27b";
		provider: "novita";
	};
	"qwen/qwen3.5-35b-a3b": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-35b-a3b";
		provider: "novita";
	};
	"qwen/qwen3.5-397b-a17b": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-397b-a17b";
		provider: "novita";
	};
	"qwen/qwen3.5-plus": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-plus";
		provider: "novita";
	};
	"qwen/qwen3.6-27b": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-27b";
		provider: "novita";
	};
	"qwen/qwen3.6-35b-a3b": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-35b-a3b";
		provider: "novita";
	};
	"qwen/qwen3.6-plus": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-plus";
		provider: "novita";
	};
	"qwen/qwen3.7-max": Model<"openai-completions"> & {
		id: "qwen/qwen3.7-max";
		provider: "novita";
	};
	"qwen/qwen3.8-max": Model<"openai-completions"> & {
		id: "qwen/qwen3.8-max";
		provider: "novita";
	};
	"sao10k/l3-70b-euryale-v2.1": Model<"openai-completions"> & {
		id: "sao10k/l3-70b-euryale-v2.1";
		provider: "novita";
	};
	"sao10k/l3-8b-lunaris": Model<"openai-completions"> & {
		id: "sao10k/l3-8b-lunaris";
		provider: "novita";
	};
	"sao10k/l31-70b-euryale-v2.2": Model<"openai-completions"> & {
		id: "sao10k/l31-70b-euryale-v2.2";
		provider: "novita";
	};
	"stepfun/step-3.7-flash": Model<"openai-completions"> & {
		id: "stepfun/step-3.7-flash";
		provider: "novita";
	};
	"tencent/hy3": Model<"openai-completions"> & {
		id: "tencent/hy3";
		provider: "novita";
	};
	"thudm/glm-4-32b-0414": Model<"openai-completions"> & {
		id: "thudm/glm-4-32b-0414";
		provider: "novita";
	};
	"xiaomimimo/mimo-v2.5": Model<"openai-completions"> & {
		id: "xiaomimimo/mimo-v2.5";
		provider: "novita";
	};
	"xiaomimimo/mimo-v2.5-pro": Model<"openai-completions"> & {
		id: "xiaomimimo/mimo-v2.5-pro";
		provider: "novita";
	};
	"zai-org/autoglm-phone-9b-multilingual": Model<"openai-completions"> & {
		id: "zai-org/autoglm-phone-9b-multilingual";
		provider: "novita";
	};
	"zai-org/glm-4.5-air": Model<"openai-completions"> & {
		id: "zai-org/glm-4.5-air";
		provider: "novita";
	};
	"zai-org/glm-4.5v": Model<"openai-completions"> & {
		id: "zai-org/glm-4.5v";
		provider: "novita";
	};
	"zai-org/glm-4.6": Model<"openai-completions"> & {
		id: "zai-org/glm-4.6";
		provider: "novita";
	};
	"zai-org/glm-4.6v": Model<"openai-completions"> & {
		id: "zai-org/glm-4.6v";
		provider: "novita";
	};
	"zai-org/glm-4.7": Model<"openai-completions"> & {
		id: "zai-org/glm-4.7";
		provider: "novita";
	};
	"zai-org/glm-4.7-flash": Model<"openai-completions"> & {
		id: "zai-org/glm-4.7-flash";
		provider: "novita";
	};
	"zai-org/glm-4.7-h": Model<"openai-completions"> & {
		id: "zai-org/glm-4.7-h";
		provider: "novita";
	};
	"zai-org/glm-5": Model<"openai-completions"> & {
		id: "zai-org/glm-5";
		provider: "novita";
	};
	"zai-org/glm-5-turbo": Model<"openai-completions"> & {
		id: "zai-org/glm-5-turbo";
		provider: "novita";
	};
	"zai-org/glm-5.1": Model<"openai-completions"> & {
		id: "zai-org/glm-5.1";
		provider: "novita";
	};
	"zai-org/glm-5.2": Model<"openai-completions"> & {
		id: "zai-org/glm-5.2";
		provider: "novita";
	};
	"zai-org/glm-5v-turbo": Model<"openai-completions"> & {
		id: "zai-org/glm-5v-turbo";
		provider: "novita";
	};
};
