// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/opencode-zen.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const OPENCODE_ZEN_MODELS: ModelCatalog<typeof values, "opencode-zen"> =
	flattenModelCatalog("opencode-zen", values);
