// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/qianfan.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const QIANFAN_MODELS: ModelCatalog<typeof values, "qianfan"> =
	flattenModelCatalog("qianfan", values);
