// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/qwen-portal.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const QWEN_PORTAL_MODELS: ModelCatalog<typeof values, "qwen-portal"> =
	flattenModelCatalog("qwen-portal", values);
