// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/sakana.json" with { type: "json" };
import type { Model } from "../types.ts";

export const SAKANA_MODELS = values as {
	"fugu": Model<"openai-responses"> & {
		id: "fugu";
		provider: "sakana";
	};
	"fugu-ultra": Model<"openai-responses"> & {
		id: "fugu-ultra";
		provider: "sakana";
	};
	"fugu-ultra-20260615": Model<"openai-responses"> & {
		id: "fugu-ultra-20260615";
		provider: "sakana";
	};
};
