// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/siliconflow-cn.json" with { type: "json" };
import type { Model } from "../types.ts";

export const SILICONFLOW_CN_MODELS = values as {
	"deepseek-ai/DeepSeek-V4-Pro": Model<"openai-completions"> & {
		id: "deepseek-ai/DeepSeek-V4-Pro";
		provider: "siliconflow-cn";
	};
	"zai-org/GLM-5.1": Model<"openai-completions"> & {
		id: "zai-org/GLM-5.1";
		provider: "siliconflow-cn";
	};
};
