// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/siliconflow-cn.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const SILICONFLOW_CN_MODELS: ModelCatalog<typeof values, "siliconflow-cn"> =
	flattenModelCatalog("siliconflow-cn", values);
