// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/synthetic.json" with { type: "json" };
import type { Model } from "../types.ts";

export const SYNTHETIC_MODELS = values as {
	"hf:Qwen/Qwen3.6-27B": Model<"openai-completions"> & {
		id: "hf:Qwen/Qwen3.6-27B";
		provider: "synthetic";
	};
	"hf:moonshotai/Kimi-K3": Model<"openai-completions"> & {
		id: "hf:moonshotai/Kimi-K3";
		provider: "synthetic";
	};
	"hf:nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4": Model<"openai-completions"> & {
		id: "hf:nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4";
		provider: "synthetic";
	};
	"hf:openai/gpt-oss-120b": Model<"openai-completions"> & {
		id: "hf:openai/gpt-oss-120b";
		provider: "synthetic";
	};
	"hf:zai-org/GLM-4.7-Flash": Model<"openai-completions"> & {
		id: "hf:zai-org/GLM-4.7-Flash";
		provider: "synthetic";
	};
	"hf:zai-org/GLM-5.2": Model<"openai-completions"> & {
		id: "hf:zai-org/GLM-5.2";
		provider: "synthetic";
	};
	"syn:large:text": Model<"openai-completions"> & {
		id: "syn:large:text";
		provider: "synthetic";
	};
	"syn:large:vision": Model<"openai-completions"> & {
		id: "syn:large:vision";
		provider: "synthetic";
	};
	"syn:small:text": Model<"openai-completions"> & {
		id: "syn:small:text";
		provider: "synthetic";
	};
	"syn:small:vision": Model<"openai-completions"> & {
		id: "syn:small:vision";
		provider: "synthetic";
	};
};
