// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/venice.json" with { type: "json" };
import type { Model } from "../types.ts";

export const VENICE_MODELS = values as {
	"aion-labs-aion-2-0": Model<"openai-completions"> & {
		id: "aion-labs-aion-2-0";
		provider: "venice";
	};
	"aion-labs-aion-3-0": Model<"openai-completions"> & {
		id: "aion-labs-aion-3-0";
		provider: "venice";
	};
	"aion-labs-aion-3-0-mini": Model<"openai-completions"> & {
		id: "aion-labs-aion-3-0-mini";
		provider: "venice";
	};
	"aion-labs.aion-2-0": Model<"openai-completions"> & {
		id: "aion-labs.aion-2-0";
		provider: "venice";
	};
	"arcee-trinity-large-thinking": Model<"openai-completions"> & {
		id: "arcee-trinity-large-thinking";
		provider: "venice";
	};
	"claude-fable-5": Model<"openai-completions"> & {
		id: "claude-fable-5";
		provider: "venice";
	};
	"claude-opus-4-5": Model<"openai-completions"> & {
		id: "claude-opus-4-5";
		provider: "venice";
	};
	"claude-opus-4-6": Model<"openai-completions"> & {
		id: "claude-opus-4-6";
		provider: "venice";
	};
	"claude-opus-4-6-fast": Model<"openai-completions"> & {
		id: "claude-opus-4-6-fast";
		provider: "venice";
	};
	"claude-opus-4-7": Model<"openai-completions"> & {
		id: "claude-opus-4-7";
		provider: "venice";
	};
	"claude-opus-4-7-fast": Model<"openai-completions"> & {
		id: "claude-opus-4-7-fast";
		provider: "venice";
	};
	"claude-opus-4-8": Model<"openai-completions"> & {
		id: "claude-opus-4-8";
		provider: "venice";
	};
	"claude-opus-4-8-fast": Model<"openai-completions"> & {
		id: "claude-opus-4-8-fast";
		provider: "venice";
	};
	"claude-opus-45": Model<"openai-completions"> & {
		id: "claude-opus-45";
		provider: "venice";
	};
	"claude-opus-5": Model<"openai-completions"> & {
		id: "claude-opus-5";
		provider: "venice";
	};
	"claude-opus-5-fast": Model<"openai-completions"> & {
		id: "claude-opus-5-fast";
		provider: "venice";
	};
	"claude-sonnet-4-5": Model<"openai-completions"> & {
		id: "claude-sonnet-4-5";
		provider: "venice";
	};
	"claude-sonnet-4-6": Model<"openai-completions"> & {
		id: "claude-sonnet-4-6";
		provider: "venice";
	};
	"claude-sonnet-45": Model<"openai-completions"> & {
		id: "claude-sonnet-45";
		provider: "venice";
	};
	"claude-sonnet-5": Model<"openai-completions"> & {
		id: "claude-sonnet-5";
		provider: "venice";
	};
	"deepseek-v3.2": Model<"openai-completions"> & {
		id: "deepseek-v3.2";
		provider: "venice";
	};
	"deepseek-v4-flash": Model<"openai-completions"> & {
		id: "deepseek-v4-flash";
		provider: "venice";
	};
	"deepseek-v4-flash-0731": Model<"openai-completions"> & {
		id: "deepseek-v4-flash-0731";
		provider: "venice";
	};
	"deepseek-v4-pro": Model<"openai-completions"> & {
		id: "deepseek-v4-pro";
		provider: "venice";
	};
	"e2ee-deepseek-v4-flash": Model<"openai-completions"> & {
		id: "e2ee-deepseek-v4-flash";
		provider: "venice";
	};
	"e2ee-gemma-3-27b-p": Model<"openai-completions"> & {
		id: "e2ee-gemma-3-27b-p";
		provider: "venice";
	};
	"e2ee-gemma-4-26b-a4b-uncensored-p": Model<"openai-completions"> & {
		id: "e2ee-gemma-4-26b-a4b-uncensored-p";
		provider: "venice";
	};
	"e2ee-gemma-4-31b": Model<"openai-completions"> & {
		id: "e2ee-gemma-4-31b";
		provider: "venice";
	};
	"e2ee-glm-4-7-flash-p": Model<"openai-completions"> & {
		id: "e2ee-glm-4-7-flash-p";
		provider: "venice";
	};
	"e2ee-glm-4-7-p": Model<"openai-completions"> & {
		id: "e2ee-glm-4-7-p";
		provider: "venice";
	};
	"e2ee-glm-5": Model<"openai-completions"> & {
		id: "e2ee-glm-5";
		provider: "venice";
	};
	"e2ee-glm-5-1": Model<"openai-completions"> & {
		id: "e2ee-glm-5-1";
		provider: "venice";
	};
	"e2ee-glm-5-2-p": Model<"openai-completions"> & {
		id: "e2ee-glm-5-2-p";
		provider: "venice";
	};
	"e2ee-gpt-oss-120b-p": Model<"openai-completions"> & {
		id: "e2ee-gpt-oss-120b-p";
		provider: "venice";
	};
	"e2ee-gpt-oss-20b-p": Model<"openai-completions"> & {
		id: "e2ee-gpt-oss-20b-p";
		provider: "venice";
	};
	"e2ee-qwen-2-5-7b-p": Model<"openai-completions"> & {
		id: "e2ee-qwen-2-5-7b-p";
		provider: "venice";
	};
	"e2ee-qwen3-30b-a3b-p": Model<"openai-completions"> & {
		id: "e2ee-qwen3-30b-a3b-p";
		provider: "venice";
	};
	"e2ee-qwen3-5-122b-a10b": Model<"openai-completions"> & {
		id: "e2ee-qwen3-5-122b-a10b";
		provider: "venice";
	};
	"e2ee-qwen3-6-27b": Model<"openai-completions"> & {
		id: "e2ee-qwen3-6-27b";
		provider: "venice";
	};
	"e2ee-qwen3-6-35b-a3b": Model<"openai-completions"> & {
		id: "e2ee-qwen3-6-35b-a3b";
		provider: "venice";
	};
	"e2ee-qwen3-6-35b-a3b-uncensored-p": Model<"openai-completions"> & {
		id: "e2ee-qwen3-6-35b-a3b-uncensored-p";
		provider: "venice";
	};
	"e2ee-qwen3-vl-30b-a3b-p": Model<"openai-completions"> & {
		id: "e2ee-qwen3-vl-30b-a3b-p";
		provider: "venice";
	};
	"e2ee-venice-uncensored-24b-p": Model<"openai-completions"> & {
		id: "e2ee-venice-uncensored-24b-p";
		provider: "venice";
	};
	"gemini-3-1-pro-preview": Model<"openai-completions"> & {
		id: "gemini-3-1-pro-preview";
		provider: "venice";
	};
	"gemini-3-5-flash": Model<"openai-completions"> & {
		id: "gemini-3-5-flash";
		provider: "venice";
	};
	"gemini-3-5-flash-lite": Model<"openai-completions"> & {
		id: "gemini-3-5-flash-lite";
		provider: "venice";
	};
	"gemini-3-6-flash": Model<"openai-completions"> & {
		id: "gemini-3-6-flash";
		provider: "venice";
	};
	"gemini-3-flash-preview": Model<"openai-completions"> & {
		id: "gemini-3-flash-preview";
		provider: "venice";
	};
	"gemini-3-pro-preview": Model<"openai-completions"> & {
		id: "gemini-3-pro-preview";
		provider: "venice";
	};
	"gemma-4-uncensored": Model<"openai-completions"> & {
		id: "gemma-4-uncensored";
		provider: "venice";
	};
	"google-gemma-3-27b-it": Model<"openai-completions"> & {
		id: "google-gemma-3-27b-it";
		provider: "venice";
	};
	"google-gemma-4-26b-a4b-it": Model<"openai-completions"> & {
		id: "google-gemma-4-26b-a4b-it";
		provider: "venice";
	};
	"google-gemma-4-31b-it": Model<"openai-completions"> & {
		id: "google-gemma-4-31b-it";
		provider: "venice";
	};
	"google.gemma-4-26b-a4b-it": Model<"openai-completions"> & {
		id: "google.gemma-4-26b-a4b-it";
		provider: "venice";
	};
	"google.gemma-4-31b-it": Model<"openai-completions"> & {
		id: "google.gemma-4-31b-it";
		provider: "venice";
	};
	"grok-4-20": Model<"openai-completions"> & {
		id: "grok-4-20";
		provider: "venice";
	};
	"grok-4-20-beta": Model<"openai-completions"> & {
		id: "grok-4-20-beta";
		provider: "venice";
	};
	"grok-4-20-multi-agent": Model<"openai-completions"> & {
		id: "grok-4-20-multi-agent";
		provider: "venice";
	};
	"grok-4-20-multi-agent-beta": Model<"openai-completions"> & {
		id: "grok-4-20-multi-agent-beta";
		provider: "venice";
	};
	"grok-4-3": Model<"openai-completions"> & {
		id: "grok-4-3";
		provider: "venice";
	};
	"grok-4-5": Model<"openai-completions"> & {
		id: "grok-4-5";
		provider: "venice";
	};
	"grok-41-fast": Model<"openai-completions"> & {
		id: "grok-41-fast";
		provider: "venice";
	};
	"grok-build-0-1": Model<"openai-completions"> & {
		id: "grok-build-0-1";
		provider: "venice";
	};
	"grok-code-fast-1": Model<"openai-completions"> & {
		id: "grok-code-fast-1";
		provider: "venice";
	};
	"hermes-3-llama-3.1-405b": Model<"openai-completions"> & {
		id: "hermes-3-llama-3.1-405b";
		provider: "venice";
	};
	"inkling": Model<"openai-completions"> & {
		id: "inkling";
		provider: "venice";
	};
	"kimi-k2-5": Model<"openai-completions"> & {
		id: "kimi-k2-5";
		provider: "venice";
	};
	"kimi-k2-6": Model<"openai-completions"> & {
		id: "kimi-k2-6";
		provider: "venice";
	};
	"kimi-k2-7-code": Model<"openai-completions"> & {
		id: "kimi-k2-7-code";
		provider: "venice";
	};
	"kimi-k2-thinking": Model<"openai-completions"> & {
		id: "kimi-k2-thinking";
		provider: "venice";
	};
	"kimi-k3": Model<"openai-completions"> & {
		id: "kimi-k3";
		provider: "venice";
	};
	"kimi-k3-fast-api": Model<"openai-completions"> & {
		id: "kimi-k3-fast-api";
		provider: "venice";
	};
	"llama-3.2-3b": Model<"openai-completions"> & {
		id: "llama-3.2-3b";
		provider: "venice";
	};
	"llama-3.3-70b": Model<"openai-completions"> & {
		id: "llama-3.3-70b";
		provider: "venice";
	};
	"mercury-2": Model<"openai-completions"> & {
		id: "mercury-2";
		provider: "venice";
	};
	"minimax-m21": Model<"openai-completions"> & {
		id: "minimax-m21";
		provider: "venice";
	};
	"minimax-m25": Model<"openai-completions"> & {
		id: "minimax-m25";
		provider: "venice";
	};
	"minimax-m27": Model<"openai-completions"> & {
		id: "minimax-m27";
		provider: "venice";
	};
	"minimax-m3": Model<"openai-completions"> & {
		id: "minimax-m3";
		provider: "venice";
	};
	"minimax-m3-preview": Model<"openai-completions"> & {
		id: "minimax-m3-preview";
		provider: "venice";
	};
	"mistral-31-24b": Model<"openai-completions"> & {
		id: "mistral-31-24b";
		provider: "venice";
	};
	"mistral-small-2603": Model<"openai-completions"> & {
		id: "mistral-small-2603";
		provider: "venice";
	};
	"mistral-small-3-2-24b-instruct": Model<"openai-completions"> & {
		id: "mistral-small-3-2-24b-instruct";
		provider: "venice";
	};
	"nvidia-nemotron-3-nano-30b-a3b": Model<"openai-completions"> & {
		id: "nvidia-nemotron-3-nano-30b-a3b";
		provider: "venice";
	};
	"nvidia-nemotron-3-ultra-550b-a55b": Model<"openai-completions"> & {
		id: "nvidia-nemotron-3-ultra-550b-a55b";
		provider: "venice";
	};
	"nvidia-nemotron-cascade-2-30b-a3b": Model<"openai-completions"> & {
		id: "nvidia-nemotron-cascade-2-30b-a3b";
		provider: "venice";
	};
	"olafangensan-glm-4.7-flash-heretic": Model<"openai-completions"> & {
		id: "olafangensan-glm-4.7-flash-heretic";
		provider: "venice";
	};
	"openai-gpt-4o-2024-11-20": Model<"openai-completions"> & {
		id: "openai-gpt-4o-2024-11-20";
		provider: "venice";
	};
	"openai-gpt-4o-mini-2024-07-18": Model<"openai-completions"> & {
		id: "openai-gpt-4o-mini-2024-07-18";
		provider: "venice";
	};
	"openai-gpt-52": Model<"openai-completions"> & {
		id: "openai-gpt-52";
		provider: "venice";
	};
	"openai-gpt-52-codex": Model<"openai-completions"> & {
		id: "openai-gpt-52-codex";
		provider: "venice";
	};
	"openai-gpt-53-codex": Model<"openai-completions"> & {
		id: "openai-gpt-53-codex";
		provider: "venice";
	};
	"openai-gpt-54": Model<"openai-completions"> & {
		id: "openai-gpt-54";
		provider: "venice";
	};
	"openai-gpt-54-mini": Model<"openai-completions"> & {
		id: "openai-gpt-54-mini";
		provider: "venice";
	};
	"openai-gpt-54-pro": Model<"openai-completions"> & {
		id: "openai-gpt-54-pro";
		provider: "venice";
	};
	"openai-gpt-55": Model<"openai-completions"> & {
		id: "openai-gpt-55";
		provider: "venice";
	};
	"openai-gpt-55-pro": Model<"openai-completions"> & {
		id: "openai-gpt-55-pro";
		provider: "venice";
	};
	"openai-gpt-56-luna": Model<"openai-completions"> & {
		id: "openai-gpt-56-luna";
		provider: "venice";
	};
	"openai-gpt-56-luna-pro": Model<"openai-completions"> & {
		id: "openai-gpt-56-luna-pro";
		provider: "venice";
	};
	"openai-gpt-56-sol": Model<"openai-completions"> & {
		id: "openai-gpt-56-sol";
		provider: "venice";
	};
	"openai-gpt-56-sol-pro": Model<"openai-completions"> & {
		id: "openai-gpt-56-sol-pro";
		provider: "venice";
	};
	"openai-gpt-56-terra": Model<"openai-completions"> & {
		id: "openai-gpt-56-terra";
		provider: "venice";
	};
	"openai-gpt-56-terra-pro": Model<"openai-completions"> & {
		id: "openai-gpt-56-terra-pro";
		provider: "venice";
	};
	"openai-gpt-oss-120b": Model<"openai-completions"> & {
		id: "openai-gpt-oss-120b";
		provider: "venice";
	};
	"qwen-3-6-plus": Model<"openai-completions"> & {
		id: "qwen-3-6-plus";
		provider: "venice";
	};
	"qwen-3-7-max": Model<"openai-completions"> & {
		id: "qwen-3-7-max";
		provider: "venice";
	};
	"qwen-3-7-plus": Model<"openai-completions"> & {
		id: "qwen-3-7-plus";
		provider: "venice";
	};
	"qwen-3-8-max": Model<"openai-completions"> & {
		id: "qwen-3-8-max";
		provider: "venice";
	};
	"qwen3-235b-a22b-instruct-2507": Model<"openai-completions"> & {
		id: "qwen3-235b-a22b-instruct-2507";
		provider: "venice";
	};
	"qwen3-235b-a22b-thinking-2507": Model<"openai-completions"> & {
		id: "qwen3-235b-a22b-thinking-2507";
		provider: "venice";
	};
	"qwen3-4b": Model<"openai-completions"> & {
		id: "qwen3-4b";
		provider: "venice";
	};
	"qwen3-5-35b-a3b": Model<"openai-completions"> & {
		id: "qwen3-5-35b-a3b";
		provider: "venice";
	};
	"qwen3-5-397b-a17b": Model<"openai-completions"> & {
		id: "qwen3-5-397b-a17b";
		provider: "venice";
	};
	"qwen3-5-9b": Model<"openai-completions"> & {
		id: "qwen3-5-9b";
		provider: "venice";
	};
	"qwen3-6-27b": Model<"openai-completions"> & {
		id: "qwen3-6-27b";
		provider: "venice";
	};
	"qwen3-6-35b-a3b": Model<"openai-completions"> & {
		id: "qwen3-6-35b-a3b";
		provider: "venice";
	};
	"qwen3-coder-480b-a35b-instruct": Model<"openai-completions"> & {
		id: "qwen3-coder-480b-a35b-instruct";
		provider: "venice";
	};
	"qwen3-coder-480b-a35b-instruct-turbo": Model<"openai-completions"> & {
		id: "qwen3-coder-480b-a35b-instruct-turbo";
		provider: "venice";
	};
	"qwen3-next-80b": Model<"openai-completions"> & {
		id: "qwen3-next-80b";
		provider: "venice";
	};
	"qwen3-vl-235b-a22b": Model<"openai-completions"> & {
		id: "qwen3-vl-235b-a22b";
		provider: "venice";
	};
	"seed-2-1-turbo": Model<"openai-completions"> & {
		id: "seed-2-1-turbo";
		provider: "venice";
	};
	"tencent-hy3-preview": Model<"openai-completions"> & {
		id: "tencent-hy3-preview";
		provider: "venice";
	};
	"venice-uncensored": Model<"openai-completions"> & {
		id: "venice-uncensored";
		provider: "venice";
	};
	"venice-uncensored-1-2": Model<"openai-completions"> & {
		id: "venice-uncensored-1-2";
		provider: "venice";
	};
	"venice-uncensored-role-play": Model<"openai-completions"> & {
		id: "venice-uncensored-role-play";
		provider: "venice";
	};
	"xiaomi-mimo-v2-5": Model<"openai-completions"> & {
		id: "xiaomi-mimo-v2-5";
		provider: "venice";
	};
	"z-ai-glm-5-turbo": Model<"openai-completions"> & {
		id: "z-ai-glm-5-turbo";
		provider: "venice";
	};
	"z-ai-glm-5v-turbo": Model<"openai-completions"> & {
		id: "z-ai-glm-5v-turbo";
		provider: "venice";
	};
	"zai-org-glm-4.6": Model<"openai-completions"> & {
		id: "zai-org-glm-4.6";
		provider: "venice";
	};
	"zai-org-glm-4.7": Model<"openai-completions"> & {
		id: "zai-org-glm-4.7";
		provider: "venice";
	};
	"zai-org-glm-4.7-flash": Model<"openai-completions"> & {
		id: "zai-org-glm-4.7-flash";
		provider: "venice";
	};
	"zai-org-glm-5": Model<"openai-completions"> & {
		id: "zai-org-glm-5";
		provider: "venice";
	};
	"zai-org-glm-5-1": Model<"openai-completions"> & {
		id: "zai-org-glm-5-1";
		provider: "venice";
	};
	"zai-org-glm-5-2": Model<"openai-completions"> & {
		id: "zai-org-glm-5-2";
		provider: "venice";
	};
};
