// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/vllm.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const VLLM_MODELS: ModelCatalog<typeof values, "vllm"> =
	flattenModelCatalog("vllm", values);
