// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/wafer-serverless.json" with { type: "json" };
import type { Model } from "../types.ts";

export const WAFER_SERVERLESS_MODELS = values as {
	"DeepSeek-V4-Flash-0731-Fast": Model<"openai-completions"> & {
		id: "DeepSeek-V4-Flash-0731-Fast";
		provider: "wafer-serverless";
	};
	"DeepSeek-V4-Pro": Model<"openai-completions"> & {
		id: "DeepSeek-V4-Pro";
		provider: "wafer-serverless";
	};
	"GLM-5.1": Model<"openai-completions"> & {
		id: "GLM-5.1";
		provider: "wafer-serverless";
	};
	"GLM-5.2": Model<"openai-completions"> & {
		id: "GLM-5.2";
		provider: "wafer-serverless";
	};
	"GLM5.2-Turbo": Model<"openai-completions"> & {
		id: "GLM5.2-Turbo";
		provider: "wafer-serverless";
	};
	"Kimi-K2.6": Model<"openai-completions"> & {
		id: "Kimi-K2.6";
		provider: "wafer-serverless";
	};
	"Kimi-K2.7-Code": Model<"openai-completions"> & {
		id: "Kimi-K2.7-Code";
		provider: "wafer-serverless";
	};
	"Kimi-K3": Model<"openai-completions"> & {
		id: "Kimi-K3";
		provider: "wafer-serverless";
	};
	"MiniMax-M3": Model<"openai-completions"> & {
		id: "MiniMax-M3";
		provider: "wafer-serverless";
	};
	"Qwen3.5-397B-A17B": Model<"openai-completions"> & {
		id: "Qwen3.5-397B-A17B";
		provider: "wafer-serverless";
	};
	"Qwen3.6-35B-A3B": Model<"openai-completions"> & {
		id: "Qwen3.6-35B-A3B";
		provider: "wafer-serverless";
	};
	"deepseek-v4-flash": Model<"openai-completions"> & {
		id: "deepseek-v4-flash";
		provider: "wafer-serverless";
	};
	"deepseek-v4-pro": Model<"openai-completions"> & {
		id: "deepseek-v4-pro";
		provider: "wafer-serverless";
	};
	"glm5.2-fast": Model<"openai-completions"> & {
		id: "glm5.2-fast";
		provider: "wafer-serverless";
	};
	"kimi-k3-fast": Model<"openai-completions"> & {
		id: "kimi-k3-fast";
		provider: "wafer-serverless";
	};
	"qwen3.7-max": Model<"openai-completions"> & {
		id: "qwen3.7-max";
		provider: "wafer-serverless";
	};
};
