// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/xai.json" with { type: "json" };
import type { Model } from "../types.ts";

export const XAI_MODELS = values as {
	"grok-2": Model<"openai-responses"> & {
		id: "grok-2";
		provider: "xai";
	};
	"grok-2-1212": Model<"openai-responses"> & {
		id: "grok-2-1212";
		provider: "xai";
	};
	"grok-2-latest": Model<"openai-responses"> & {
		id: "grok-2-latest";
		provider: "xai";
	};
	"grok-2-vision": Model<"openai-responses"> & {
		id: "grok-2-vision";
		provider: "xai";
	};
	"grok-2-vision-1212": Model<"openai-responses"> & {
		id: "grok-2-vision-1212";
		provider: "xai";
	};
	"grok-2-vision-latest": Model<"openai-responses"> & {
		id: "grok-2-vision-latest";
		provider: "xai";
	};
	"grok-3": Model<"openai-responses"> & {
		id: "grok-3";
		provider: "xai";
	};
	"grok-3-fast": Model<"openai-responses"> & {
		id: "grok-3-fast";
		provider: "xai";
	};
	"grok-3-fast-latest": Model<"openai-responses"> & {
		id: "grok-3-fast-latest";
		provider: "xai";
	};
	"grok-3-latest": Model<"openai-responses"> & {
		id: "grok-3-latest";
		provider: "xai";
	};
	"grok-3-mini": Model<"openai-responses"> & {
		id: "grok-3-mini";
		provider: "xai";
	};
	"grok-3-mini-fast": Model<"openai-responses"> & {
		id: "grok-3-mini-fast";
		provider: "xai";
	};
	"grok-3-mini-fast-latest": Model<"openai-responses"> & {
		id: "grok-3-mini-fast-latest";
		provider: "xai";
	};
	"grok-3-mini-latest": Model<"openai-responses"> & {
		id: "grok-3-mini-latest";
		provider: "xai";
	};
	"grok-4": Model<"openai-responses"> & {
		id: "grok-4";
		provider: "xai";
	};
	"grok-4-1-fast": Model<"openai-responses"> & {
		id: "grok-4-1-fast";
		provider: "xai";
	};
	"grok-4-1-fast-non-reasoning": Model<"openai-responses"> & {
		id: "grok-4-1-fast-non-reasoning";
		provider: "xai";
	};
	"grok-4-fast": Model<"openai-responses"> & {
		id: "grok-4-fast";
		provider: "xai";
	};
	"grok-4-fast-non-reasoning": Model<"openai-responses"> & {
		id: "grok-4-fast-non-reasoning";
		provider: "xai";
	};
	"grok-4.20-0309-non-reasoning": Model<"openai-responses"> & {
		id: "grok-4.20-0309-non-reasoning";
		provider: "xai";
	};
	"grok-4.20-0309-reasoning": Model<"openai-responses"> & {
		id: "grok-4.20-0309-reasoning";
		provider: "xai";
	};
	"grok-4.20-beta-latest-non-reasoning": Model<"openai-responses"> & {
		id: "grok-4.20-beta-latest-non-reasoning";
		provider: "xai";
	};
	"grok-4.20-beta-latest-reasoning": Model<"openai-responses"> & {
		id: "grok-4.20-beta-latest-reasoning";
		provider: "xai";
	};
	"grok-4.20-multi-agent-0309": Model<"openai-responses"> & {
		id: "grok-4.20-multi-agent-0309";
		provider: "xai";
	};
	"grok-4.20-multi-agent-beta-latest": Model<"openai-responses"> & {
		id: "grok-4.20-multi-agent-beta-latest";
		provider: "xai";
	};
	"grok-4.3": Model<"openai-completions"> & {
		id: "grok-4.3";
		provider: "xai";
	};
	"grok-4.5": Model<"openai-responses"> & {
		id: "grok-4.5";
		provider: "xai";
	};
	"grok-4.6": Model<"openai-responses"> & {
		id: "grok-4.6";
		provider: "xai";
	};
	"grok-beta": Model<"openai-responses"> & {
		id: "grok-beta";
		provider: "xai";
	};
	"grok-build": Model<"openai-responses"> & {
		id: "grok-build";
		provider: "xai";
	};
	"grok-build-0.1": Model<"openai-completions"> & {
		id: "grok-build-0.1";
		provider: "xai";
	};
	"grok-code-fast-1": Model<"openai-responses"> & {
		id: "grok-code-fast-1";
		provider: "xai";
	};
	"grok-composer-2.5-fast": Model<"openai-responses"> & {
		id: "grok-composer-2.5-fast";
		provider: "xai";
	};
	"grok-vision-beta": Model<"openai-responses"> & {
		id: "grok-vision-beta";
		provider: "xai";
	};
};
