// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/yolo-auto.json" with { type: "json" };
import type { Model } from "../types.ts";

export const YOLO_AUTO_MODELS = values as {
	"deepseek-flash-v4": Model<"openai-completions"> & {
		id: "deepseek-flash-v4";
		provider: "yolo-auto";
	};
};
