// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/zenmux.json" with { type: "json" };
import type { Model } from "../types.ts";

export const ZENMUX_MODELS = values as {
	"anthropic/claude-3.5-haiku": Model<"anthropic-messages"> & {
		id: "anthropic/claude-3.5-haiku";
		provider: "zenmux";
	};
	"anthropic/claude-3.5-sonnet": Model<"anthropic-messages"> & {
		id: "anthropic/claude-3.5-sonnet";
		provider: "zenmux";
	};
	"anthropic/claude-3.7-sonnet": Model<"anthropic-messages"> & {
		id: "anthropic/claude-3.7-sonnet";
		provider: "zenmux";
	};
	"anthropic/claude-fable-5": Model<"anthropic-messages"> & {
		id: "anthropic/claude-fable-5";
		provider: "zenmux";
	};
	"anthropic/claude-fable-5-free": Model<"anthropic-messages"> & {
		id: "anthropic/claude-fable-5-free";
		provider: "zenmux";
	};
	"anthropic/claude-haiku-4.5": Model<"anthropic-messages"> & {
		id: "anthropic/claude-haiku-4.5";
		provider: "zenmux";
	};
	"anthropic/claude-opus-4": Model<"anthropic-messages"> & {
		id: "anthropic/claude-opus-4";
		provider: "zenmux";
	};
	"anthropic/claude-opus-4.1": Model<"anthropic-messages"> & {
		id: "anthropic/claude-opus-4.1";
		provider: "zenmux";
	};
	"anthropic/claude-opus-4.5": Model<"anthropic-messages"> & {
		id: "anthropic/claude-opus-4.5";
		provider: "zenmux";
	};
	"anthropic/claude-opus-4.6": Model<"anthropic-messages"> & {
		id: "anthropic/claude-opus-4.6";
		provider: "zenmux";
	};
	"anthropic/claude-opus-4.7": Model<"anthropic-messages"> & {
		id: "anthropic/claude-opus-4.7";
		provider: "zenmux";
	};
	"anthropic/claude-opus-4.8": Model<"anthropic-messages"> & {
		id: "anthropic/claude-opus-4.8";
		provider: "zenmux";
	};
	"anthropic/claude-opus-5": Model<"anthropic-messages"> & {
		id: "anthropic/claude-opus-5";
		provider: "zenmux";
	};
	"anthropic/claude-sonnet-4": Model<"anthropic-messages"> & {
		id: "anthropic/claude-sonnet-4";
		provider: "zenmux";
	};
	"anthropic/claude-sonnet-4.5": Model<"anthropic-messages"> & {
		id: "anthropic/claude-sonnet-4.5";
		provider: "zenmux";
	};
	"anthropic/claude-sonnet-4.6": Model<"anthropic-messages"> & {
		id: "anthropic/claude-sonnet-4.6";
		provider: "zenmux";
	};
	"anthropic/claude-sonnet-5": Model<"anthropic-messages"> & {
		id: "anthropic/claude-sonnet-5";
		provider: "zenmux";
	};
	"anthropic/claude-sonnet-5-free": Model<"anthropic-messages"> & {
		id: "anthropic/claude-sonnet-5-free";
		provider: "zenmux";
	};
	"baidu/ernie-5.0-thinking-preview": Model<"openai-completions"> & {
		id: "baidu/ernie-5.0-thinking-preview";
		provider: "zenmux";
	};
	"baidu/ernie-5.1": Model<"openai-completions"> & {
		id: "baidu/ernie-5.1";
		provider: "zenmux";
	};
	"baidu/ernie-x1.1-preview": Model<"openai-completions"> & {
		id: "baidu/ernie-x1.1-preview";
		provider: "zenmux";
	};
	"bytedance/doubao-seed-1.8": Model<"openai-completions"> & {
		id: "bytedance/doubao-seed-1.8";
		provider: "zenmux";
	};
	"bytedance/doubao-seed-2.0-code": Model<"openai-completions"> & {
		id: "bytedance/doubao-seed-2.0-code";
		provider: "zenmux";
	};
	"bytedance/doubao-seed-2.0-lite": Model<"openai-completions"> & {
		id: "bytedance/doubao-seed-2.0-lite";
		provider: "zenmux";
	};
	"bytedance/doubao-seed-2.0-mini": Model<"openai-completions"> & {
		id: "bytedance/doubao-seed-2.0-mini";
		provider: "zenmux";
	};
	"bytedance/doubao-seed-2.0-pro": Model<"openai-completions"> & {
		id: "bytedance/doubao-seed-2.0-pro";
		provider: "zenmux";
	};
	"bytedance/doubao-seed-2.1-pro": Model<"openai-completions"> & {
		id: "bytedance/doubao-seed-2.1-pro";
		provider: "zenmux";
	};
	"bytedance/doubao-seed-2.1-turbo": Model<"openai-completions"> & {
		id: "bytedance/doubao-seed-2.1-turbo";
		provider: "zenmux";
	};
	"bytedance/doubao-seed-character": Model<"openai-completions"> & {
		id: "bytedance/doubao-seed-character";
		provider: "zenmux";
	};
	"bytedance/doubao-seed-code": Model<"openai-completions"> & {
		id: "bytedance/doubao-seed-code";
		provider: "zenmux";
	};
	"bytedance/doubao-seed-evolving": Model<"openai-completions"> & {
		id: "bytedance/doubao-seed-evolving";
		provider: "zenmux";
	};
	"deepseek/deepseek-chat": Model<"openai-completions"> & {
		id: "deepseek/deepseek-chat";
		provider: "zenmux";
	};
	"deepseek/deepseek-chat-v3.1": Model<"openai-completions"> & {
		id: "deepseek/deepseek-chat-v3.1";
		provider: "zenmux";
	};
	"deepseek/deepseek-r1-0528": Model<"openai-completions"> & {
		id: "deepseek/deepseek-r1-0528";
		provider: "zenmux";
	};
	"deepseek/deepseek-reasoner": Model<"openai-completions"> & {
		id: "deepseek/deepseek-reasoner";
		provider: "zenmux";
	};
	"deepseek/deepseek-v3.2": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3.2";
		provider: "zenmux";
	};
	"deepseek/deepseek-v3.2-exp": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v3.2-exp";
		provider: "zenmux";
	};
	"deepseek/deepseek-v4-flash": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-flash";
		provider: "zenmux";
	};
	"deepseek/deepseek-v4-flash-free": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-flash-free";
		provider: "zenmux";
	};
	"deepseek/deepseek-v4-pro": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-pro";
		provider: "zenmux";
	};
	"deepseek/deepseek-v4-pro-free": Model<"openai-completions"> & {
		id: "deepseek/deepseek-v4-pro-free";
		provider: "zenmux";
	};
	"google/gemini-2.0-flash": Model<"openai-completions"> & {
		id: "google/gemini-2.0-flash";
		provider: "zenmux";
	};
	"google/gemini-2.0-flash-lite-001": Model<"openai-completions"> & {
		id: "google/gemini-2.0-flash-lite-001";
		provider: "zenmux";
	};
	"google/gemini-2.5-flash": Model<"openai-completions"> & {
		id: "google/gemini-2.5-flash";
		provider: "zenmux";
	};
	"google/gemini-2.5-flash-lite": Model<"openai-completions"> & {
		id: "google/gemini-2.5-flash-lite";
		provider: "zenmux";
	};
	"google/gemini-2.5-pro": Model<"openai-completions"> & {
		id: "google/gemini-2.5-pro";
		provider: "zenmux";
	};
	"google/gemini-3-flash-preview": Model<"openai-completions"> & {
		id: "google/gemini-3-flash-preview";
		provider: "zenmux";
	};
	"google/gemini-3-pro-image-preview": Model<"openai-completions"> & {
		id: "google/gemini-3-pro-image-preview";
		provider: "zenmux";
	};
	"google/gemini-3-pro-preview": Model<"openai-completions"> & {
		id: "google/gemini-3-pro-preview";
		provider: "zenmux";
	};
	"google/gemini-3.1-flash-lite": Model<"openai-completions"> & {
		id: "google/gemini-3.1-flash-lite";
		provider: "zenmux";
	};
	"google/gemini-3.1-flash-lite-preview": Model<"openai-completions"> & {
		id: "google/gemini-3.1-flash-lite-preview";
		provider: "zenmux";
	};
	"google/gemini-3.1-pro-preview": Model<"openai-completions"> & {
		id: "google/gemini-3.1-pro-preview";
		provider: "zenmux";
	};
	"google/gemini-3.5-flash": Model<"openai-completions"> & {
		id: "google/gemini-3.5-flash";
		provider: "zenmux";
	};
	"google/gemini-3.5-flash-free": Model<"openai-completions"> & {
		id: "google/gemini-3.5-flash-free";
		provider: "zenmux";
	};
	"google/gemini-3.5-flash-lite": Model<"openai-completions"> & {
		id: "google/gemini-3.5-flash-lite";
		provider: "zenmux";
	};
	"google/gemini-3.6-flash": Model<"openai-completions"> & {
		id: "google/gemini-3.6-flash";
		provider: "zenmux";
	};
	"google/gemini-embedding-2": Model<"openai-completions"> & {
		id: "google/gemini-embedding-2";
		provider: "zenmux";
	};
	"google/gemma-3-12b-it": Model<"openai-completions"> & {
		id: "google/gemma-3-12b-it";
		provider: "zenmux";
	};
	"google/gemma-4-26b-a4b-it": Model<"openai-completions"> & {
		id: "google/gemma-4-26b-a4b-it";
		provider: "zenmux";
	};
	"inclusionai/ling-1t": Model<"openai-completions"> & {
		id: "inclusionai/ling-1t";
		provider: "zenmux";
	};
	"inclusionai/ling-2.6-1t": Model<"openai-completions"> & {
		id: "inclusionai/ling-2.6-1t";
		provider: "zenmux";
	};
	"inclusionai/ling-2.6-flash": Model<"openai-completions"> & {
		id: "inclusionai/ling-2.6-flash";
		provider: "zenmux";
	};
	"inclusionai/ling-3.0-flash": Model<"openai-completions"> & {
		id: "inclusionai/ling-3.0-flash";
		provider: "zenmux";
	};
	"inclusionai/ling-flash-2.0": Model<"openai-completions"> & {
		id: "inclusionai/ling-flash-2.0";
		provider: "zenmux";
	};
	"inclusionai/ling-mini-2.0": Model<"openai-completions"> & {
		id: "inclusionai/ling-mini-2.0";
		provider: "zenmux";
	};
	"inclusionai/llada2.0-flash-cap": Model<"openai-completions"> & {
		id: "inclusionai/llada2.0-flash-cap";
		provider: "zenmux";
	};
	"inclusionai/llada2.1-flash": Model<"openai-completions"> & {
		id: "inclusionai/llada2.1-flash";
		provider: "zenmux";
	};
	"inclusionai/ming-flash-omni-2.0": Model<"openai-completions"> & {
		id: "inclusionai/ming-flash-omni-2.0";
		provider: "zenmux";
	};
	"inclusionai/ring-1t": Model<"openai-completions"> & {
		id: "inclusionai/ring-1t";
		provider: "zenmux";
	};
	"inclusionai/ring-2.6-1t": Model<"openai-completions"> & {
		id: "inclusionai/ring-2.6-1t";
		provider: "zenmux";
	};
	"inclusionai/ring-flash-2.0": Model<"openai-completions"> & {
		id: "inclusionai/ring-flash-2.0";
		provider: "zenmux";
	};
	"inclusionai/ring-mini-2.0": Model<"openai-completions"> & {
		id: "inclusionai/ring-mini-2.0";
		provider: "zenmux";
	};
	"kuaishou/kat-coder-air-v2.5": Model<"openai-completions"> & {
		id: "kuaishou/kat-coder-air-v2.5";
		provider: "zenmux";
	};
	"kuaishou/kat-coder-pro-v1": Model<"openai-completions"> & {
		id: "kuaishou/kat-coder-pro-v1";
		provider: "zenmux";
	};
	"kuaishou/kat-coder-pro-v1-free": Model<"openai-completions"> & {
		id: "kuaishou/kat-coder-pro-v1-free";
		provider: "zenmux";
	};
	"kuaishou/kat-coder-pro-v2": Model<"openai-completions"> & {
		id: "kuaishou/kat-coder-pro-v2";
		provider: "zenmux";
	};
	"kuaishou/kat-coder-pro-v2.5": Model<"openai-completions"> & {
		id: "kuaishou/kat-coder-pro-v2.5";
		provider: "zenmux";
	};
	"meituan/longcat-2.0": Model<"openai-completions"> & {
		id: "meituan/longcat-2.0";
		provider: "zenmux";
	};
	"meta/llama-3.3-70b-instruct": Model<"openai-completions"> & {
		id: "meta/llama-3.3-70b-instruct";
		provider: "zenmux";
	};
	"meta/llama-4-scout-17b-16e-instruct": Model<"openai-completions"> & {
		id: "meta/llama-4-scout-17b-16e-instruct";
		provider: "zenmux";
	};
	"meta/muse-spark-1.1": Model<"openai-completions"> & {
		id: "meta/muse-spark-1.1";
		provider: "zenmux";
	};
	"meta/muse-spark-1.2": Model<"openai-completions"> & {
		id: "meta/muse-spark-1.2";
		provider: "zenmux";
	};
	"minimax/minimax-m2": Model<"openai-completions"> & {
		id: "minimax/minimax-m2";
		provider: "zenmux";
	};
	"minimax/minimax-m2-her": Model<"openai-completions"> & {
		id: "minimax/minimax-m2-her";
		provider: "zenmux";
	};
	"minimax/minimax-m2.1": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.1";
		provider: "zenmux";
	};
	"minimax/minimax-m2.5": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.5";
		provider: "zenmux";
	};
	"minimax/minimax-m2.5-lightning": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.5-lightning";
		provider: "zenmux";
	};
	"minimax/minimax-m2.7": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.7";
		provider: "zenmux";
	};
	"minimax/minimax-m2.7-highspeed": Model<"openai-completions"> & {
		id: "minimax/minimax-m2.7-highspeed";
		provider: "zenmux";
	};
	"minimax/minimax-m3": Model<"openai-completions"> & {
		id: "minimax/minimax-m3";
		provider: "zenmux";
	};
	"mistralai/mistral-large-2512": Model<"openai-completions"> & {
		id: "mistralai/mistral-large-2512";
		provider: "zenmux";
	};
	"moonshotai/kimi-k2-0711": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2-0711";
		provider: "zenmux";
	};
	"moonshotai/kimi-k2-0905": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2-0905";
		provider: "zenmux";
	};
	"moonshotai/kimi-k2-thinking": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2-thinking";
		provider: "zenmux";
	};
	"moonshotai/kimi-k2-thinking-turbo": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2-thinking-turbo";
		provider: "zenmux";
	};
	"moonshotai/kimi-k2.5": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.5";
		provider: "zenmux";
	};
	"moonshotai/kimi-k2.6": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.6";
		provider: "zenmux";
	};
	"moonshotai/kimi-k2.7-code": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.7-code";
		provider: "zenmux";
	};
	"moonshotai/kimi-k2.7-code-free": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.7-code-free";
		provider: "zenmux";
	};
	"moonshotai/kimi-k2.7-code-highspeed": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k2.7-code-highspeed";
		provider: "zenmux";
	};
	"moonshotai/kimi-k3": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k3";
		provider: "zenmux";
	};
	"moonshotai/kimi-k3-free": Model<"openai-completions"> & {
		id: "moonshotai/kimi-k3-free";
		provider: "zenmux";
	};
	"openai/chat-latest": Model<"openai-completions"> & {
		id: "openai/chat-latest";
		provider: "zenmux";
	};
	"openai/gpt-4.1": Model<"openai-completions"> & {
		id: "openai/gpt-4.1";
		provider: "zenmux";
	};
	"openai/gpt-4.1-mini": Model<"openai-completions"> & {
		id: "openai/gpt-4.1-mini";
		provider: "zenmux";
	};
	"openai/gpt-4.1-nano": Model<"openai-completions"> & {
		id: "openai/gpt-4.1-nano";
		provider: "zenmux";
	};
	"openai/gpt-4o": Model<"openai-completions"> & {
		id: "openai/gpt-4o";
		provider: "zenmux";
	};
	"openai/gpt-4o-mini": Model<"openai-completions"> & {
		id: "openai/gpt-4o-mini";
		provider: "zenmux";
	};
	"openai/gpt-5": Model<"openai-completions"> & {
		id: "openai/gpt-5";
		provider: "zenmux";
	};
	"openai/gpt-5-chat": Model<"openai-completions"> & {
		id: "openai/gpt-5-chat";
		provider: "zenmux";
	};
	"openai/gpt-5-codex": Model<"openai-completions"> & {
		id: "openai/gpt-5-codex";
		provider: "zenmux";
	};
	"openai/gpt-5-mini": Model<"openai-completions"> & {
		id: "openai/gpt-5-mini";
		provider: "zenmux";
	};
	"openai/gpt-5-nano": Model<"openai-completions"> & {
		id: "openai/gpt-5-nano";
		provider: "zenmux";
	};
	"openai/gpt-5-pro": Model<"openai-completions"> & {
		id: "openai/gpt-5-pro";
		provider: "zenmux";
	};
	"openai/gpt-5.1": Model<"openai-completions"> & {
		id: "openai/gpt-5.1";
		provider: "zenmux";
	};
	"openai/gpt-5.1-chat": Model<"openai-completions"> & {
		id: "openai/gpt-5.1-chat";
		provider: "zenmux";
	};
	"openai/gpt-5.1-codex": Model<"openai-completions"> & {
		id: "openai/gpt-5.1-codex";
		provider: "zenmux";
	};
	"openai/gpt-5.1-codex-mini": Model<"openai-completions"> & {
		id: "openai/gpt-5.1-codex-mini";
		provider: "zenmux";
	};
	"openai/gpt-5.2": Model<"openai-completions"> & {
		id: "openai/gpt-5.2";
		provider: "zenmux";
	};
	"openai/gpt-5.2-chat": Model<"openai-completions"> & {
		id: "openai/gpt-5.2-chat";
		provider: "zenmux";
	};
	"openai/gpt-5.2-codex": Model<"openai-completions"> & {
		id: "openai/gpt-5.2-codex";
		provider: "zenmux";
	};
	"openai/gpt-5.2-pro": Model<"openai-completions"> & {
		id: "openai/gpt-5.2-pro";
		provider: "zenmux";
	};
	"openai/gpt-5.3-chat": Model<"openai-completions"> & {
		id: "openai/gpt-5.3-chat";
		provider: "zenmux";
	};
	"openai/gpt-5.3-codex": Model<"openai-completions"> & {
		id: "openai/gpt-5.3-codex";
		provider: "zenmux";
	};
	"openai/gpt-5.4": Model<"openai-completions"> & {
		id: "openai/gpt-5.4";
		provider: "zenmux";
	};
	"openai/gpt-5.4-mini": Model<"openai-completions"> & {
		id: "openai/gpt-5.4-mini";
		provider: "zenmux";
	};
	"openai/gpt-5.4-nano": Model<"openai-completions"> & {
		id: "openai/gpt-5.4-nano";
		provider: "zenmux";
	};
	"openai/gpt-5.4-pro": Model<"openai-completions"> & {
		id: "openai/gpt-5.4-pro";
		provider: "zenmux";
	};
	"openai/gpt-5.5": Model<"openai-completions"> & {
		id: "openai/gpt-5.5";
		provider: "zenmux";
	};
	"openai/gpt-5.5-instant": Model<"openai-completions"> & {
		id: "openai/gpt-5.5-instant";
		provider: "zenmux";
	};
	"openai/gpt-5.5-pro": Model<"openai-completions"> & {
		id: "openai/gpt-5.5-pro";
		provider: "zenmux";
	};
	"openai/gpt-5.6-luna": Model<"openai-completions"> & {
		id: "openai/gpt-5.6-luna";
		provider: "zenmux";
	};
	"openai/gpt-5.6-sol": Model<"openai-completions"> & {
		id: "openai/gpt-5.6-sol";
		provider: "zenmux";
	};
	"openai/gpt-5.6-terra": Model<"openai-completions"> & {
		id: "openai/gpt-5.6-terra";
		provider: "zenmux";
	};
	"openai/gpt-image-1.5": Model<"openai-completions"> & {
		id: "openai/gpt-image-1.5";
		provider: "zenmux";
	};
	"openai/gpt-image-2": Model<"openai-completions"> & {
		id: "openai/gpt-image-2";
		provider: "zenmux";
	};
	"openai/o4-mini": Model<"openai-completions"> & {
		id: "openai/o4-mini";
		provider: "zenmux";
	};
	"openai/text-embedding-3-large": Model<"openai-completions"> & {
		id: "openai/text-embedding-3-large";
		provider: "zenmux";
	};
	"openai/text-embedding-3-small": Model<"openai-completions"> & {
		id: "openai/text-embedding-3-small";
		provider: "zenmux";
	};
	"qwen/qwen3-14b": Model<"openai-completions"> & {
		id: "qwen/qwen3-14b";
		provider: "zenmux";
	};
	"qwen/qwen3-235b-a22b-2507": Model<"openai-completions"> & {
		id: "qwen/qwen3-235b-a22b-2507";
		provider: "zenmux";
	};
	"qwen/qwen3-235b-a22b-thinking-2507": Model<"openai-completions"> & {
		id: "qwen/qwen3-235b-a22b-thinking-2507";
		provider: "zenmux";
	};
	"qwen/qwen3-asr-flash": Model<"openai-completions"> & {
		id: "qwen/qwen3-asr-flash";
		provider: "zenmux";
	};
	"qwen/qwen3-coder": Model<"openai-completions"> & {
		id: "qwen/qwen3-coder";
		provider: "zenmux";
	};
	"qwen/qwen3-coder-plus": Model<"openai-completions"> & {
		id: "qwen/qwen3-coder-plus";
		provider: "zenmux";
	};
	"qwen/qwen3-max": Model<"openai-completions"> & {
		id: "qwen/qwen3-max";
		provider: "zenmux";
	};
	"qwen/qwen3-max-preview": Model<"openai-completions"> & {
		id: "qwen/qwen3-max-preview";
		provider: "zenmux";
	};
	"qwen/qwen3-vl-embedding": Model<"openai-completions"> & {
		id: "qwen/qwen3-vl-embedding";
		provider: "zenmux";
	};
	"qwen/qwen3-vl-plus": Model<"openai-completions"> & {
		id: "qwen/qwen3-vl-plus";
		provider: "zenmux";
	};
	"qwen/qwen3.5-flash": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-flash";
		provider: "zenmux";
	};
	"qwen/qwen3.5-plus": Model<"openai-completions"> & {
		id: "qwen/qwen3.5-plus";
		provider: "zenmux";
	};
	"qwen/qwen3.6-flash": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-flash";
		provider: "zenmux";
	};
	"qwen/qwen3.6-max-preview": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-max-preview";
		provider: "zenmux";
	};
	"qwen/qwen3.6-plus": Model<"openai-completions"> & {
		id: "qwen/qwen3.6-plus";
		provider: "zenmux";
	};
	"qwen/qwen3.7-flash": Model<"openai-completions"> & {
		id: "qwen/qwen3.7-flash";
		provider: "zenmux";
	};
	"qwen/qwen3.7-max": Model<"openai-completions"> & {
		id: "qwen/qwen3.7-max";
		provider: "zenmux";
	};
	"qwen/qwen3.7-plus": Model<"openai-completions"> & {
		id: "qwen/qwen3.7-plus";
		provider: "zenmux";
	};
	"qwen/qwen3.8-max": Model<"openai-completions"> & {
		id: "qwen/qwen3.8-max";
		provider: "zenmux";
	};
	"sapiens-ai/agnes-1.5-flash": Model<"openai-completions"> & {
		id: "sapiens-ai/agnes-1.5-flash";
		provider: "zenmux";
	};
	"sapiens-ai/agnes-1.5-lite": Model<"openai-completions"> & {
		id: "sapiens-ai/agnes-1.5-lite";
		provider: "zenmux";
	};
	"sapiens-ai/agnes-1.5-pro": Model<"openai-completions"> & {
		id: "sapiens-ai/agnes-1.5-pro";
		provider: "zenmux";
	};
	"sapiens-ai/agnes-2.0-flash": Model<"openai-completions"> & {
		id: "sapiens-ai/agnes-2.0-flash";
		provider: "zenmux";
	};
	"stepfun/step-3": Model<"openai-completions"> & {
		id: "stepfun/step-3";
		provider: "zenmux";
	};
	"stepfun/step-3.5-flash": Model<"openai-completions"> & {
		id: "stepfun/step-3.5-flash";
		provider: "zenmux";
	};
	"stepfun/step-3.5-flash-free": Model<"openai-completions"> & {
		id: "stepfun/step-3.5-flash-free";
		provider: "zenmux";
	};
	"stepfun/step-3.7-flash": Model<"openai-completions"> & {
		id: "stepfun/step-3.7-flash";
		provider: "zenmux";
	};
	"stepfun/step-3.7-flash-free": Model<"openai-completions"> & {
		id: "stepfun/step-3.7-flash-free";
		provider: "zenmux";
	};
	"tencent/hunyuan-2.0-thinking": Model<"openai-completions"> & {
		id: "tencent/hunyuan-2.0-thinking";
		provider: "zenmux";
	};
	"tencent/hy3": Model<"openai-completions"> & {
		id: "tencent/hy3";
		provider: "zenmux";
	};
	"tencent/hy3-preview": Model<"openai-completions"> & {
		id: "tencent/hy3-preview";
		provider: "zenmux";
	};
	"volcengine/doubao-seed-1-6-vision": Model<"openai-completions"> & {
		id: "volcengine/doubao-seed-1-6-vision";
		provider: "zenmux";
	};
	"volcengine/doubao-seed-1.8": Model<"openai-completions"> & {
		id: "volcengine/doubao-seed-1.8";
		provider: "zenmux";
	};
	"volcengine/doubao-seed-2.0-code": Model<"openai-completions"> & {
		id: "volcengine/doubao-seed-2.0-code";
		provider: "zenmux";
	};
	"volcengine/doubao-seed-2.0-lite": Model<"openai-completions"> & {
		id: "volcengine/doubao-seed-2.0-lite";
		provider: "zenmux";
	};
	"volcengine/doubao-seed-2.0-mini": Model<"openai-completions"> & {
		id: "volcengine/doubao-seed-2.0-mini";
		provider: "zenmux";
	};
	"volcengine/doubao-seed-2.0-pro": Model<"openai-completions"> & {
		id: "volcengine/doubao-seed-2.0-pro";
		provider: "zenmux";
	};
	"volcengine/doubao-seed-code": Model<"openai-completions"> & {
		id: "volcengine/doubao-seed-code";
		provider: "zenmux";
	};
	"x-ai/grok-4": Model<"openai-completions"> & {
		id: "x-ai/grok-4";
		provider: "zenmux";
	};
	"x-ai/grok-4-fast": Model<"openai-completions"> & {
		id: "x-ai/grok-4-fast";
		provider: "zenmux";
	};
	"x-ai/grok-4-fast-non-reasoning": Model<"openai-completions"> & {
		id: "x-ai/grok-4-fast-non-reasoning";
		provider: "zenmux";
	};
	"x-ai/grok-4.1-fast": Model<"openai-completions"> & {
		id: "x-ai/grok-4.1-fast";
		provider: "zenmux";
	};
	"x-ai/grok-4.1-fast-non-reasoning": Model<"openai-completions"> & {
		id: "x-ai/grok-4.1-fast-non-reasoning";
		provider: "zenmux";
	};
	"x-ai/grok-4.2-fast": Model<"openai-completions"> & {
		id: "x-ai/grok-4.2-fast";
		provider: "zenmux";
	};
	"x-ai/grok-4.2-fast-non-reasoning": Model<"openai-completions"> & {
		id: "x-ai/grok-4.2-fast-non-reasoning";
		provider: "zenmux";
	};
	"x-ai/grok-4.3": Model<"openai-completions"> & {
		id: "x-ai/grok-4.3";
		provider: "zenmux";
	};
	"x-ai/grok-4.5": Model<"openai-completions"> & {
		id: "x-ai/grok-4.5";
		provider: "zenmux";
	};
	"x-ai/grok-4.5-free": Model<"openai-completions"> & {
		id: "x-ai/grok-4.5-free";
		provider: "zenmux";
	};
	"x-ai/grok-build-0.1": Model<"openai-completions"> & {
		id: "x-ai/grok-build-0.1";
		provider: "zenmux";
	};
	"x-ai/grok-code-fast-1": Model<"openai-completions"> & {
		id: "x-ai/grok-code-fast-1";
		provider: "zenmux";
	};
	"xiaomi/mimo-v2-flash": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2-flash";
		provider: "zenmux";
	};
	"xiaomi/mimo-v2-flash-free": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2-flash-free";
		provider: "zenmux";
	};
	"xiaomi/mimo-v2-omni": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2-omni";
		provider: "zenmux";
	};
	"xiaomi/mimo-v2-pro": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2-pro";
		provider: "zenmux";
	};
	"xiaomi/mimo-v2.5": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2.5";
		provider: "zenmux";
	};
	"xiaomi/mimo-v2.5-pro": Model<"openai-completions"> & {
		id: "xiaomi/mimo-v2.5-pro";
		provider: "zenmux";
	};
	"z-ai/glm-4.5": Model<"openai-completions"> & {
		id: "z-ai/glm-4.5";
		provider: "zenmux";
	};
	"z-ai/glm-4.5-air": Model<"openai-completions"> & {
		id: "z-ai/glm-4.5-air";
		provider: "zenmux";
	};
	"z-ai/glm-4.6": Model<"openai-completions"> & {
		id: "z-ai/glm-4.6";
		provider: "zenmux";
	};
	"z-ai/glm-4.6v": Model<"openai-completions"> & {
		id: "z-ai/glm-4.6v";
		provider: "zenmux";
	};
	"z-ai/glm-4.6v-flash": Model<"openai-completions"> & {
		id: "z-ai/glm-4.6v-flash";
		provider: "zenmux";
	};
	"z-ai/glm-4.6v-flash-free": Model<"openai-completions"> & {
		id: "z-ai/glm-4.6v-flash-free";
		provider: "zenmux";
	};
	"z-ai/glm-4.7": Model<"openai-completions"> & {
		id: "z-ai/glm-4.7";
		provider: "zenmux";
	};
	"z-ai/glm-4.7-flash-free": Model<"openai-completions"> & {
		id: "z-ai/glm-4.7-flash-free";
		provider: "zenmux";
	};
	"z-ai/glm-4.7-flashx": Model<"openai-completions"> & {
		id: "z-ai/glm-4.7-flashx";
		provider: "zenmux";
	};
	"z-ai/glm-5": Model<"openai-completions"> & {
		id: "z-ai/glm-5";
		provider: "zenmux";
	};
	"z-ai/glm-5-turbo": Model<"openai-completions"> & {
		id: "z-ai/glm-5-turbo";
		provider: "zenmux";
	};
	"z-ai/glm-5.1": Model<"openai-completions"> & {
		id: "z-ai/glm-5.1";
		provider: "zenmux";
	};
	"z-ai/glm-5.2": Model<"openai-completions"> & {
		id: "z-ai/glm-5.2";
		provider: "zenmux";
	};
	"z-ai/glm-5.2-free": Model<"openai-completions"> & {
		id: "z-ai/glm-5.2-free";
		provider: "zenmux";
	};
	"z-ai/glm-5v-turbo": Model<"openai-completions"> & {
		id: "z-ai/glm-5v-turbo";
		provider: "zenmux";
	};
};
