// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { AIAND_MODELS } from "./providers/aiand.models.ts";
import { AIMLAPI_MODELS } from "./providers/aimlapi.models.ts";
import { ALIBABA_CODING_PLAN_MODELS } from "./providers/alibaba-coding-plan.models.ts";
import { ALIBABA_TOKEN_PLAN_MODELS } from "./providers/alibaba-token-plan.models.ts";
import { AMAZON_BEDROCK_MODELS } from "./providers/amazon-bedrock.models.ts";
import { ANT_LING_MODELS } from "./providers/ant-ling.models.ts";
import { ANTHROPIC_MODELS } from "./providers/anthropic.models.ts";
import { AZURE_OPENAI_RESPONSES_MODELS } from "./providers/azure-openai-responses.models.ts";
import { BASETEN_MODELS } from "./providers/baseten.models.ts";
import { BEDROCK_MANTLE_MODELS } from "./providers/bedrock-mantle.models.ts";
import { CEREBRAS_MODELS } from "./providers/cerebras.models.ts";
import { CLOUDFLARE_AI_GATEWAY_MODELS } from "./providers/cloudflare-ai-gateway.models.ts";
import { CLOUDFLARE_WORKERS_AI_MODELS } from "./providers/cloudflare-workers-ai.models.ts";
import { COREWEAVE_MODELS } from "./providers/coreweave.models.ts";
import { DEEPSEEK_MODELS } from "./providers/deepseek.models.ts";
import { FIREPASS_MODELS } from "./providers/firepass.models.ts";
import { FIREWORKS_MODELS } from "./providers/fireworks.models.ts";
import { GITHUB_COPILOT_MODELS } from "./providers/github-copilot.models.ts";
import { GMI_CLOUD_MODELS } from "./providers/gmi-cloud.models.ts";
import { GOOGLE_MODELS } from "./providers/google.models.ts";
import { GOOGLE_VERTEX_MODELS } from "./providers/google-vertex.models.ts";
import { GROQ_MODELS } from "./providers/groq.models.ts";
import { HUGGINGFACE_MODELS } from "./providers/huggingface.models.ts";
import { KILO_MODELS } from "./providers/kilo.models.ts";
import { KIMI_CODE_MODELS } from "./providers/kimi-code.models.ts";
import { KIMI_CODING_MODELS } from "./providers/kimi-coding.models.ts";
import { LITELLM_MODELS } from "./providers/litellm.models.ts";
import { LM_STUDIO_MODELS } from "./providers/lm-studio.models.ts";
import { META_MODELS } from "./providers/meta.models.ts";
import { MINIMAX_MODELS } from "./providers/minimax.models.ts";
import { MINIMAX_CN_MODELS } from "./providers/minimax-cn.models.ts";
import { MINIMAX_CODE_MODELS } from "./providers/minimax-code.models.ts";
import { MINIMAX_CODE_CN_MODELS } from "./providers/minimax-code-cn.models.ts";
import { MISTRAL_MODELS } from "./providers/mistral.models.ts";
import { MOONSHOTAI_MODELS } from "./providers/moonshotai.models.ts";
import { MOONSHOTAI_CN_MODELS } from "./providers/moonshotai-cn.models.ts";
import { NANOGPT_MODELS } from "./providers/nanogpt.models.ts";
import { NOVITA_MODELS } from "./providers/novita.models.ts";
import { NVIDIA_MODELS } from "./providers/nvidia.models.ts";
import { OPENAI_MODELS } from "./providers/openai.models.ts";
import { OPENAI_CODEX_MODELS } from "./providers/openai-codex.models.ts";
import { OPENCODE_MODELS } from "./providers/opencode.models.ts";
import { OPENCODE_GO_MODELS } from "./providers/opencode-go.models.ts";
import { OPENCODE_ZEN_MODELS } from "./providers/opencode-zen.models.ts";
import { OPENROUTER_MODELS } from "./providers/openrouter.models.ts";
import { QIANFAN_MODELS } from "./providers/qianfan.models.ts";
import { QWEN_PORTAL_MODELS } from "./providers/qwen-portal.models.ts";
import { SAKANA_MODELS } from "./providers/sakana.models.ts";
import { SILICONFLOW_MODELS } from "./providers/siliconflow.models.ts";
import { SILICONFLOW_CN_MODELS } from "./providers/siliconflow-cn.models.ts";
import { SYNTHETIC_MODELS } from "./providers/synthetic.models.ts";
import { TOGETHER_MODELS } from "./providers/together.models.ts";
import { UMANS_MODELS } from "./providers/umans.models.ts";
import { VENICE_MODELS } from "./providers/venice.models.ts";
import { VERCEL_AI_GATEWAY_MODELS } from "./providers/vercel-ai-gateway.models.ts";
import { VLLM_MODELS } from "./providers/vllm.models.ts";
import { WAFER_SERVERLESS_MODELS } from "./providers/wafer-serverless.models.ts";
import { XAI_MODELS } from "./providers/xai.models.ts";
import { XIAOMI_MODELS } from "./providers/xiaomi.models.ts";
import { XIAOMI_TOKEN_PLAN_AMS_MODELS } from "./providers/xiaomi-token-plan-ams.models.ts";
import { XIAOMI_TOKEN_PLAN_CN_MODELS } from "./providers/xiaomi-token-plan-cn.models.ts";
import { XIAOMI_TOKEN_PLAN_SGP_MODELS } from "./providers/xiaomi-token-plan-sgp.models.ts";
import { ZAI_MODELS } from "./providers/zai.models.ts";
import { ZAI_CODING_CN_MODELS } from "./providers/zai-coding-cn.models.ts";
import { ZENMUX_MODELS } from "./providers/zenmux.models.ts";
import { ZHIPU_CODING_PLAN_MODELS } from "./providers/zhipu-coding-plan.models.ts";

export const MODELS = {
	"aiand": AIAND_MODELS,
	"aimlapi": AIMLAPI_MODELS,
	"alibaba-coding-plan": ALIBABA_CODING_PLAN_MODELS,
	"alibaba-token-plan": ALIBABA_TOKEN_PLAN_MODELS,
	"amazon-bedrock": AMAZON_BEDROCK_MODELS,
	"ant-ling": ANT_LING_MODELS,
	"anthropic": ANTHROPIC_MODELS,
	"azure-openai-responses": AZURE_OPENAI_RESPONSES_MODELS,
	"baseten": BASETEN_MODELS,
	"bedrock-mantle": BEDROCK_MANTLE_MODELS,
	"cerebras": CEREBRAS_MODELS,
	"cloudflare-ai-gateway": CLOUDFLARE_AI_GATEWAY_MODELS,
	"cloudflare-workers-ai": CLOUDFLARE_WORKERS_AI_MODELS,
	"coreweave": COREWEAVE_MODELS,
	"deepseek": DEEPSEEK_MODELS,
	"firepass": FIREPASS_MODELS,
	"fireworks": FIREWORKS_MODELS,
	"github-copilot": GITHUB_COPILOT_MODELS,
	"gmi-cloud": GMI_CLOUD_MODELS,
	"google": GOOGLE_MODELS,
	"google-vertex": GOOGLE_VERTEX_MODELS,
	"groq": GROQ_MODELS,
	"huggingface": HUGGINGFACE_MODELS,
	"kilo": KILO_MODELS,
	"kimi-code": KIMI_CODE_MODELS,
	"kimi-coding": KIMI_CODING_MODELS,
	"litellm": LITELLM_MODELS,
	"lm-studio": LM_STUDIO_MODELS,
	"meta": META_MODELS,
	"minimax": MINIMAX_MODELS,
	"minimax-cn": MINIMAX_CN_MODELS,
	"minimax-code": MINIMAX_CODE_MODELS,
	"minimax-code-cn": MINIMAX_CODE_CN_MODELS,
	"mistral": MISTRAL_MODELS,
	"moonshotai": MOONSHOTAI_MODELS,
	"moonshotai-cn": MOONSHOTAI_CN_MODELS,
	"nanogpt": NANOGPT_MODELS,
	"novita": NOVITA_MODELS,
	"nvidia": NVIDIA_MODELS,
	"openai": OPENAI_MODELS,
	"openai-codex": OPENAI_CODEX_MODELS,
	"opencode": OPENCODE_MODELS,
	"opencode-go": OPENCODE_GO_MODELS,
	"opencode-zen": OPENCODE_ZEN_MODELS,
	"openrouter": OPENROUTER_MODELS,
	"qianfan": QIANFAN_MODELS,
	"qwen-portal": QWEN_PORTAL_MODELS,
	"sakana": SAKANA_MODELS,
	"siliconflow": SILICONFLOW_MODELS,
	"siliconflow-cn": SILICONFLOW_CN_MODELS,
	"synthetic": SYNTHETIC_MODELS,
	"together": TOGETHER_MODELS,
	"umans": UMANS_MODELS,
	"venice": VENICE_MODELS,
	"vercel-ai-gateway": VERCEL_AI_GATEWAY_MODELS,
	"vllm": VLLM_MODELS,
	"wafer-serverless": WAFER_SERVERLESS_MODELS,
	"xai": XAI_MODELS,
	"xiaomi": XIAOMI_MODELS,
	"xiaomi-token-plan-ams": XIAOMI_TOKEN_PLAN_AMS_MODELS,
	"xiaomi-token-plan-cn": XIAOMI_TOKEN_PLAN_CN_MODELS,
	"xiaomi-token-plan-sgp": XIAOMI_TOKEN_PLAN_SGP_MODELS,
	"zai": ZAI_MODELS,
	"zai-coding-cn": ZAI_CODING_CN_MODELS,
	"zenmux": ZENMUX_MODELS,
	"zhipu-coding-plan": ZHIPU_CODING_PLAN_MODELS,
} as const;
