/** Runtime v3 事件目录；新增事件必须同时提供独立 payload schema。 */

export const RUNTIME_EVENT_TYPES = [
	"session.created",
	"session.forked",
	"session.migration_started",
	"session.legacy_message_imported",
	"session.migration_committed",
	"session.migration_failed",
	"session.stop_requested",
	"session.stopped",
	"session.closed",
	"session.corrupted",
	"session.repair_reported",
	"session.handoff_requested",
	"session.handoff_committed",
	"session.handoff_failed",
	"session.deletion_planned",
	"session.deletion_tombstoned",
	"session.deletion_committed",
	"session.deletion_failed",
	"input.source_recorded",
	"input.declassification_decided",
	"conversation.message_recorded",
	"orchestrator.journal_committed",
	"goal.created",
	"goal.transitioned",
	"task.created",
	"task.definition_revised",
	"task.transitioned",
	"task.output_bound",
	"turn.started",
	"turn.finished",
	"turn.interrupted",
	"turn.failed",
	"model.routed",
	"model.requested",
	"model.finished",
	"model.failed",
	"tool.requested",
	"tool.authorized",
	"tool.started",
	"tool.finished",
	"tool.interrupted",
	"tool.failed",
	"permission.requested",
	"permission.decided",
	"permission.expired",
	"permission.revoked",
	"capability.rate_limit_recorded",
	"workspace.bound",
	"workspace.validation_recorded",
	"workspace.released",
	"sandbox.resolved",
	"sandbox.execution_recorded",
	"executor.requested",
	"executor.execution_recorded",
	"queue.enqueued",
	"queue.claimed",
	"queue.consumed",
	"queue.cancelled",
	"checkpoint.created",
	"checkpoint.rewound",
	"artifact.intent_recorded",
	"artifact.aborted",
	"artifact.created",
	"artifact.committed",
	"resource.snapshot",
	"resource.lifecycle_recorded",
	"resource.approved",
	"resource.revoked",
	"mode.transitioned",
	"plan.proposed",
	"plan.approved",
	"plan.rejected",
	"plan.invalidated",
	"context.assembled",
	"compaction.started",
	"compaction.completed",
	"compaction.failed",
	"compaction.suppressed",
	"memory.proposed",
	"memory.approved",
	"memory.rejected",
	"memory.published",
	"memory.searched",
	"memory.injected",
	"memory.revoked",
	"memory.expired",
	"budget.transaction_committed",
	"verification.started",
	"verification.finished",
	"episode.manifest_committed",
	"episode.seal_recorded",
	"change_proposal.recorded",
	"draft_pr.requested",
	"draft_pr.created",
	"draft_pr.failed",
	"human_gate.requested",
	"human_gate.decided",
	"command.claimed",
	"command.applied",
	"command.rejected",
	"command.reconciliation_required",
	"runtime.replacement_prepared",
	"runtime.generation_activated",
	"runtime.replacement_failed",
	"daemon.shutdown_requested",
	"daemon.shutdown_completed",
	"daemon.shutdown_failed",
	"policy.effective_recorded",
	"policy.normalization_recorded",
	"cost.recorded",
	"cost.reconciled",
	"telemetry.delivery_recorded",
	"finding.transitioned",
	"agent.root_registered",
	"agent.root_revalidated",
	"agent.spawn_requested",
	"agent.spawned",
	"agent.spawn_failed",
	"agent.transitioned",
	"agent.paused",
	"agent.stopped",
	"agent.partial_committed",
	"agent.cursor_advanced",
	"agent.artifact_reported",
	"agent.residency_changed",
	"agent.budget_rebound",
	"agent.turn_recorded",
	"agent.launch_recorded",
	"agent.resume_revalidated",
	"agent.handoff_requested",
	"agent.handoff_committed",
	"agent.handoff_failed",
	"agent.merge_requested",
	"agent.merge_committed",
	"agent.merge_conflicted",
	"agent.merge_failed",
	"agent.finished",
	"agent.failed",
	"agent.cleanup_requested",
	"agent.runtime_released",
	"agent.workspace_released",
	"agent.budget_settled",
	"agent.cleanup_reconciliation_required",
	"agent.cleanup_completed",
	"lease.acquired",
	"lease.taken_over",
	"lease.released",
] as const;

export type RuntimeEventType = (typeof RUNTIME_EVENT_TYPES)[number];
export type RuntimeEventStreamScope = "session" | "authority_tenant";

const AUTHORITY_TENANT_COMPATIBLE_EVENT_TYPES: ReadonlySet<RuntimeEventType> = new Set([
	"resource.snapshot",
	"resource.lifecycle_recorded",
	"resource.approved",
	"resource.revoked",
]);

const AUTHORITY_TENANT_ONLY_EVENT_TYPES: ReadonlySet<RuntimeEventType> = new Set([
	"session.handoff_requested",
	"session.handoff_committed",
	"session.handoff_failed",
	"session.deletion_planned",
	"session.deletion_tombstoned",
	"session.deletion_committed",
	"session.deletion_failed",
	"command.claimed",
	"command.applied",
	"command.rejected",
	"command.reconciliation_required",
	"runtime.replacement_prepared",
	"runtime.generation_activated",
	"runtime.replacement_failed",
	"daemon.shutdown_requested",
	"daemon.shutdown_completed",
	"daemon.shutdown_failed",
	"policy.effective_recorded",
	"policy.normalization_recorded",
]);

/** 每个 canonical event type 的封闭 stream scope；authority lifecycle 事件后续独立扩展。 */
export const RUNTIME_EVENT_ALLOWED_STREAM_SCOPES = Object.freeze(
	Object.fromEntries(
	RUNTIME_EVENT_TYPES.map((type) => [
			type,
			AUTHORITY_TENANT_ONLY_EVENT_TYPES.has(type)
				? (["authority_tenant"] as const)
				: AUTHORITY_TENANT_COMPATIBLE_EVENT_TYPES.has(type)
				? (["session", "authority_tenant"] as const)
				: (["session"] as const),
		]),
	),
) as unknown as Readonly<Record<RuntimeEventType, readonly RuntimeEventStreamScope[]>>;

const EVENT_TYPE_SET: ReadonlySet<string> = new Set(RUNTIME_EVENT_TYPES);

export function isKnownRuntimeEventType(value: unknown): value is RuntimeEventType {
	return typeof value === "string" && EVENT_TYPE_SET.has(value);
}

export function isRuntimeEventTypeAllowedInStream(
	type: RuntimeEventType,
	scope: RuntimeEventStreamScope,
): boolean {
	return RUNTIME_EVENT_ALLOWED_STREAM_SCOPES[type].includes(scope);
}
